### ISSUE TITLE
Request - option to hide additional song name toolbar.

### ISSUE THREAD

**Issue by radioproektor** [losnoco/Cog#101]
It is nice that you bring back option to toggle toolbar style to classic view, but i noticed some strange additional toolbar with song name. That toolbar is useless in classic toolbar view. Also when playback starts it appears and disappears with some very annoying jumping effect.
So here is request - option to hide additional song name toolbar when toggle toolbar style to classic view. Or just option to globally turn that toolbar on/off.
![Screen Shot 2021-02-10 at 9 41 22 AM](https://user-images.githubusercontent.com/35053925/107480258-f9754780-6b84-11eb-8620-ef79e27ca4be.jpg)

**Comment by nevack** [comment]
This toolbar helps to scroll to current entry in long list of songs.
If you have ideas, how to reimplement this feature without additional toolbar - you're welcome!

**Comment by radioproektor** [comment]
Hmm... I use Cog starting from very early Mac OS X Leopard 10.5 days and never had problem with scroll to current entry. In most cases i don't use too long lists, but if i really lost in long list i can just press Previous/Next button and this brings the list to current track.
That jumping toolbar is very nervous. It jumps in very annoying way and also slightly changes height when song name text appears in it.
Note that i am not against that toolbar, because it is useful as current track name indicator when use BigSur-like single row top toolbar that don't provide current track info. But in classic pre-BigSur toolbar style it just waste space and doubles track name info already visible in main top toolbar.

**Comment by radioproektor** [comment]
So is it impossible at least to make that bar with fixed height to avoid jumping effect?

**Comment by nevack** [comment]
> So is it impossible at least to make that bar with fixed height to avoid jumping effect?
Do you want it always stay visible, even if no track playing?

**Comment by radioproektor** [comment]
1. I personally prefer option to completely hide it because i just don't need it, especially when i use classic toolbar style.
2. For those who use BigSur-style toolbar toggle i guess i prefer it always stay visible, even if no track playing.

**Comment by kode54** [comment]
How about we just drop all post-Big Sur changes and make no further attempts to adopt newer APIs and styles.

**Comment by nevack** [comment]
Now that additional bar is shown only if compact titlebar is shown or if Window is in Fullscreen (where titlebar is not visible)
