### ISSUE TITLE
Too wide Search button in Toolbar

### ISSUE THREAD

**Issue by radioproektor** [losnoco/Cog#102]
In newer versions of Cog Search button in toolbar is too wide. It waste too many space and limits the length of seek control.
Examples:
![2](https://user-images.githubusercontent.com/35053925/107509662-8632fc00-6bab-11eb-980f-ae0019012b88.jpg)
![1](https://user-images.githubusercontent.com/35053925/107509673-89c68300-6bab-11eb-87ba-cd71a5a46339.jpg)

P.S. Also space at the left of seek control is larger than at the right. Not too pretty.

**Comment by radioproektor** [comment]
Buttons length is also less compact in newer versions

**Comment by radioproektor** [comment]
And also in newer version "Current Time" button height is smaller that Search bar height.

**Comment by nevack** [comment]
Search field behaviour is defined by macOS, it's width is limited, if you resize width more, you'll see that Search field no longer expands, and Position Slider takes remaining space.

**Comment by nevack** [comment]
@radioproektor Can you please provide Cog version for each Screenshot?

**Comment by radioproektor** [comment]
Yes, sorry. Examples are from Cog-3b628c398 and Cog-a6aaeafdc

**Comment by nevack** [comment]
Okay, need to bisect this, https://github.com/losnoco/Cog/compare/3b628c398..a6aaeafdc

I think it's mostly because of SDK upgraded to 11.+

**Comment by kode54** [comment]
Has this gone anywhere?

**Comment by nevack** [comment]
> Has this gone anywhere?

This is expected behaviour for AppKit's NSSearchToolbarItem introduced with 11.0 SDK and backward compatible with previous versions. We do not control sizing of expanded Search control, AppKit does.
