### ISSUE TITLE
Can't command-F to search anymore?

### ISSUE THREAD

**Issue by ardunster** [losnoco/Cog#104]
**Describe**
I've had Cog on my Mac for a while, but haven't used it much as I don't often listen to music from my laptop. Tonight I realized I had a bunch of music on an SD card and could throw it in and listen so I did so, put all the music in the playlist, and I'm 99% sure I used command-F to search for the specific track I was looking for (I certainly didn't scroll through the just-added three days worth of music).  After listening for a while I was sad that I didn't have any functionality to sort my playlist and figured I should update in case there were new features. Ran "check for updates" which updated from 1127 to 1405 and now command-F doesn't do anything and I can't find any other text search find feature (there are menu items for 'search by artist' and 'search by album'; neither is what I want, especially if I'm looking for a specific song title!) 

**Expected behavior**
Pressing command-F should bring up a text search menu to find all files/playlist entries with the given text.

**Version information:***
 - macOS version: 10.15.7 (19H2)
 - Cog version: Version 1405 (1405-g1ddce2395)

**Comment by ardunster** [comment]
Also don't know if it's relevant but I was disappointed that when restarting, Cog didn't bring up the file it was on when I closed it but started over at the beginning of the playlist (which is why I even found that command-f wasn't working....)

**Comment by kode54** [comment]
Regarding the Find window, I tested on Big Sur, apparently the popping open action isn't working prior to that? In which case, it's a bug.

**Comment by ardunster** [comment]
Not quite sure what you mean, but I'm still running Catalina, I haven't upgraded to Big Sur, if that is what you are saying. It did work before I ran the update on Cog, but doesn't work now. 

I looked through the code a bit to see if I could theorize about the cause but I'm not sure where the toolbar code is so haven't come up with anything useful on that front.

**Comment by kode54** [comment]
Cmd+F is a menu shortcut, and the menu is in the main application template, MainMenu.xib.
