### ISSUE TITLE
Make the now playing popout enable/disable with the compact titlebar mode (formerly Remove compact titlebar mode)

### ISSUE THREAD

**Issue by kode54** [losnoco/Cog#105]
**Describe**
~~I'm apparently the only person who actually likes the compact titlebar mode, so let's remove it entirely. Also remove that now-playing popout thing that will no longer be necessary.~~

Alter the now playing popout in the main window to only appear if the compact titlebar is enabled.

**Comment by nevack** [comment]
I like compact title bar. :/

**Comment by kode54** [comment]
I do too. Maybe we can make a compromise then. Somehow get rid of that now playing notifier when the compact titlebar is disabled.

**Comment by kode54** [comment]
Sorry for the rash initial post, I get kind of fed up when changes I like are vocally outspoken against in my inbox.
