### ISSUE TITLE
Linux native port

### ISSUE THREAD

**Issue by alpharde** [losnoco/Cog#107]
Oh god please and let me ditch running foobar on wine.

**Comment by nevack** [comment]
> Oh god please and let me ditch running foobar on wine.

Have a look at https://github.com/DeaDBeeF-Player/deadbeef

**Comment by alpharde** [comment]
Deadbeef is nice however most plugins are badly outdated, that's mainly why I'm stuck with foobar.

**Comment by kode54** [comment]
DeaDBeeF doesn't even have gapless AAC support. An issue was opened 3 years ago that suggested work was being made to look into migrating to FDK-AAC, but that went nowhere.

Yeah, this isn't likely to happen, unless you know of a quick way to port Objective-C and Swift with heavy Cocoa and macOS system library use to Linux.

**Comment by alpharde** [comment]
Welp
Guess I'll have to wait until these plugins drop on gstreamer, _someday_.
