### ISSUE TITLE
Volume keys (f10, f11, f12) not working

### ISSUE THREAD

**Issue by montajd** [losnoco/Cog#11]
volume controls not working currently with latest release. Cmd+up and Cmd+down work when app has focus.

**Comment by kode54** [comment]
This must be a long standing issue, as I've never touched the volume control keys. The only recent change I made was so that the input hook would disable itself when System Preferences is open.

**Comment by 1000hz** [comment]
Also having this issue on High Sierra. It was introduced in `k54-980-g7cfcd87c`. Browsing the commits between that release and the previous one, I'm guessing it has something to do with 18176782. Issue is reproducible even if System Preferences are closed.

**Comment by montajd** [comment]
thank you!

**Comment by megadr01d** [comment]
@montajd Please close the issue if fixed.

**Comment by nevack** [comment]
`ThirdParty/SPMediaKeyTap` dep was removed, closing as outdated
