### ISSUE TITLE
Include in homebrew

### ISSUE THREAD

**Issue by reagle** [losnoco/Cog#117]
I was looking to replace clementine, which is fine but a CPU hog, even when idle. Cog is working great! I'd be nice to have it in homebrew.

**Comment by nevack** [comment]
Okay, we'll try to push it as Homebrew Cask

**Comment by nevack** [comment]
@reagle My bad, Cog is already available as `kode54-cog` cask

**Comment by reagle** [comment]
What's "kode54"? There's no other conflicting names, and if you want specificity, perhaps `cog-player`?

**Comment by nevack** [comment]
> What's "kode54"? There's no other conflicting names, and if you want specificity, perhaps `cog-player`?

That's Christopher's username.

I don't know, if there's a way to rename existing Cask. 

Btw, `cog` name is free.
```sh
$ brew search cog
==> Formulae
cogl                                                                        terracognita
==> Casks
kode54-cog
```

**Comment by nevack** [comment]
@reagle Reopen till merged https://github.com/Homebrew/homebrew-cask/pull/100444

**Comment by esaruoho** [comment]
pls make it cog instead of kode54-cog. i'd never think of installing "kode54-cog" if i was on a new computer. but i might think of installing "cog" if i was on a new computer..

**Comment by nevack** [comment]
@esaruoho It's `cog` now!
PR above is merged. Closing the issue.
