### ISSUE TITLE
App Sandbox breaks Sparkle

### ISSUE THREAD

**Issue by kode54** [losnoco/Cog#119]
**Describe**
Due to a known upstream issue, Sparkle support is completely broken by App Sandbox. This is a 6 year old issue that still hasn't been dealt with.

https://github.com/sparkle-project/Sparkle/issues/499

Guess we need to switch to 2.0:

https://github.com/sparkle-project/Sparkle/issues/1523

**Comment by nevack** [comment]
@kode54 2.0 is in alpha as I see, maybe revert sandbox for now?
We can create issue for sandbox and develop support for it in separate branch.

**Comment by nevack** [comment]
https://github.com/losnoco/Cog/pull/120

**Comment by nevack** [comment]
Fixed for `sandbox` branch in #120
