### ISSUE TITLE
Sandboxing in Cog-4300fdb15 is too spammy with "grant access to this folder" dialogs

### ISSUE THREAD

**Issue by pitermach** [losnoco/Cog#122]
I just updated cog to the latest version as of writing (see the title) from one that wasn't sandboxed, and immediately reverted to the last version that wasn't. I don't know how many of these bugs can be fixed and which ones are just a result of what restrictions sandboxing imposes, but since they're very closely related I put them all in one issue. Here's what I found:

- The "click Open to grant permissions" dialog won't take no for an answer. If you press Cancel, it'll just keep coming back until you press Open.
- Opening any file in finder asks to grant permission, and this doesn't seem to be remembered. If you open a file, grant permission, close Cog, then open the same file you will be asked to grant permission again.
- Likewise, pressing enter to load a folder from the file tree pops up grant permission prompts, except these pop up recursively for any subdirectories. This coupled with the fact you can't just cancel out of these dialogs means loading a folder with a lot of subfolders is very fun. And just like with opening files from Finder, these aren't remembered so if you choose to load the same folder again in the future you'll get the same prompts again.
- The directory tree doesn't remember its content after a restart. I pointed it at my network drive, and after a restart the tree came up empty, I was able to get it back only after selecting "choose" in the directory popup and browsing to it again. This works fine in the pre-sandbox version.

I also tried giving Cog full disk access in system preferences but that didn't seem to change anything. If you're making these changes to eventually make an App Store release, then I think it'd be good to also offer a non-store unrestricted version or make it work better with the full disk access setting since I'm usually running from the Git builds anyway and prefer less restricted versions of apps in general, taking full responsibility for any security implications of a less sandboxed app of course. ☺️ Getting the singular "Cog wants access to your documents/downloads/desktop folder" prompts is one thing, having one every time you open anything is quite another. Other than these issues that just came back, I really love the app and that I can play all of my chip tunes and other music with it, I'm really happy that someone is still working on it!

System specs: MacBook Air 2020 (Apple M1 CPU), Mac OS 11.3 Public Beta 2

**Comment by kode54** [comment]
Thus, I agree, we never should have sandboxed the app, the sandboxing related commits should all be reverted permanently, and all hope of ever getting listed in the App Store should be discarded.

**Comment by kode54** [comment]
Sandboxing has been moved to another branch, where it will probably stay forever.

I could restrict sandboxing to just the exact files or folders that the user opens, but then external album artwork won't work.

**Comment by kode54** [comment]
Also I think there may have been a bug with dragging files around triggering the pruning of the bookmark database. You must reorder your playlist entries with drag operations an awful lot.

**Comment by pitermach** [comment]
Yeah. The idea is definitely not without Merit, with how well the app supports less common tracker formats it would probably find an audience in the app store, and some of these bugs could be fixed to be less annoying. For instance, Transmit which is an FTP client has both an App Store and non-app store version, with the latter also requiring manually granting folder access (though their [knowledge base article](https://library.panic.com/transmit/transmit5/sandboxing/) saying granting access to 1 folder should also allow subdirectories to be accessed, so it should be possible to make the experience less annoying, but some features like the file tree would probably still feel a little less easy to use. 

For what it's worth, all of my Mac media playing needs are covered by VLC and Cog, and neither of these apps is in the store.

**Comment by JanX2** [comment]
My perspective is that sandboxing has merit and users should be advised to grant Full Disk Access in the macOS Security preference pane, if they don’t care about security. 

Cog uses a huge amount of 3rd party code with no hope of it ever being reviewed for issues.

 What do you think?

**Comment by pitermach** [comment]
I just remembered about this issue after pulling the latest updates and seeing the sandboxing changes. Needless to say the experience now is much better, I did get prompted but only once and it was much clearer what folders were going to be accessible. It's only fair I close this issue, hopefully you can find an even bigger audience for the app. ☺️
