### ISSUE TITLE
Mini window complaints

### ISSUE THREAD

**Issue by kode54** [losnoco/Cog#125]
**Describe**
User complained that the mini window is now more like a "maxi" window that "takes up half the screen". Suggests that Apple sells mostly 13" laptops like the one they own, so that's the display target that we should develop for.

So with that in mind, I guess we should be setting our desktops to 1280x800 to get a feel for what that's like.

**To Reproduce** (delete if not applicable)
1. Set display to 1280x800
2. Switch to mini window
3. Marvel at how little fits on the screen now

**Expected behavior**
Should support setting the Mini window as small as a single control, or even just the stoplights and the song name.

**Version information:***
 - macOS version: 10.13.6
 - Cog version: 1443-gf86f7dc5

**Additional context**
I hope I'm not doctoring their words too much this time. It's not entirely my fault that the smallest laptop I've ever bought is 15", and the smallest desktop display I've ever bought is 24". The only iMac I've regularly used, until I sold it, was also the 27" 5K monster, too bad it only retained 1/4 its purchase price. Also both these machines overheat like crazy, lovely thermal designs.

Full disclosure: My favorite Mac is not actually a Mac. But I do have access to two actual Macs, I just don't like using them as much. One of them is my dad's iMac, and the other is my second personal Mac purchase, a 2014 15" MBP, built in 2015, and has already had its batteries replaced once out of warranty due to it becoming a spicy pillow. The MBP takes literally twice as long to compile Cog in Archive mode compared to the desktop "Mac", and in the process turns both its fans up to maximum and nearly reaches the thermal cutoff.

Would buy an M1 Mini, but literally can't afford it.

**Comment by nevack** [comment]
I'm using MacBook Pro 2019 16", but I can ask my friends to test on 13" device.
But I just don't understand what is the issue with mini window.
Maybe screenshot will help.

For now I can offer to remove minimum content/window size constraint and advice users to use alternative toolbar style with separate title row

**Comment by piaci** [comment]
here is a full-screen-shot of three music players in their minimal state. cog only has the info enabled, still cannot be resized to smaller:

<img width="1440" alt="Screen Shot 2021-03-03 at 14 10 36" src="https://user-images.githubusercontent.com/4758798/109810933-7fd3f500-7c2a-11eb-90a8-5f0847f2453b.png">

**Comment by nevack** [comment]
Should be fixed in https://github.com/losnoco/Cog/commit/e5e9dffe0f38744aa25b9f2f8503b6bf685fb876

Screenshot:
![image](https://user-images.githubusercontent.com/8330119/109863338-93a34980-7c72-11eb-878e-9ecad0bee928.png)
![image](https://user-images.githubusercontent.com/8330119/109863360-99992a80-7c72-11eb-96ff-838c017754bd.png)

Tell me if the issue can be closed.

**Comment by piaci** [comment]
yep, now it has the correct mini size, thanks.
