### ISSUE TITLE
Fix or re-implement scripting automation

### ISSUE THREAD

**Issue by kode54** [losnoco/Cog#126]
**Describe**
The scripting automation files in the project now are 15 years old, and haven't been touched since major interface changes have happened. They seem to partially work, but are not maintainable in their current state, and need to be redone using the newer XML definition method that compiles to the equivalent of the two files currently in the repo and app.

**Comment by nevack** [comment]
@kode54 What scripts are to be updated?
Maybe some of them more important now?

**Comment by kode54** [comment]
The current files are in the Cog.script* files in the root folder, but from what I can tell from Apple documentation, writing those two files manually is an old way to do it, and the new way involves writing an XML formatted .sdef or so file, which Xcode compiles to produce the correct result.

It requires declaring arrays/dictionaries and their member properties that are compatible with AppleScript, and what type the variables are.

**Comment by kode54** [comment]
Maybe optionally remove it entirely, it doesn't seem all that useful.

**Comment by kode54** [comment]
Bumping this issue, it should be fixed. For instance, so that @kddlb 's lyrics fetching app can interact with the player.

**Comment by kode54** [comment]
@kddlb enjoy.
