### ISSUE TITLE
Shuffle and randomize playlist icons look identical.

### ISSUE THREAD

**Issue by reactorcoremeltdown** [losnoco/Cog#129]
**Describe**
Both icons look identical for "shuffle mode" and "randomize playlist" toolbar buttons.

**To Reproduce** (delete if not applicable)
1. Open Cog
2. Add both "shuffle mode" and "randomize playlist" buttons to the toolbar
3. Experience some confusion

**Expected behavior**
Would it be better to use a dice icon for playlist randomization maybe?

**Screenshots**
![image](https://user-images.githubusercontent.com/674257/110637492-bae7a280-81ad-11eb-985a-a8142adc705b.png)

**Version information:***
 - macOS version: 11.2.2
 - Cog version: Version 1449 (1449-gba7aaec6)

**Additional context**
This is just a suggestion, please feel free to close if this goes against your design policies. And thanks a lot for bringing the best player for Mac back to life!

**Comment by nevack** [comment]
Hm, I really have no ideas, what symbol can replace current one. IMHO, dice is not the one we want.

**Comment by Oleg-Chashko** [comment]
@kode54 

I'll think about what to draw. Or the future awaits us:
![light](https://user-images.githubusercontent.com/62497891/151160818-d3fdf769-b0bc-4ec8-9bb1-291f37ba708a.png)

**Comment by Oleg-Chashko** [comment]
Example:
<img width="381" alt="Screen Shot 2022-01-26 at 15 38 57" src="https://user-images.githubusercontent.com/62497891/151183658-bbe3b4d2-ac07-4b6d-a9b1-d318a8586d3a.png">

**Comment by Oleg-Chashko** [comment]
I can draw something else. Write if you need it.

**Comment by kode54** [comment]
Looks good, I'll put incorporation on my todo list for a future build.

**Comment by Oleg-Chashko** [comment]
- Mockup:
<img width="1083" alt="Screen Shot 2022-01-27 at 13 09 08" src="https://user-images.githubusercontent.com/62497891/151357384-8f1bc2d0-f3e6-421a-94a7-93591bbfdd27.png">

**Comment by nevack** [comment]
We could use `dice` for Randomize action
![Uploading image.png…]()

**Comment by Oleg-Chashko** [comment]
I thought but did not want to draw. I have an association (dice) with the casino.

- A light brush sketch:
<img width="418" alt="Screen Shot 2022-01-27 at 17 26 50" src="https://user-images.githubusercontent.com/62497891/151401816-0e7852c2-e220-4bae-bbba-db50a49035d7.png">

**Comment by Oleg-Chashko** [comment]
> Take a look at https://developer.apple.com/sf-symbols/

@nevack 
Thanks, I'll take a look.
I can draw it myself, without any copyrights, whether they are there or not.

**Comment by Oleg-Chashko** [comment]
<img width="336" alt="Screen Shot 2022-01-27 at 19 54 25" src="https://user-images.githubusercontent.com/62497891/151425430-fd49cb11-9d0d-4151-bf4b-d68cdaa552cf.png">


Files: Black_colour_(png), (pdf)
[Cog_Randomize.pdf.zip](https://github.com/losnoco/Cog/files/7953117/Cog_Randomize.pdf.zip)
[Cog_Randomize.png.zip](https://github.com/losnoco/Cog/files/7953118/Cog_Randomize.png.zip)

**Comment by kode54** [comment]
I like this last one:

> <img alt="Mockup" width="1083" src="https://user-images.githubusercontent.com/62497891/151426352-33408124-a2fd-4ef9-9cc7-4f82c8129a75.png">

But the lines on the playlist object need to be thicker for non-Retina displays, otherwise it looks like a blur. It looks perfect on my 4K monitor, though.

**Comment by kode54** [comment]
Also, please, for future reference. Please only use Black shapes in these templates. No white shapes, that doesn't work for templates.

All objects with holes in them must be assembled as objects with actual cutouts in them. Otherwise, I have to render the vector to a high res PNG and trace it to a vector all over again. It'll still look the same, but it needs to be purely black shapes, no layered white shapes, because those don't work for template vectors.

**Comment by Oleg-Chashko** [comment]
I've added sources created in the Sketch app. 
Modify and translate them into other formats as you wish. 
You own them now.

- **For non-Retina displays:**

![Cog_Randomize_New_thicker_for_non-Retina_displays copy](https://user-images.githubusercontent.com/62497891/151546322-d162117b-ded9-4577-ba97-f97a98467538.png)

Files: (sketch), (png), (pdf)

[Cog_Randomize_New_thicker_for_non-Retina_displays.sketch.zip](https://github.com/losnoco/Cog/files/7958572/Cog_Randomize_New_thicker_for_non-Retina_displays.sketch.zip)
[Cog_Randomize_New_thicker_for_non-Retina_displays.png.zip](https://github.com/losnoco/Cog/files/7958573/Cog_Randomize_New_thicker_for_non-Retina_displays.png.zip)
[Cog_Randomize_New_thicker_for_non-Retina_displays.pdf.zip](https://github.com/losnoco/Cog/files/7958571/Cog_Randomize_New_thicker_for_non-Retina_displays.pdf.zip)

- **For Retina displays:**

![Cog_Randomize_New_1](https://user-images.githubusercontent.com/62497891/151547037-88890bd6-f70f-4e84-b645-b0776ccf8f46.png)

Files: (sketch), (png), (pdf)

[Cog_Randomize_New_1.sketch.zip](https://github.com/losnoco/Cog/files/7958615/Cog_Randomize_New_1.sketch.zip)
[Cog_Randomize_New_1.png.zip](https://github.com/losnoco/Cog/files/7958616/Cog_Randomize_New_1.png.zip)
[Cog_Randomize_New_1.pdf.zip](https://github.com/losnoco/Cog/files/7958618/Cog_Randomize_New_1.pdf.zip)

- **Cog_EQ:**

![Cog_EQ](https://user-images.githubusercontent.com/62497891/151550034-f3cd095a-39b8-4249-84b6-6fa400b47e13.png)

Files: (sketch), (png), (pdf)

[Cog_EQ.sketch.zip](https://github.com/losnoco/Cog/files/7958744/Cog_EQ.sketch.zip)
[Cog_EQ.png.zip](https://github.com/losnoco/Cog/files/7958760/Cog_EQ.png.zip)
[Cog_EQ.pdf.zip](https://github.com/losnoco/Cog/files/7958761/Cog_EQ.pdf.zip)

**Comment by Oleg-Chashko** [comment]
Use the new "For non-Retina displays" icon, as the readability is noticeably better.

I think this issue can be closed?

<img width="1083" alt="151426352-33408124-a2fd-4ef9-9cc7-4f82c8129a75" src="https://user-images.githubusercontent.com/62497891/151551728-cdefa576-d9b5-4a47-81e4-1e3ac28e54a8.png">

**Comment by kode54** [comment]
Will grab this now, and will deal with it when I return from my break. Thanks.

**Comment by kode54** [comment]
Please reply, these buttons should be different now.

**Comment by reactorcoremeltdown** [comment]
> Please reply, these buttons should be different now.

Thanks, looks good! I think this can be resolved now.
