### ISSUE TITLE
beachball or crash on  directories with 100+ files

### ISSUE THREAD

**Issue by yannick** [losnoco/Cog#130]
when i open directories with 100+ files the mighty beachball shows up and it takes quite some time. 
this used to work flawless and be fast in earlier versions
if the directory gets to big it even crashes

**Comment by nevack** [comment]
@kode54 Is it related to removing multithreaded loading?

**Comment by kode54** [comment]
Apparently.

**Comment by yannick** [comment]
it got quite a bit faster now. at least at ~500files the speed is now acceptable. 
thank you for maintaining this great software!

**Comment by kode54** [comment]
Yeah, I had an unfortunate bug with my info fetching routine, where it would fail to exclude files with their info already loaded, so on every add, it was doing a full query on the entire playlist. Oops.
