### ISSUE TITLE
Switchable icon style, Big Sur vs just the cog

### ISSUE THREAD

**Issue by kode54** [losnoco/Cog#131]
**Describe**
Looks like this really is a thing, and it's finally hit us:
https://mjtsai.com/blog/2020/11/17/big-sur-application-icons/

**Expected behavior**
User requests switchable icons, to have the not-Big Sur style icon at their preference. Not sure if it matters what's visible when the app isn't running.

**Comment by nevack** [comment]
IMHO, this is minor as hell.

**Comment by kode54** [comment]
And yet someone thought it was important enough to register on my forum and ask for it. I already told them it was Big Sur icon style.
