### ISSUE TITLE
Tweaks on VGM support

### ISSUE THREAD

**Issue by kerunaru** [losnoco/Cog#136]
**Describe**
It would be great if we can set the number of repetitions and a fade out length for tracks which repeats endlessly. It would be great to have support for covers in this file format.

**Expected behavior**
If I play, for example, _Fighting in the street_ by Yuzo Koshiro from _Streets of rage_, I would like to make it repeat twice before fading out during four or five seconds. I also would like to see the screenshot of the title screen from the game (like the one you get when download a file from [Project 2612](https://project2612.org)).

**Comment by kode54** [comment]
I'll consider this for a future update. It means adding an extra set of options to the Synthesizer page.

Needs:

* Default length/fade times
* Loop count for logged formats
* Whether to prefer default length or loop count for logged formats

Some day, it may even get a tag editor so you can permanently tag files with this information. Currently it just reads the tags from these files on every open and applies that to the length. It also doesn't provide a means to reload tags for the playlist's cached metadata or length info.

**Comment by kode54** [comment]
@nevack Feel like helping me make a text control that accepts timestamps? The loop count could simply be a drop list of 1-10 or so, which seems more than reasonable. Preferring length or loop count is something that can be a checkbox. Really, the timestamp field and transformation to/from timestamp to time in milliseconds is really all I need for a proper dialog option.

**Comment by nevack** [comment]
> @nevack Feel like helping me make a text control that accepts timestamps? The loop count could simply be a drop list of 1-10 or so, which seems more than reasonable. Preferring length or loop count is something that can be a checkbox. Really, the timestamp field and transformation to/from timestamp to time in milliseconds is really all I need for a proper dialog option.

I'll look into it this week. I'll contact you later for more info.

**Comment by kode54** [comment]
This has been implemented, hopefully to your satisfaction.
