### ISSUE TITLE
The title of the current track sometimes causes the other elements in the toolbar to shift to the right

### ISSUE THREAD

**Issue by sirburpalot** [losnoco/Cog#137]
See the GIF below.

![ezgif-7-6d2ae0d478af](https://user-images.githubusercontent.com/1429516/111920486-50cdd800-8aa0-11eb-87e8-9d8a952e2224.gif)

**Comment by kode54** [comment]
@nevack I think this bug is because the info icon is not the same width as the album artwork button. We should try to make the icon the same width, or make the button a fixed width to match the album artwork, and the italic i can be centered on that button.

**Comment by kode54** [comment]
This seems to be fixed now? Please retest.
