### ISSUE TITLE
Crash on drag of multiple files with some having .asd extension at the end.

### ISSUE THREAD

**Issue by esaruoho** [losnoco/Cog#138]
Hi, I have a bunch of files. WAV, AIF etc. I also happen to have .aif.asd and .wav.asd files in the same situation.

I'll drag .wav .aif .wav.asd .aif.asd in to Cog, and Cog will promptly crash. every time.

I was kind of expecting Cog to know to not play the .asd files since they aren't music.

Any chance this could be protected against?

**Comment by kode54** [comment]
This should also be fixed by my latest commits and published release, as there was a bug with the "file:///.id=#" type links reaching the File Extractor extension checker through VGMStream, and resulting in a strlen(NULL) call.

**Comment by kode54** [comment]
Please test this.

**Comment by esaruoho** [comment]
Will check tonight

**Comment by esaruoho** [comment]
fixed the issue. closing ticket. thanks!
