### ISSUE TITLE
What does "Save as" actually save and how do I load it?

### ISSUE THREAD

**Issue by esaruoho** [losnoco/Cog#140]
I'm hoping to just save a playlist. I click Save as... and then I don't know what exactly to do after that. 

Dragging it in does nothing.
Opening it does nothing. (not recognized). it's just a filename with no extension. what is it?

**Comment by kode54** [comment]
I have added allowed extensions to the Save as... option, and it will default to .m3u, but allow .pls. This should be fixed with the next release, within 10-20 minutes of this comment.

**Comment by esaruoho** [comment]
i'm now able to save as and it has .m3u by default extension, and dragging .m3u in works. closing ticket. thanks!
