### ISSUE TITLE
Filter is persistent after restart of Cog (no way to get back to old unfiltered list)

### ISSUE THREAD

**Issue by rsternagel** [losnoco/Cog#141]
**First an foremost:**
Thanks a lot for actively continuing this great piece of software! :) 👍 

### Use Case:
* open Cog
* load playlist or couple of songs per drag and drop (e.g. 10 songs)
* filter for something (⌘ F) (now e.g. 2 songs)
* close Cog
* reopen Cog

### Observed behavior:
* there are only 2 songs in your current playlist (no filter is active)!

### Expected behavior:
* old playlist (10 songs) is still there and
a) filter is still active and can be removed to get back to 10 songs _(preferred)_ XOR 
b) filter is removed and I see 10 songs as initially _(good enough)_

**Comment by kode54** [comment]
Oh, crap, I thought I fixed this issue a long time ago. I have fixed it now, possibly once again. It now explicitly removes the filter predicate before saving the playlist on shutdown. Await an update within maybe 10-20 minutes of this post.

**Comment by rsternagel** [comment]
Great, it works again! 👍
