### ISSUE TITLE
Graphical artifacts if you tab away from playlist window and switch window

### ISSUE THREAD

**Issue by NattyNarwhal** [losnoco/Cog#142]
**To Reproduce** (delete if not applicable)
1. Highlight a track in the playlist
2. Press the tab key
3. Switch window, watch the grey rectangle in the highlight rectangle
4. If you switch back, the grey rectangle persists

**Expected behavior**
The grey artifact shouldn't be there.

**Screenshots**
<img width="862" alt="Screen Shot 2021-04-15 at 6 57 56 PM" src="https://user-images.githubusercontent.com/3161292/114943545-84d8b680-9e1c-11eb-8d70-f0407830aa7a.png">
<img width="818" alt="Screen Shot 2021-04-15 at 6 40 33 PM" src="https://user-images.githubusercontent.com/3161292/114943547-8609e380-9e1c-11eb-8230-48717c33bca5.png">

**Version information:***
 - macOS version: 11.2.3, M1
 - Cog version: Version 1484 (1484-gd06eec4f)

**Additional context**
I'm really liking Cog!

**Comment by kode54** [comment]
Fascinating, it only happens in Light mode. And I haven't the foggiest as to what it's doing, other than a possible OS bug.

**Comment by kode54** [comment]
This seems to have been fixed by the rather rocky but now completed transition to a View-based NSTableView, rather than the highly obsolete Cell-based form.

**Comment by NattyNarwhal** [comment]
Indeed, I don't seem to see them anymore.
