### ISSUE TITLE
libfluidsynth.2.dylib was built for newer macOS version (11.0)

### ISSUE THREAD

**Issue by JanX2** [losnoco/Cog#146]
Building with Xcode 12.4 on macOS Catalina produces this warning:
ld: warning: dylib (…/Cog/ThirdParty/FluidSynth/libfluidsynth.2.dylib) was built for newer macOS version (11.0) than being linked (10.13)

The remaining warnings seem to be of the type “Double-quoted include &quot;HEADER FILE&quot; in framework header, expected angle-bracketed instead”.

Thanks for fixing all those warnings BTW!

PS: Working on improving the time display text field behavior in the toolbar…

**Comment by JanX2** [comment]
Awesome @kode54! 

What are we going to do about double-quoted includes? Are they not one of the default warnings in your Xcode version? Not having them would cut down tremendously on noise in the warnings and make development easier in future.

**Comment by kode54** [comment]
We can either disable the warnings, or ask that the third parties whose code we use change all of their frameworks to avoid using double quoted includes of their framework headers. This includes third party code we're using that isn't shipped just as frameworks for macOS.

**Comment by kode54** [comment]
This is irrelevant as we no longer include FluidSynth.
