### ISSUE TITLE
Feature request: Play count; Bug report: Window can't be made smaller

### ISSUE THREAD

**Issue by kode54** [losnoco/Cog#151]
> Thanks for keeping Cog going.  I was using an old version
forever and it's nice to see new updates.  I like Cog because it is simple, small, and streamlined.  Don't make it bloated like so many other players!  The only thing I'd wish for is a play count option on the main player window.  That'd be useful.  

> There is an issue with MacOS 10.13.5 where if I make the Cog player window wider, I can't make it narrower again.  It will keep getting wider if I drag, but even if I quit and re-launch, the window can never be made narrower (it WILL resize height in the expected way).  Even rebooting the computer doesn't help.  Tried versions 1492, 1508, and 1517.  Same issue.  Going backward to 1148 fixed it.

**Comment by montajd** [comment]
Hi @kode54 I also noticed the Cog window being much wider than I remember it being (hadn't updated in a while) so I downloaded 1148 and you are exactly right, the width of the window has changed, and cannot go back to the width of 1148 and below. I really hope they are able to address this as the one thing I liked about Cog was how small you could make the width (reminds me of Winamp which I miss more with each passing day).

Even more interesting, after opening 1148 with v1586 still installed, looks like 1148 was using the same preferences as 1586. So, after adjusting the size of the window in 1148, I opened 1586 and my columns had all adjusted to the same widths as they were in 1148, but there is a huge gap from the right side of the last column on the right to the end of the window. That huge gap was the difference in window width from 1148 (preferred window width) and the existing 1586 window width (which cannot be made smaller).

**Comment by kode54** [comment]
I've added play count support. Bug fixes incoming for that already, mainly with viewing the info in the info panel.
