### ISSUE TITLE
Toolbar small size is actually larger than regular size

### ISSUE THREAD

**Issue by guinzox** [losnoco/Cog#156]
**Describe**
Toolbar. Small size of toolbar is higher (read bigger) than "normal".

**To Reproduce** (delete if not applicable)
1. Go to 'main window'
2. Click on 'toolbar right click '
3. Scroll down to 'use small size'

**Expected behavior**
in small size mode toolbar is higher than usual and add a thin grey line. In the screenshot the small size is on the right

**Screenshots**
<img width="408" alt="Screenshots copy" src="https://user-images.githubusercontent.com/84385456/118883050-7c810900-b8fd-11eb-9c5f-a0a0c0c8a9de.png">

**Version information:***
 - macOS version: 11.3.1 (20E241)
 - Cog version: ... (Version 1534 [1534-g297ba639])

**Additional context**
Add any other context about the issue here.

**Comment by kode54** [comment]
This appears to be a non-issue now, as there is no "small size" any longer.
