### ISSUE TITLE
[Cog 1534-g297ba639] 

### ISSUE THREAD

**Issue by guinzox** [losnoco/Cog#157]
**Describe**
An error with the playback of APE files

**To Reproduce** (delete if not applicable)
1. One APE file with one CUE file
2. Drop the Cue file to the Cog and play continuously 
3. Some tracks will cut off at the end

**Expected behavior**
Again there are an error with the playback of APE files. Some tracks are not played to the end: the time runs out, the file is cut off and the next one begins. This has already happened before, but on November 20, 2020, I received a fixed Version 0.08 (2087) of the Cog from D. P. Now only that D. P.'s version can be used.

**Screenshots**

**Version information:***
 - macOS version: 11.4 (20F71)
 - Cog version: [Cog 1534-g297ba639] 

**Additional context**
Files to test it. You won't have to suffer for a long time this will happen already on the second and third tracks. https://disk.yandex.ru/d/38-B_RDQx9pToA

**Comment by kode54** [comment]
Does this "D. P." share their fixes, per the software license?

**Comment by kode54** [comment]
Found it, yeah, how about I just retire this fork since that one is clearly superior.

**Comment by kode54** [comment]
Okay, I rashly acted, but I still say I want to take a step back. I'll have to see what the hell that other fork has been doing all these years.

**Comment by guinzox** [comment]
Dear Christopher,
take it easy. I feel like I was trespassing on someone else's territory. But I just decided to leave a feedback to make the app better.

1st. Does this "D. P." share their fixes, per the software license?
Go to Vincent Spader site (cogx.org) and look for software license. More recently it was possible to download the Nightly Build which works on macOS 11, now it is not there, unfortunately. I found cog.losno.co this year after News February 5 "Cog is dead!" on Spader site.

2nd. ...I just retire this fork since that one is clearly superior.
Sound is important to me, not the beauty of a code line. This cog sounds almost the same as the old one, which is not bad. And I know the shorter the path is the better for the sound and the less the app weighs is the better for the sound, etc. For example, Cog sounds better than heavy Audirvana. And if you strip the Cog naked and get rid of the external beauty and additional features, then you will get a better sound. Do you hear the difference isn't it?

3rd. ...what the hell...
Well, what can I say? The logo of this Cog is terrible. ⁚一❩ 

Wish you all the best!
