### ISSUE TITLE
"Open URL" command not working even though Cog can open remote URL's from local playlists

### ISSUE THREAD

**Issue by pitermach** [losnoco/Cog#161]
**To Reproduce** (delete if not applicable)
1. Go to File>Open URL or press Command-Shift-O
2. Enter any remote address, it can be pointing to a file or a playlist. A few addresses I was trying with include:
http://radio.tyflopodcast.net:8000/listen.pls
https://weszlo.fm/live
https://piotrs.site/audio/audiomo21/25-SpeaknBreak.flac
https://listen.hkcradio.com/hkc.mp3.m3u
3. If you try to play any of these, absolutely nothing happens.
4. Go back to any of the URL's that are a playlist, and download one of them. For weszlo.fm/live which isn't a playlist, I manually put it inside a .m3u playlist for testing.
5. Open one of these downloaded files in Cog and play the entry, which should start playing.

**Expected behavior**
Playing files through the open URL dialog should work

**Version information:***
 - macOS version: 12 Public Beta but also reproduced on 11.5
 - Cog version: Version 1560 (1560-g0a7be8ab)

**Comment by kode54** [comment]
Not really a bug, unfortunately. The playlist loader doesn't support remote files. The FLAC input also doesn't support streaming.

Consider trying the macOS version of foobar2000 if you need these things. It's not self updating, but it supports multiple playlists, it supports actual tag editing, and it supports many of the obscure formats that my player supports. I tend to keep both players installed for different tasks, and mostly use Cog for the more obscure formats, or for things I know I can control through my own implementation.

**Comment by pitermach** [comment]
Ah, I see. Yeah, I'm playing remote streams through VLC for this reason as well since most radios point to playlists. 
In that case I think it would still be at least helpful if after someone tries playing such a link, some sort of error would pop up explaining why nothing happened.

**Comment by kode54** [comment]
Okay, all of these work now. Among the reasons for the FLAC input not supporting streaming included OggFLAC support not being enabled.
