### ISSUE TITLE
Cog is crashing on stale playlist 

### ISSUE THREAD

**Issue by reagle** [losnoco/Cog#170]
Just now, when I open cog and click on a song in the extant playlist, it crashes -- and asks if I want to send a report to Apple. I haven't changed the location of the files, but I've had those songs in the playlist for a while, across a reboot. Removing the songs and adding them works fine. So I suspect there's something odd about the playlist being old or "stale"...

- macOS 11.5.2 20G95 arm64
- cog: 1570,3f6cb1bc

**Comment by reagle** [comment]
I opened this so I can add things as they occur. Having the problem again. Crash report is attached.

[cog-crash.txt](https://github.com/losnoco/Cog/files/7188591/cog-crash.txt)

**Comment by kode54** [comment]
Please test this again. I will supply a debug build for logging output from Console.app, filtered to "Cog", which will contain more verbose information than release builds produce.
