### ISSUE TITLE
ReplayGain not working at all

### ISSUE THREAD

**Issue by AryaTwirl** [losnoco/Cog#172]
ReplayGain not working, neither Album Gain nor Track Gain

Steps to reproduce the behaviour:
1. Go to 'Preferences' > 'Output'
2. Click on 'Volume Level'
3. Select 'ReplayGain' (any kinds)
4. Play some songs
5. Notice the volume behaviour doesn't change at all

Expected Behaviour:
Volume will be normalised per ReplayGain tags. But it's not. 

Version Information:
 - macOS version: 11.5.2
 - Cog version: Version 1586 (1586-g42a6738e)

Additional context:
I'm also using Sound Control app (the one with octopus icon). Perhaps it's causing the issues? Thank you.

**Comment by kode54** [comment]
Please state your file format. ReplayGain tags are only supported for the following formats:

* Anything with ID3v2 tags with TXXX literals containing ReplayGain tags
* Ogg Vorbis and Opus files with Xiph comments containing RG tags
* Anything with APEv2 tags with textual RG tags

No, MP4 isn't supported. No, I have no idea how to implement that in TagLib. Yes, patches are welcome.

**Comment by AryaTwirl** [comment]
Ah, if that's the case, then I will close this issue. it is MP4 and it is not supported (M4a to be more specific).

Thank you very much for your explanation.

**Comment by kode54** [comment]
I want to eventually support it, though. It will also need support for SoundCheck reading.
