### ISSUE TITLE
too frequent updates

### ISSUE THREAD

**Issue by yannick** [losnoco/Cog#173]
Hi!
Even though i unchecked ```Automatically check for updates on startup``` i get the update screen almost every day. 
in general it would be cool to have an update channel that just once a months updates and makes it easy to follow the new features.
best
y

**Comment by kode54** [comment]
Sorry, I can't maintain multiple update channels. I can't even guarantee the main update channel even gets an update at least once a month, much less roll up all updates from a specific time period into a specific channel.

There hasn't been an update for a whole week. Is updating weekly too often for you?

**Comment by yannick** [comment]
for me it feels like every time i (re)start cog it has an update. but maybe that just happens so infrequently.
ill just disable the update checkbox and re enable it once a while. sorry
