### ISSUE TITLE
Feature request: Custom Field - Rating

### ISSUE THREAD

**Issue by zDEFz** [losnoco/Cog#174]
**Describe**
Just want the functionality so that I can sort my music to be filterable by the "Rating" tag, I gave them.
Thats all.
A clear and concise description of what the issue is.

**Version information:***
 - macOS version: 11.6
 - Cog version: Version 1611 (1611-g1fd160dc)

**Comment by zDEFz** [comment]
Additional meta fields also lining up with #151

**Comment by kode54** [comment]
It has been suggested to me that adding tag writing or modifying ability to the player would just end up bloating it even more than it already is. I'm not so sure I want to do this any more.

**Comment by zDEFz** [comment]
> It has been suggested to me that adding tag writing or modifying ability to the player would just end up bloating it even more than it already is. I'm not so sure I want to do this any more.

Well. Usually I just disable other columns just for that feature. But I have kind of stopped rating my Songs.
But I have not found a solution on how to find the songs I liked the most. Playlists don't seem to work when some files are moved. Rating does always work, but changes Metadata - and changes the file itself usually.

**Comment by kode54** [comment]
I'll look into this, if I can figure out a way to render rating stars appropriately. I'll probably use Unicode star characters, and hollow stars for the unfilled ratings. And somehow make them clickable.

And I'd store them in a database similar to the play counts database I currently employ.

**Comment by kode54** [comment]
Rating support is in. No, it doesn't use or write file tags.
