### ISSUE TITLE
Cog is crashing after adding many new files/moving them in watched folder

### ISSUE THREAD

**Issue by danieltomasz** [losnoco/Cog#176]
**Describe**
I have cog watching download folder
When I add some new albums to folder, or I move them when cog is watching, cog is crashing when I add files to playlist or set playlist and want  to play files
It crashes a few times when I try to restart it, then it starts working again
Are there any log I could share?

I am on Big Sur 11.6 with Intel processer 
Cog Version 1608 (1608-gee6faec7)

**Comment by kode54** [comment]
Please try this again. If you reproduce it, please let me know, I will supply you with a debug build, and you can capture log output from Console.app filtered to "Cog" and determine which file is causing it to crash.

One reason it may be crashing is that it starts probing files for metadata the moment they come into existence, even if they're incomplete files. Technically, none of my inputs should outright crash on incomplete files, though.

**Comment by danieltomasz** [comment]
Yes, the indexed files contained a folder in which files were still downloaded or  are indeed partially downloaded  (using Soulseek for example)

In meantime, I switched to M1 MacBook and cannot reproduce, also Cog was updated many times
(Thanks for the hard work!) I may  close the issue for now, when it will happens again I  may reopen the issue
