### ISSUE TITLE
Fade In/Out only works once

### ISSUE THREAD

**Issue by alsilat** [losnoco/Cog#179]
Pressing Shift-Command-P or selecting the Fade In/Out function in Control only works once. After having faded in and then out on a playing track once, the function no longer works (Command-P still does, so just the fade function is affected.) So I would have to quit and reopen Cog to use it again (once.)

macOS version: 12.1 Beta (21C5031d)
Cog version: Version 1617 (1617-gbce21b44)

**Comment by kode54** [comment]
I can't reproduce this.

**Comment by alsilat** [comment]
Thank you for taking care of this. Perhaps I am the only one on whose system this occurs. I can reliably reproduce it with various audio devices here. Perhaps it is a Monterey (Beta) problem. If there is anything I can do in this case, please let me know.

**Comment by kode54** [comment]
Please outline your exact steps. If any of your files are short. Whatever it takes. I cannot reproduce it with a 5 minute file on the Monterey beta.

The fade steps don't work unless you're already playing a file. Fading out pauses afterward. Fading in unpauses. The fade in/out key/menu action is disabled for the duration of the 1 second fade.

I tested at multiple volume levels as well.

**Comment by alsilat** [comment]
I have a playlist of FLAC audio files of any size (I only play FLAC format) and press Play on any track. Then, I press Shift-Command-P to fade out and pause the playback. This works. After some time (not immediately) I press Shift-Command-P again, the playback fades in. This also works. After some time (again, not immediately, but possibly on the same track), I again press Shift-Command-P. Nothing happens.

**Comment by kode54** [comment]
Again, I can't reproduce this issue. I can fade out and back in at random times. Are you sure the application has keyboard focus when you're using the shortcut? It is also possible that your sound device has stopped responding to volume adjustments, since it uses the output method volume control, rather than scaling the volume itself in software.

**Comment by alsilat** [comment]
Thank you very much for your efforts. I have tried different audio devices (internal/external) and different volumes with the same result. It has nothing to do with keyboard focus, as I always see the View menu highlighted when I press Shift-Command-P. Likewise, it doesn’t work when I use the mouse and select the function from the menu. If the function ever works again on my system, I will let you know. I can live without fading for now.

**Comment by alsilat** [comment]
With the latest fix in 1623-g91bd653b you did it. The fade in and fade out works on my system without any restrictions! Thanks a lot!

**Comment by kode54** [comment]
The fade-out already had a rounding error handler, but apparently fade-in needed one too, otherwise the timer just perpetually ran forever and never completed. Glad I could get that fixed.
