### ISSUE TITLE
playlist streams.

### ISSUE THREAD

**Issue by Mturner88** [losnoco/Cog#18]
It seems to take a long time, when loading a .m3u playlist of web streams.

**Comment by kode54** [comment]
That is because the http reader treats every link as a static file, and must probe them all for metadata and format info on load. I haven’t a clue how to properly fix this without breaking actual static files.

**Comment by megadr01d** [comment]
Just a heads up, loading playlists may be quicker now with this fix: https://github.com/kode54/Cog/issues/33.

**Comment by kode54** [comment]
Please try this again.
