### ISSUE TITLE
Increase/Decrease Font Size

### ISSUE THREAD

**Issue by GScottElshaw** [losnoco/Cog#183]
I am really impressed with Cog's implementation of increasing and decreasing font sizes across both windows. After trying to get another project to include the code for this (Hi @nevack), and getting nowhere, I wondered if it was possible to repurpose and build it myself?

Cheers,
Gary

**Comment by kode54** [comment]
It's quite simple. Check out the configuration value `fontSize`. And the transformer, `FontSizeToLineHeightTransformer`, which is applied to that value to control the PlaylistView (NSTableView) 's Row Height property.

Sorry I took so long to get back to you on this.

**Comment by GScottElshaw** [comment]
Thanks for getting back to me, i'll see what I can figure out! Thanks for all of your work on Cog, it really is impressive!

**Comment by GScottElshaw** [comment]
I don't suppose I could persuade you to contribute this function as a PR to [Transmission](https://github.com/transmission/transmission), @kode54?

**Comment by kode54** [comment]
I suppose I could do that, when I get around to it. Maybe tomorrow.

**Comment by GScottElshaw** [comment]
> I suppose I could do that, when I get around to it. Maybe tomorrow.

Really? Thank you from my eyeballs for the current squint I have looking at the main menu on my MacBook Air.

**Comment by kode54** [comment]
I'm not sure if this affects menus or not. Also, I can only apply such a thing toward a native Cocoa client. This would have nothing to do with the GTK interface.

**Comment by GScottElshaw** [comment]
I think other Mac users with diminutive screens will be grateful nonetheless!

**Comment by GScottElshaw** [comment]
I don't know, but worth mentioning if it is easier for you, the inspector window is fine, it is the main window that needs attention. Poking around? I think it's here https://github.com/transmission/transmission/blob/main/macosx/InfoFileView.xib

**Comment by GScottElshaw** [comment]
I made a start on what _i think_ the pbxproj file should look like. https://github.com/GScottElshaw/transmission-fonts/tree/main/Transmission.xcodeproj

**Comment by GScottElshaw** [comment]
Just in case you're bored on your break....
