### ISSUE TITLE
Crash and Digital noise: v.1644-g2445cc94

### ISSUE THREAD

**Issue by Oleg-Chashko** [losnoco/Cog#186]
**Version information:**
 Cog v.1644-g2445cc94

**Crash logs:**
[Crash logs.zip](https://github.com/losnoco/Cog/files/7774177/Crash.logs.zip)

- After deleting the song, the player no longer runs, a constant crash.
<img width="1028" alt="147102221-c1932499-ff7b-4e02-807c-e5105a480e28" src="https://user-images.githubusercontent.com/62497891/147350684-7ba99397-4114-4611-ad4e-295a1ce6eb0c.png">

**Screenshots**

https://user-images.githubusercontent.com/62497891/147349558-aa5e3726-3410-46d0-bbdd-1a41d0d9566a.mp4

- To start the application after the crash, it is necessary to delete (Default.sqlite).

**Comment by Oleg-Chashko** [comment]
- Digital noise:

https://user-images.githubusercontent.com/62497891/147351737-83d21d4f-09e0-4ff9-8539-e00761356271.mp4

**Comment by Oleg-Chashko** [comment]
Crash: Version 1645 (1645-ga8a982d3)

**Comment by kode54** [comment]
1648 should fix this.

**Comment by Oleg-Chashko** [comment]
But digital noise is present! Closed so as not to duplicate.
I closed the topic, there is no Crash with. Thank you!
