### ISSUE TITLE
Improving UI

### ISSUE THREAD

**Issue by Oleg-Chashko** [losnoco/Cog#187]
**+++Fixed+++**
- (1) Align. 

<img width="530" alt="Screen Shot 2021-12-25 at 12 06 27" src="https://user-images.githubusercontent.com/62497891/147383984-e76199e0-ffb9-4116-992e-f4ffd87677ba.png">

---
**---(Apple SDK) (wont fix)---**
- (2) The Toolbar border is not visible on a dark theme.

<img width="1000" alt="Screen Shot 2021-12-25 at 12 08 08" src="https://user-images.githubusercontent.com/62497891/147384058-4b4f9cca-a469-4d7b-81ab-035bd53d0eea.png">

<img width="1000" alt="Screen Toolbar" src="https://user-images.githubusercontent.com/62497891/147384061-363d2030-1c73-46d2-8ee5-40a325015c55.png">

---
 **+++Fixed+++**
- (3) The second copy of (Not Playing).

<img width="280" alt="Screen Shot 2021-12-25 at 12 41 48" src="https://user-images.githubusercontent.com/62497891/147384246-d612eae5-8db7-4368-8a7f-b19ef49a0d34.png">

---
**---(Apple SDK) (wont fix)---**
- (4) Align along the axis of symmetry.

<img width="846" alt="Screen Shot 2021-12-25 at 12 50 34" src="https://user-images.githubusercontent.com/62497891/147384489-df78a6e4-ccca-44ae-8886-d7fb09b0fc10.png">

<img width="1024" alt="Screen Shot 2021-12-25 at 12 59 22" src="https://user-images.githubusercontent.com/62497891/147384491-cdad90f6-19bd-45bd-a120-d0c9c2ed6917.png">

---

- (5) Align.

<img width="240" alt="Screen Shot 2021-12-25 at 13 07 39" src="https://user-images.githubusercontent.com/62497891/147384677-fe3d9b73-2869-402b-af74-5e148a9a59b7.png">

---
 **+++Fixed+++**
- (6) Possibility to select the "Randomize" button in the "Mini mode".

Mini mode:

<img width="836" alt="Mini mode - Randomize" src="https://user-images.githubusercontent.com/62497891/147384851-ae12b6b6-3bee-4e4c-b4d5-7a87401c72b5.png">

Full mode:

<img width="1139" alt="Full mode - Randomize OK" src="https://user-images.githubusercontent.com/62497891/147384858-56e64a10-7577-48ef-98d3-e1f6ffe709c8.png">

---
 **+++Fixed+++**
- (7) If the player window is at the edge of the display, there are problems with the display of the percentage arrow.  

<img width="251" alt="Screen Shot 2021-12-25 at 13 52 19" src="https://user-images.githubusercontent.com/62497891/147385515-7bb9e795-6ebf-4934-bcf0-12e4fa01cd1d.png">

---
**---(Apple SDK) (wont fix)---**
- (8) Align along the axis of symmetry (Add URL).

![Add URL](https://user-images.githubusercontent.com/62497891/147391963-c52c3f51-34ca-49b8-95f2-f00ea1dbd7cc.jpg)

---
 **+++Fixed+++**
- (9) It looks like you put a dash instead of a minus.
<img width="395" alt="Screen Shot 2021-12-25 at 20 24 47" src="https://user-images.githubusercontent.com/62497891/147392437-8e10ae98-c4d7-4c3a-8677-a95d043f77f2.png">

**Comment by nevack** [comment]
Thanks for the comprehensive report!
I think I can fix some of the issues listed.

Some points:
1. Current Time view has a lot of issues and should be completely overhauled, I have put dash instead of minus to make it less shaky changing from time played to time left and vice versa.
2. Volume slider can be fixed by making it horizontal, NSPopover works badly for narrow views.

**Comment by Oleg-Chashko** [comment]
_Thanks for the comprehensive report!_
I am glad to help.

1.  _Current Time view has a lot of issues and should be completely overhauled._ Ok. 
 _I have put dash instead of minus to make it less shaky changing from time played to time left and vice versa._
You can temporarily insert a small space between (-) and (00:00), to improve readability?
Example:
![147392871-9926e34a-a350-40e9-aeb2-2d384a31d57c](https://user-images.githubusercontent.com/62497891/147398364-af4d2f4b-2793-48af-87ca-8e51c48a7b6e.png)

---

2. _Volume slider can be fixed by making it horizontal, NSPopover works badly for narrow views._

 How about making it like Quicktime: without the arrows and percentages? 
For example, I set the volume level by ear, not by percentages.
And I think a lot of people do that.
Example:
![ScreenFlow](https://user-images.githubusercontent.com/62497891/147398124-255dd0cf-9bfc-43ea-b7b7-299ce7806449.gif)

---

3. I would like to add that the arrows somehow, not very nice.
Example:
<img width="223" alt="Screen Shot 2021-12-26 at 04 19 45" src="https://user-images.githubusercontent.com/62497891/147398219-8817f7de-ac2c-4431-9b91-8ac9b1e43817.png">

**Comment by kddlb** [comment]
Pull requests are welcome.

**Comment by nevack** [comment]
> I would like to add that the arrows somehow, not very nice.
yes, this is NSPopover's artifacts for narrow views.

**Comment by nevack** [comment]
@kddlb I think I want to keep this open until resolved

**Comment by Oleg-Chashko** [comment]
<img width="530" alt="Screen Shot 2022-01-14 at 21 52 53" src="https://user-images.githubusercontent.com/62497891/149584634-1707dea8-c6ff-4702-9ac3-82cf5aafc27c.png">

**Comment by kode54** [comment]
I literally have no idea how you're measuring this, the editor doesn't show me how big the gap is between the controls.

**Comment by Oleg-Chashko** [comment]
I don't measure with any tools, I see it with my own eyes. Sometimes even at 1 pixel I see inaccuracy.

**Comment by kode54** [comment]
I'm leaving it to @nevack to deal with this, since I obviously can't competently design a UI.

**Comment by Oleg-Chashko** [comment]
> I'm leaving it to @nevack to deal with this, since I obviously can't competently design a UI.

After you've dealt with the sound problem perfectly, I don't doubt you can also improve the user interface.

**Comment by kode54** [comment]
I have attempted to deal with most of these.

1. I re-positioned most of the preferences pane controls according to sensible alignments, and aligned labels to drop lists by the ruler within the editor.
2. I've implemented code to hide the current artist menu item from the dock context menu, either when no track is currently playing, or when the current track has no appreciable artist field assigned.
3. I added a randomize button to the mini window's toolbar palette.
4. I changed the volume slider's tooltip so that it edge guards the current screen when it is being positioned, such that it will pop out to the left of the slider if it's too close to the right edge of the screen.
5. I changed the time display field to use a Unicode minus sign instead of a Unicode hyphen. They both appear to be the same width in the configured fixed width font which is being used on macOS 10.15 and up.

A new build will be uploaded shortly.

**Comment by Oleg-Chashko** [comment]
You handled most of the problems very well! I marked them as fixed (**+++Fixed+++**).
There are still some problems left: (4), (5), (8).

**Comment by kode54** [comment]
2. This appears to be a limitation of the OS. I do not use custom colors or controls for this.
4. I have no control over this unless I change the control to use a fixed size and adjust its size until the alignment is perfect.
5. I'll fix this the next time I work on the player.
8. I have no control over this, either. I just use standard controls for things like this, and alignment of text is down to the control.

**Comment by Oleg-Chashko** [comment]
Noted that at this time it is not possible to fix: (2), (4), (8) **---(Apple SDK) (wont fix)---**
After you have had a time to fix (5) please close the issue.
Thank you.

**Comment by kode54** [comment]
I have fixed (5).

**Comment by Oleg-Chashko** [comment]
Fixed. Closed the issue.
Thank you.
