### ISSUE TITLE
Not Responding and Crash: 1646 (1646-gd4614a2f)

### ISSUE THREAD

**Issue by Oleg-Chashko** [losnoco/Cog#188]
**Crash log:**
[Crash log.zip](https://github.com/losnoco/Cog/files/7775882/Crash.log.zip)

**Screenshots**

https://user-images.githubusercontent.com/62497891/147386180-70ac65e5-a195-4e83-9b55-148dd9730cac.mp4

**Version information:**
 - macOS version: 12.1 (21C52)
 - Cog version: 1646 (1646-gd4614a2f)

**Comment by kode54** [comment]
Sorry, I didn't test that my new playlist loader crashed when the database is empty. 1648 should fix this, when it's up.

**Comment by Oleg-Chashko** [comment]
I closed the topic, there is no Crash with. Thank you!
