### ISSUE TITLE
The player is trying to play a file that has already been deleted from the system

### ISSUE THREAD

**Issue by Oleg-Chashko** [losnoco/Cog#189]
The player is trying to play a file that has already been deleted from the system.

**Screenshots**

https://user-images.githubusercontent.com/62497891/147398950-6ed3050c-0f4a-4fed-a60f-1afae7df847e.mp4

**Version information:**
 - macOS version: 12.1 (21C52)
 - Cog version: 1649 (1649-gc6b112f5)

**Comment by kode54** [comment]
This is the player behaving as intended when it cannot play a file. It will play 10 seconds of silence instead.
