### ISSUE TITLE
VGMStream randomly crashes when processing a lot of files at once for tags, but only on Intel

### ISSUE THREAD

**Issue by kode54** [losnoco/Cog#191]
**Describe**
The VGMStream decoder plugin, when fed 8 or more .txtp files at once for tag and properties reading, such as when adding them to the player for the first time, or when reloading their info manually, causes the player to crash. The crash only occurs on Intel machines, not even Apple Silicon machines running the hardened app under Rosetta. It does not happen under debug builds, or under the debugger. The crash will occur under the following call path:

init_vgmstream_from_cogfile -> init_vgmstream_from_STREAMFILE -> init_vgmstream_txtp -> init_vgmstream_from_STREAMFILE -> init_vgmstream_mus_acm -> check_extensions

**To Reproduce** (delete if not applicable)
1. Launch Cog on an Intel machine
2. Add a bunch of valid VGMStream .txtp files to the playlist at once
3. If it hasn't crashed by now, force an info reload for all of them

**Expected behavior**
The inputs should reload the file properties without error, regardless of how many files are being reloaded at once.

**Version information:***
 - macOS version: 11.6.2
 - Cog version: 1700

**Additional context**
Strangely, this is very hard to debug. Something must be clobbering the stack somewhere.

**Comment by kode54** [comment]
Maybe this is because I was calling the playlistLoader loadInfoForEntries directly from the UI thread.

**Comment by kode54** [comment]
Nope, it still crashes. And only on Intel. I'm thinking of dropping Intel support sooner than later.

**Comment by kode54** [comment]
Hmm, this could be a Clang bug in the Intel optimizer, but it's been around since at least Xcode 11 or 12 or so. I'll try reducing the Intel optimization level to -O1 or so and see if that fixes it.

**Comment by nevack** [comment]
> I'll try reducing the Intel optimization level to -O1 or so and see if that fixes it.

You mean only for the problematic target? Or the whole project?

**Comment by kode54** [comment]
Only for the problematic target, which is libvgmstream. The major problem it has, as far as I can tell, is that it's massively inlining and unrolling the giant init loop that calls over 100 different format init functions until one of them succeeds. The loop is designed to call them from a function list table one by one. Apparently it thinks it's perfectly okay to just unroll a bunch of them, so that like 3-4 passes through the breakpoint-able calling function hit the crashing function, which is #73 (starting at 0) in the list. It also makes it impossible to trace what is clobbering the registers that contain the object pointers that are crashing.

**Comment by kode54** [comment]
Okay, that seems to have fixed it. Pushing the commit.

**Comment by kode54** [comment]
Closing this issue, because changing compile flags should have fixed it. Over inlining broke the ability of the VGMStream input to be called recursively, since several of its inputs are playlists that reference other files that it supports.
