### ISSUE TITLE
Cog repeated crash - versions 1684-g112a2013 up to the current version 1718-gc8301a98

### ISSUE THREAD

**Issue by joostjodel** [losnoco/Cog#192]
**Describe**
Cog (1718-gc8301a98) repeatedly yet somewhat unpredictably crashes a second or two after pressing play.
Filetypes include flacs and mp3s at various sample- and bit rates.

From version 1710-g6c910bdf it is with a "Exception Type:        EXC_CRASH (SIGABRT)"
Crashes started to happen with version 1684-g112a2013, but then it was a "Exception Type:        EXC_BAD_ACCESS (SIGBUS)"

Is it related to bug #191?

**To Reproduce** (delete if not applicable)

I initially got the intuition that might have something to do with sample rate conversions. The files that I tried to play were quite diverse (44,1 / 48 / 88,2). I had been messing around a bit, manually setting sampling rates and output devices in Mac's "Audio MIDI Setup.app" , because I had worked with audio software+external soundcard. 

The older versions of Cog gave these more verbose messages suggestive of some conversion error:

Thread 15 Crashed:
0   com.apple.audio.toolbox.AudioToolbox	0x00007fff2bc5c67c Resampler2::ConvertSIMD_AVX_SmallIntegerRatio(float*, float*, unsigned int, unsigned int) + 1468
1   com.apple.audio.toolbox.AudioToolbox	0x00007fff2bc5b8c7 Resampler2::PushConvert(float const*, float const*, float*, float*, unsigned int&, unsigned int&, unsigned int, unsigned int, unsigned int) + 1111
2   com.apple.audio.toolbox.AudioToolbox	0x00007fff2bc59bd5 Resampler2Wrapper::RenderOutput(CABufferList*, unsigned int, unsigned int&) + 643
3   com.apple.audio.toolbox.AudioToolbox	0x00007fff2bc59943 SampleRateConverter::RenderOutput(CABufferList*, unsigned int, unsigned int&, AudioStreamPacketDescription*) + 39
4   com.apple.audio.toolbox.AudioToolbox	0x00007fff2bc58da3 BufferedAudioConverter::FillBuffer(unsigned int&, AudioBufferList&, AudioStreamPacketDescription*) + 355
5   com.apple.audio.toolbox.AudioToolbox	0x00007fff2bc58ff6 AudioConverterChain::RenderOutput(CABufferList*, unsigned int, unsigned int&, AudioStreamPacketDescription*) + 106
6   com.apple.audio.toolbox.AudioToolbox	0x00007fff2bc58da3 BufferedAudioConverter::FillBuffer(unsigned int&, AudioBufferList&, AudioStreamPacketDescription*) + 355
7   com.apple.audio.toolbox.AudioToolbox	0x00007fff2bc58a59 AudioConverterFillComplexBuffer + 984
8   org.cogx.cogaudio             	0x0000000106e6d2c8 -[ConverterNode convert:amount:] + 1140
9   org.cogx.cogaudio             	0x0000000106e6ce0e -[ConverterNode process] + 116
10  org.cogx.cogaudio             	0x0000000106e64a2c -[Node threadEntry:] + 49
11  com.apple.Foundation          	0x00007fff2f5c29a2 __NSThread__start__ + 1194
12  libsystem_pthread.dylib       	0x00007fff596462eb _pthread_body + 126
13  libsystem_pthread.dylib       	0x00007fff59649249 _pthread_start + 66
14  libsystem_pthread.dylib       	0x00007fff5964540d thread_start + 13
 
Never versions of Cog still keep crashing sometimes, even while I have rebooted and set the sampling rate in Audio MIDI Setup.app to a pretty standard 44,1/24bit, and the output device in Cog's preferences to "Built-in output". 
For instance, Cog crashed again trying to play a 96KhZ/24bit file, in the same playlist as a bunch of 44,1/16 files. But now the error messages seem less verbose:

Thread 8 Crashed:
0   libsystem_kernel.dylib        	0x00007fff5d1072c2 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff5d1c2bf1 pthread_kill + 284
2   libsystem_c.dylib             	0x00007fff5d071745 __abort + 144
3   libsystem_c.dylib             	0x00007fff5d071ff3 __stack_chk_fail + 205
4   org.cogx.cogaudio             	0x00000001092a6e54 -[ConverterNode process] + 186
5   ???                           	0xbea4a07bbec5fd6a 0 + 13737281216728923498

**Expected behavior**

Previously, Cog never crashed on playing a variety of file types in a range of sample and bitrates.

**Version information:***
 - macOS version:  Mac OS X 10.14.6 (18G9323) (on an Intel mac)
 - Cog version: versions 1684-g112a2013 up to the current version 1718-gc8301a98

See zipped mac crashlogs attached.

[Cog_crashlogs.zip](https://github.com/losnoco/Cog/files/7841394/Cog_crashlogs.zip)

**Comment by kode54** [comment]
This should be fixed now, by completely gutting out the AudioToolbox resampler and conversion crap, and replacing it with my own code, except for the resampler, which I lifted from RetroArch. My version is not compatible with theirs, of course, because it adds support for variable channel counts, and a function to return the current tap count divided by two, as a latency count on input data.

This latency count is needed to determine how much silence to pad input on start, and how much output to discard after start, and how much input to pad on shutdown after the file ends.

**Comment by joostjodel** [comment]
Thanks Christopher for your response.

Cog no longer seems to crash. Unfortunately, a strange new issue seems to occur in the latest version (1735-g84d445cf) with playback going all berserk under conditions specified below. I can consistently reproduce as follows:

1. Upon start, Cog plays any song in a remembered and reloaded playlist just fine.
2. However, when I manually skip to a song, either by pressing the "next" button (>>) or manually clicking on another song, playback becomes all distorted (as if the speed seems to double/triple/quadruple).
3. When I exit Cog, and restart, it plays fine again, until again manually skipping to a new song in a playlist. 
4. When the distortion has once begun to occur, it cannot be reversed. Only restarting Cog will make it disappear again, until I again manually skip to another song.... Also, the two exceptions below do no longer apply.

_exceptions_
- Auto-forward to a next song in a playlist works without issues.
- Forwarding in a song by moving the slider works without hiccups.

**Settings:**
OS: 44,1/24bit in MacOS Audio MIDI Setup, under Intel 10.14.6
Cog: output device "system default device" / no volume scaling / resampling quality [a new feature in Cog Settings?]: normal, higher, doesn't matter.

**Comment by joostjodel** [comment]
It is, cheers!
