### ISSUE TITLE
Audio track is garbled and with static on 2nd+ playback

### ISSUE THREAD

**Issue by g4r37h** [losnoco/Cog#193]
**Describe**
Audio tracks play garbled and too fast on the 2nd playback.

**To Reproduce** (delete if not applicable)
1. Put some tracks in the playlist
2. Double-click on a track to play it
3. Double-click on another track (or the same one) to play it before the first one has finished
4. Notice the audio is borked, playing too fast and with lots of static noise
5. Closing the application and re-launching it allows for successful playback of an audio track, but following the above process results in the issue reoccurring.

**Expected behavior**
Audio tracks should play fine no matter whether it's the 1st, 2nd or 100th track.

**Version information:***
 - macOS version: 12.1
 - Cog version: Version 1735 (1735-g84d445cf)

**Additional context**
After some testing, I've estasblished that the issue was introduced specifically in version 1735-g84d445cf. The previous version, 1727-g91c3feac, works as expected.

**Comment by kode54** [comment]
This should be fixed by 1740.

**Comment by g4r37h** [comment]
Tried 1748 just now and the issue is no longer present. Thanks.  :)
