### ISSUE TITLE
Request: add equalizer

### ISSUE THREAD

**Issue by Oleg-Chashko** [losnoco/Cog#194]
Is it possible to add an equalizer in the future. For example, as in Apple Music.

<img width="440" alt="Screen Shot 2022-01-15 at 16 51 48" src="https://user-images.githubusercontent.com/62497891/149628527-d24b2aac-dde2-4bf2-ae11-80f80846bdfc.png">

**Comment by kode54** [comment]
I have implemented an equalizer, using the AudioUnit GraphicEQ. Look for it in an upcoming release.

**Comment by Oleg-Chashko** [comment]
Thank you.

**Comment by Oleg-Chashko** [comment]
Please add:
1. Equalizer call button and shortcut key.
2. Selection of presets and manual.
3. Check box with the ability to turn off the equalizer.
4. Check box with option to limit volume to 100% (Sometimes more than 100% volume causes **clipping**).


![1511590116_swinsian_02](https://user-images.githubusercontent.com/62497891/149670552-0ce1a897-4a39-4da7-93eb-12ee23de3993.jpeg)

**Comment by Oleg-Chashko** [comment]
You can add an automatic mode: 
Depending on the genre of the track, select a preset corresponding to this genre (genre: Metal = preset: Rock).

**Comment by kode54** [comment]
I can't alter the dialog without completely reimplementing it myself. I'm currently just using the system GraphicEQ AudioUnit and instantiating its own control dialog.

**Comment by kode54** [comment]
Actually, I can add controls to a a dialog, but then I need to make a split view like the main playlist window, so I can insert the AU control as a view. The editor is implemented as an NSView.

**Comment by kode54** [comment]
Also, what version of macOS are you running? The controls look different here:

<img width="705" alt="Screen Shot 2022-01-16 at 2 33 53 PM" src="https://user-images.githubusercontent.com/796316/149680837-e10c5098-71f4-490d-9423-fb868f6337d2.png">

**Comment by kode54** [comment]
If you can tell me how to change the config dialog and GraphicEQ instance to use the design you suggested, then I will implement it more easily.

**Comment by Oleg-Chashko** [comment]
> Also, what version of macOS are you running? The controls look different here:
> 
> <img alt="Screen Shot 2022-01-16 at 2 33 53 PM" width="705" src="https://user-images.githubusercontent.com/796316/149680837-e10c5098-71f4-490d-9423-fb868f6337d2.png">

I used a screenshot of the Swinsian player.

**Comment by Oleg-Chashko** [comment]
> If you can tell me how to change the config dialog and GraphicEQ instance to use the design you suggested, then I will implement it more easily.

Try using the reverse engineering of the Swinsian player. 
[Swinsian - Contents.zip](https://github.com/losnoco/Cog/files/7882110/Swinsian.-.Contents.zip)

**Comment by kode54** [comment]
Reverse engineering proprietary players is not only beyond my capability, but beyond what's allowed for open source software.

**Comment by Oleg-Chashko** [comment]
The "Flat" preset duplicates the "Flatten EQ" button.

<img width="705" alt="Screen Shot 2022-01-18 at 05 14 45" src="https://user-images.githubusercontent.com/62497891/149870317-5892b9a5-76fb-44a8-8008-f17402ab0131.png">

**Comment by kode54** [comment]
I can't remove either one. The button is part of a control dialog I don't control, and the preset Flat is needed for genre tracking, as a default.

**Comment by kode54** [comment]
There, I just removed the "Flatten EQ" button. I can't move the other one over into its place, though, as the view is using some sort of auto layout system, so it repositions itself automatically.

**Comment by Oleg-Chashko** [comment]
> There, I just removed the "Flatten EQ" button. I can't move the other one over into its place, though, as the view is using some sort of auto layout system, so it repositions itself automatically.

If you can put it back ("Flatten EQ" button), it will be more beautiful.

**Comment by Oleg-Chashko** [comment]
Please remove this if possible.

<img width="705" alt="Screen Shot 2022-01-18 at 12 52 58" src="https://user-images.githubusercontent.com/62497891/149934239-c9ac5a70-7118-45fc-af8c-3da88990bc18.png">

**Comment by Oleg-Chashko** [comment]
What do you think of item: 4?
4. Check box with option to limit volume to 100% (Sometimes more than 100% volume causes clipping). Or add a preamp control.

**Comment by Oleg-Chashko** [comment]
Bug:
If you play a list of tracks with different styles of music, the EQ does not always switch the correct EQ setting. This problem does not occur when switching tracks manually.

**Comment by Oleg-Chashko** [comment]
Some characteristics of the equalizer look a little strange. Added a table of equalizer settings.
Add styles and fix.
Thank you.
[EQ.docx](https://github.com/losnoco/Cog/files/7890235/EQ.docx)

**Comment by Oleg-Chashko** [comment]
I have a feeling that the presets are from the 80-95s, because the equalization level is very high. At that time there were no quality playback sources and you had to compensate the sound a lot.

**Comment by kode54** [comment]
How do I change the range without completely remaking the dialog from scratch?

**Comment by Oleg-Chashko** [comment]
> How do I change the range without completely remaking the dialog from scratch?

If, it's complicated, you don't have to redo it. I'm just asking.

**Comment by Oleg-Chashko** [comment]
I don't quite understand why you took Winamp's settings. 
If they don't match your EQ on the frequency grid, except for 16kHz.

![noname](https://user-images.githubusercontent.com/62497891/150153226-7c7a6a17-e9a7-4c55-99e0-e41f3e5a0684.png)

**Comment by Oleg-Chashko** [comment]
I will make a preset table in the appropriate frequency grid for your equalizer (32Hz, 64Hz, 128Hz, 256Hz, 512Hz, 1KHz, 2KHz, 4KHz, 8KHz, 16KHz) and in the standard unit for your equalizer (from +12 to -12dB). 
But you will have to do the conversion to another standard.

**Comment by kode54** [comment]
I only took Winamp's settings because they were handy presets. If you want to make custom band presets, I need to add custom band preset support. Currently, it takes whatever bands are present in the source preset, and interpolates/extrapolates them to match the Apple GraphicEQ bands.

**Comment by Oleg-Chashko** [comment]
> I only took Winamp's settings because they were handy presets.

Winamp is dead. And Winamp's equalizer settings are dead, too. Strange that anyone was using it. I hope you don't use all of its equalizer settings.

It is advisable not to use all equalizer settings. But that's up to you. At this point in the day, these presets are **not usable**.

Here are a couple of examples of his equalizer settings.

---

- Apple Music
<img width="440" alt="Screen Shot 2022-01-20 at 13 37 43" src="https://user-images.githubusercontent.com/62497891/150340494-428daf50-6092-43e8-a2d4-ea772a325c8b.png">

- Winamp
<img width="705" alt="Screen Shot 2022-01-20 at 13 38 05" src="https://user-images.githubusercontent.com/62497891/150340516-115bef0f-0237-4565-b436-02f8ce00ef69.png">

---

- Apple Music
<img width="440" alt="Screen Shot 2022-01-20 at 13 44 26" src="https://user-images.githubusercontent.com/62497891/150341046-75e3802c-b258-443b-921e-ba72f771f211.png">

- Winamp
<img width="705" alt="Screen Shot 2022-01-20 at 13 44 48" src="https://user-images.githubusercontent.com/62497891/150341299-2a5165b2-ffe9-4e09-a038-2e19bb04f167.png">

---

**Comment by Oleg-Chashko** [comment]
The equalizer settings table I suggested uses Apple Music and the Swinsian player which uses the same equalizer as yours.
I trust Apple Music and Swinsian and my ears more than I trust dead Winamp.
But that's up to you to decide.

**Comment by kode54** [comment]
Then compile a list of presets, with their frequency bands, and I'll replace my set. Alternate genre matches suggested for any fields which can't be matched by a simple substring match of the preset genre against the track genre.

**Comment by Oleg-Chashko** [comment]
You wrote:
_The format is simple. Specific set of bands, range 1-64. 33 is centered, 1 is -12 dB, 64 is +12 dB._

1. There was a mathematical problem: for it to be like you said, there must be a range of 1 to 65.

<img width="1027" alt="Screen Shot 2022-01-21 at 14 21 18" src="https://user-images.githubusercontent.com/62497891/150535717-7d118922-af49-4eae-a309-bebb19a8396e.png">

2. In order for me to make an exact copy, I need a range of at least: (1 to 120 = -12dB)(121=centered=Flat=0dB)(122 to 241 = +12dB).
_If that works for you, this range, I'll make a file of the EQ presets._

**Comment by Oleg-Chashko** [comment]
Minimum accuracy range: (1 to 120 = -12dB)(121=centered=Flat=0dB)(122 to 241 = +12dB)

Average accuracy range: (1 to 200 = -20dB)(201=centered=Flat=0dB)(202 to 402 = +20dB)

Maximum accuracy range: (1 to 2000 = -20dB)(2001=centered=Flat=0dB)(2002 to 4002 = +20dB)

**Comment by Oleg-Chashko** [comment]
If you want to do it once and well then it is advisable to do the range:
- Range: -20dB to +20dB
Maximum accuracy range: (1 to 2000 = -20dB)(2001=centered=Flat=0dB)(2002 to 4001 = +20dB)

- Range: -12dB to +12dB
Minimum accuracy range: (1 to 120 = -12dB)(121=centered=Flat=0dB)(122 to 241 = +12dB)
Maximum accuracy range: (1 to 1200 = -12dB)(1201=centered=Flat=0dB)(1202 to 2401 = +12dB)

- Range: -20dB to +20dB
Minimum accuracy range: (1 to 200 = -20dB)(201=centered=Flat=0dB)(202 to 401 = +20dB)
Maximum accuracy range: (1 to 2000 = -20dB)(2001=centered=Flat=0dB)(2002 to 4001 = +20dB)

**Comment by Oleg-Chashko** [comment]
Example:
- Pulseaudio Equalizer (Linux)
Range: -20dB to +20dB
Minimum accuracy range: (1 to 200 = -20dB)(201=centered=Flat=0dB)(202 to 401 = +20dB)

**Comment by kode54** [comment]
Use whichever range you prefer, I will change the system around whatever preset range you use. I would prefer if you use a fixed list of bands, named `hz######`, for ease of reading, and a structure similar to the Winamp json I include now. It should include a different preset type tag at the top, and a preset list of members in the presets.

Each preset should have `name`, `hz######` for the list of bands you choose for your set, and optionally a `altGenres` member, which would contain a JSON array (`[ "blah", "blah" ]` etc) containing any alternate genres that should match this preset. The `altGenres` member is entirely optional. Their order is also currently acceptable in any order, since I check the names against an array of the names I expect. An array contains the minimum of `name` and the `hz#####` names, as well as `preamp` if you think we should include it. Or it checks against the optional `altGenres`.

If it's missing even one of the mandatory fields, it will ignore the preset. See: `Window/AUPlayerView.m` for the example of where the config is loaded and parsed.

**Comment by Oleg-Chashko** [comment]
Done, you can integrate it into the player.
When the player version is released, with the new presets, I will check and let you know if there are any problems.

1. EQ presets file: Winamp.q1.json -> Cog.q1.json
[Cog.q1.json.zip](https://github.com/losnoco/Cog/files/7918260/Cog.q1.json.zip)
2. Conversion table EQ: Conversion_table_EQ.pdf
[Conversion_table_EQ.zip](https://github.com/losnoco/Cog/files/7918261/Conversion_table_EQ.zip)
3. Cog Preset EQ: Cog_Preset_EQ.pdf
[Cog_Preset_EQ.pdf.zip](https://github.com/losnoco/Cog/files/7918264/Cog_Preset_EQ.pdf.zip)

**Comment by Oleg-Chashko** [comment]
Request to make:
1. Not required turn on the preamplifier, so you added a checkbox with "Limit volume control to 100%".
*. But it is necessary to correct the volume control characteristic, when the checkbox "Limit volume control to 100%" is activated.
<img width="230" alt="Screen Shot 2022-01-22 at 13 34 48" src="https://user-images.githubusercontent.com/62497891/150638823-7c7c988c-151c-49b9-be2e-7c89cf2d94e4.png">
 
---

2. Please back ("Flatten EQ" button), it will be more beautiful.
3. Please remove this if possible.
<img width="832" alt="Screen Shot 2022-01-22 at 13 35 06" src="https://user-images.githubusercontent.com/62497891/150639313-138f6952-52a8-4ea6-a277-f34bacf48bd7.png">

---

**Comment by kode54** [comment]
This should be fixed by 1885.

**Comment by Oleg-Chashko** [comment]
Please lift the "Flatten EQ" button up.
<img width="1432" alt="Screen Shot 2022-01-24 at 12 34 56" src="https://user-images.githubusercontent.com/62497891/150778672-546db7fc-75b0-4bec-9a28-1feda1b08572.png">

**Comment by Oleg-Chashko** [comment]
1. Fixed. 👍🏻
3. Fixed. 👍🏻
4. Fixed. 👍🏻

Request to make:
2. EQ button in the UI and the shortcut key.
5. Please lift the "Flatten EQ" button up.
<img width="1432" alt="150778672-546db7fc-75b0-4bec-9a28-1feda1b08572" src="https://user-images.githubusercontent.com/62497891/150779797-e98e3252-69e3-4f3a-a391-972d2a106392.png">

**Comment by kode54** [comment]
Oops, I didn't notice you already posted some stuff. Looking now.

**Comment by kode54** [comment]
Sorry I couldn't mess with the Flatten EQ button, if I so much as budge its window frame, the entire AU control view stops functioning. It uses some sort of auto layout mess, and it puts that control in the wrong place. That one's on Apple.

**Comment by Oleg-Chashko** [comment]
> I will check and let you know if there are any problems.

**Bug doesn't work Range "hz16000".**
![Cog_Preset_EQ](https://user-images.githubusercontent.com/62497891/151008014-df3eaedf-dc42-4f05-8819-ae0cd3228eb8.jpg)

**Comment by Oleg-Chashko** [comment]
> Sorry I couldn't mess with the Flatten EQ button, if I so much as budge its window frame, the entire AU control view stops functioning. It uses some sort of auto layout mess, and it puts that control in the wrong place. That one's on Apple.

Try lowering the 10 Bands/31 Bands button, maybe you can fix it?

**Comment by Oleg-Chashko** [comment]
You will be adding: EQ button in the UI and the shortcut key?

**Comment by kode54** [comment]
Please suggest a hotkey to bind, one which is not already in use by any of the other menu items, and not one of the global hotkeys.

Also, for the button, I will need an appropriate icon. And it cannot be an SF Symbols icon, unless you intend to export it as a template PDF for inclusion in the project for 10.14 and older.

**Comment by Oleg-Chashko** [comment]
> Also, for the button, I will need an appropriate icon. And it cannot be an SF Symbols icon, unless you intend to export it as a template PDF for inclusion in the project for 10.14 and older.

Done (drawn in app Sketch).

- Cog_EQ_2_Grey_colour.sketch
<img width="1178" alt="Sketch_Cog_EQ_2" src="https://user-images.githubusercontent.com/62497891/151156311-4bbbef07-0e9b-4f43-98b8-fe792b2dc8a2.png">

File: [Cog_EQ_2_Grey_colour.sketch.zip](https://github.com/losnoco/Cog/files/7941432/Cog_EQ_2_Grey_colour.sketch.zip)

---

- Cog_EQ_2_Black_color.sketch
<img width="935" alt="Screen Shot 2022-01-26 at 12 37 21" src="https://user-images.githubusercontent.com/62497891/151157024-c7a24d4d-e5b7-4ffe-a53b-f29f06934a4a.png">

File: [Cog_EQ_2_Black_color.sketch.zip](https://github.com/losnoco/Cog/files/7941437/Cog_EQ_2_Black_color.sketch.zip)
 
---

Files: Grey_colour_(png), (svg), (pdf)
[Grey_colour_(png).zip](https://github.com/losnoco/Cog/files/7941466/Grey_colour_.png.zip)
[Grey_colour_(svg).zip](https://github.com/losnoco/Cog/files/7941467/Grey_colour_.svg.zip)
[Grey_colour_(pdf).zip](https://github.com/losnoco/Cog/files/7941468/Grey_colour_.pdf.zip)

 ---

Files: Black_colour_(png), (svg), (pdf)
[Black_color_(png).zip](https://github.com/losnoco/Cog/files/7941472/Black_color_.png.zip)
[Black_color_(svg).zip](https://github.com/losnoco/Cog/files/7941474/Black_color_.svg.zip)
[Black_color_(pdf).zip](https://github.com/losnoco/Cog/files/7941473/Black_color_.pdf.zip)

**Comment by Oleg-Chashko** [comment]
> Please suggest a hotkey to bind, one which is not already in use by any of the other menu items, and not one of the global hotkeys.

Hotkey: **cmd** + **e** + **q** 
A unique combination of fingers! One hand is involved in the pressing. Not busy yet?

**Comment by Oleg-Chashko** [comment]
Easier icons.

<img width="565" alt="Screen Shot 2022-01-26 at 15 44 26" src="https://user-images.githubusercontent.com/62497891/151184589-aaffaad1-9352-4f05-8232-48d9c6cb1134.png">
Files: Black_colour_(png), (pdf)

[Black_colour_(pdf).zip](https://github.com/losnoco/Cog/files/7942700/Black_colour_.pdf.zip)
[Black_colour_(png).zip](https://github.com/losnoco/Cog/files/7942703/Black_colour_.png.zip)

---

<img width="344" alt="Screen Shot 2022-01-26 at 15 43 02" src="https://user-images.githubusercontent.com/62497891/151184603-400c7102-d5e8-462e-bd7b-e33707a798d9.png">
Files: Black_colour_(png), (pdf)

[Black_colour_(pdf).pdf.zip](https://github.com/losnoco/Cog/files/7942725/Black_colour_.pdf.pdf.zip)
[Black_colour_(png).png.zip](https://github.com/losnoco/Cog/files/7942726/Black_colour_.png.png.zip)

**Comment by kode54** [comment]
I'll take one of these after I review them, and I'll make a reminder to work on this next time I tackle the code. Thanks for your contributions.

**Comment by kode54** [comment]
By the way, I can't do a multi-key chord. The menus don't support that. It will have to be the Music shortcut, then.

**Comment by Oleg-Chashko** [comment]
>Thanks for your contributions.

Glad I could help.

>It will have to be the Music shortcut, then.

Excellent. **alt** + **cmd** + **e**

**Comment by Oleg-Chashko** [comment]
- Mockup:
<img width="1083" alt="Mockup" src="https://user-images.githubusercontent.com/62497891/151365214-80630516-aad7-4652-80e5-78bec3740b13.png">

**Comment by Oleg-Chashko** [comment]
Bug doesn't work Preset range "hz16000".
https://github.com/losnoco/Cog/issues/194#issuecomment-1021315679

**Comment by kode54** [comment]
hz16000 being broken by the predictor, and 20000 not being predicted right either, is fixed by impending commit, 9caf7046301e0a413f23564431258c822f21c30f.

**Comment by Oleg-Chashko** [comment]
Excellent work! Close issue.
