### ISSUE TITLE
Web: There was an error while loading the changelog & etc.

### ISSUE THREAD

**Issue by Oleg-Chashko** [losnoco/Cog#195]
https://cog.losno.co/download/

1. There was an error while loading the changelog.
2. After reloading the page: the same changelog is everywhere.

Example:

https://user-images.githubusercontent.com/62497891/149657863-c3487c73-5bce-44a6-9e03-15ca5c394182.mp4

**Comment by kode54** [comment]
Yes, I was migrating downloads.

@kddlb  There is still an issue if the /download link is loaded directly from an outside link, or if the refresh button is pressed while on the download page.

**Comment by Oleg-Chashko** [comment]
Fixed. Closed the issue.
