### ISSUE TITLE
Non-linear volume control characteristic

### ISSUE THREAD

**Issue by Oleg-Chashko** [losnoco/Cog#197]
Non-linear volume control characteristic.

**Screenshots**

<img width="967" alt="Screen Shot 2022-01-18 at 17 22 04" src="https://user-images.githubusercontent.com/62497891/149977677-a0e15e96-0183-4e58-bd0f-6694db5898e9.png">

**Version information:**
 - macOS version: 12.2 Beta (21D5039d)
 - Cog version: 1814 (1814-gec8466e5)

**Comment by nevack** [comment]
What's wrong? Volume scales logarithmically.

**Comment by Oleg-Chashko** [comment]
> What's wrong? Volume scales logarithmically.

- 50% should be at half scale.

<img width="199" alt="Screen Shot 2022-01-18 at 19 58 32" src="https://user-images.githubusercontent.com/62497891/150001429-b83d1a91-d780-4a0a-b8a7-21a1197f2081.png">

**Comment by nevack** [comment]
Oh, it's some new option i'm not familiar with.

Do you suggest to make volume slider linear with this option enabled?

**Comment by Oleg-Chashko** [comment]
> Oh, it's some new option i'm not familiar with.
> 
> Do you suggest to make volume slider linear with this option enabled?

Here is a typical volume control graph: (logarithmic)

![images](https://user-images.githubusercontent.com/62497891/150004070-1bf2cb61-b729-4054-b29a-3a3901c99a3e.png)

With the checkbox enabled:

![images-1](https://user-images.githubusercontent.com/62497891/150004194-e6a955c7-1dc6-48d6-997b-6db01e9a47fe.png)

Do you suggest to make volume slider linear with this option enabled?

Not with such a steep rise in characteristic, and 50% should be closer to the middle.

**Comment by Oleg-Chashko** [comment]
@nevack 
I checked the volume control in the macOS, if you look at the percentages, the response is linear and 50% in the middle. And if you look at the decibels, it is also linear and even. There is no logarithmic relationship.

**Comment by Oleg-Chashko** [comment]
At the moment, when the checkbox is on, this is the characteristic:

<img width="258" alt="100" src="https://user-images.githubusercontent.com/62497891/150010261-c771e955-536b-416f-872b-7322194ea75e.png">

**Comment by kode54** [comment]
The original control was non-linear. I just changed it to use a different maximum volume, because it was requested.

**Comment by Oleg-Chashko** [comment]
> The original control was non-linear. I just changed it to use a different maximum volume, because it was requested. I do need to change one of the converter functions to apply less sharp transition, due to the difference of 800 vs 100 as the maximum volume.

I saw this from the first day of use and understood why it was done, but with the introduction of the new feature there should be two modes. Up to 800% with logarithmic. Up to 100% with linear.

**Comment by Oleg-Chashko** [comment]
If you have the time and opportunity, please fix it. And it will be possible to close this issue, thank you.

**Comment by Oleg-Chashko** [comment]
Not fixed.

**Comment by kode54** [comment]
Blame @nevack

**Comment by kode54** [comment]
I'll fix it properly.

**Comment by kode54** [comment]
Committing fix.

**Comment by Oleg-Chashko** [comment]
Yes, fixed!👍🏻🎉
