### ISSUE TITLE
Crash: 1814 (1814-gec8466e5)

### ISSUE THREAD

**Issue by Oleg-Chashko** [losnoco/Cog#200]
**Describe**
During the playback of the track list, a crash occurred.

**Unfortunately, I can't give more information.**

**Version information:**
 - macOS version: 12.2 Beta (21D5039d)
 - Cog version: 1814 (1814-gec8466e5)

**Additional context**
[Cog-2022-01-18-133519.ips.zip](https://github.com/losnoco/Cog/files/7895635/Cog-2022-01-18-133519.ips.zip)

**Comment by kode54** [comment]
Please update the player.

**Comment by Oleg-Chashko** [comment]
> Please update the player.

Ok. I closed the issue.
