### ISSUE TITLE
The end of the track loops endlessly

### ISSUE THREAD

**Issue by Oleg-Chashko** [losnoco/Cog#201]
**Describe**

**The bug occurs when using rewind!**
Loops endlessly for about 2 seconds of the track and does not go to the next track in the list.

**Version information:**
 - macOS version: 12.2 Beta (21D5039d)
 - Cog version: 1830 (1830-g5f82fa57)

**Comment by kode54** [comment]
Please verify 1833.

**Comment by Oleg-Chashko** [comment]
> Please verify 1833.

- 1836 (1836-g698798a6)
Unfortunately, the problem is still present.

**Comment by kode54** [comment]
Is this from rewinding from way near the end? I had to specially handle seeking from way near the end, or else it would seek within the next track, which has already been switched to internally.

**Comment by Oleg-Chashko** [comment]
> Is this from rewinding from way near the end?

Yes.

**Comment by kode54** [comment]
What format are you playing? I can't reproduce this issue.

**Comment by Oleg-Chashko** [comment]
> What format are you playing? I can't reproduce this issue.

mp3 and FLAC

**Comment by kode54** [comment]
And how much is the looping? Forever? Or just for a moment? I am stopping playback and restarting it. Is this with a Bluetooth audio device in use?

**Comment by kode54** [comment]
I could change it to reuse the output, but that would require flushing it first.

**Comment by Oleg-Chashko** [comment]
And how much is the looping? 1 - 1.5sec.
Forever? Yes.
I am stopping playback and restarting it? No.
Bluetooth audio device in use? Yes.

Looping.
<img width="2519" alt="Screen Shot 2022-01-22 at 22 02 31" src="https://user-images.githubusercontent.com/62497891/150655575-88280b74-f241-4e39-8ce7-1318b597c589.png">

**Comment by kode54** [comment]
This should be fixed by 502e52d6993d2f2dd87ee10c446164d8df8208d0 / 1870.

**Comment by Oleg-Chashko** [comment]
1867 (1867-gae10e3e7)

- Turn on the sound when playing this video.

https://user-images.githubusercontent.com/62497891/150671354-0dc0a5a6-9e00-42a9-ba5f-6b3183cfdd93.mp4

**Comment by Oleg-Chashko** [comment]
I am stopping playback and restarting it? It happens in all variants: stopping playback and restarting.
Bluetooth audio device in use? It happens in all variants: Bluetooth audio device and System Audio.

**Comment by Oleg-Chashko** [comment]
> This should be fixed by [502e52d](https://github.com/losnoco/Cog/commit/502e52d6993d2f2dd87ee10c446164d8df8208d0) / 1870.

v.1875 (1875-g6b8d3003)
Not fixed.

**Comment by kode54** [comment]
I see what may be happening. I need to add another sync lock around a buffer there. I'll deal with that tonight.

**Comment by kode54** [comment]
This should be fixed by 1883.

**Comment by Oleg-Chashko** [comment]
Fixed. The issue is closed.
