### ISSUE TITLE
Custom accent color causes status icons to appear blank on selected row, on macOS Monterey

### ISSUE THREAD

**Issue by kode54** [losnoco/Cog#202]
Starting with macOS Monterey first 12.0 beta, and up to 12.1, the presence of a custom accent color causes NSTableView image cells with template images to color the template image incorrectly, and only on Dark Mode. It does not happen on Light Mode. It appears to be a macOS bug, rather than a bug with my app.

It is being tracked with Feedback reference FB9852263. Feel free to file redundant feedback issues reporting the same thing, and reference the existing FB9852263 with your issue.

This is not a bug in my app, unless you consider the only resolution is to remove the custom global accent setting from the build settings and asset catalog.

**Comment by kode54** [comment]
Further issues noted:

* It does not occur on Big Sur
* It does occur even without the custom accent color
* It only occurs on NSTableView that's Cell-based, not the newer View-based model

**Comment by kddlb** [comment]
Fixed with 2b4de1033dcb6f55f0fb10c685d459dc706b3fbe.
