### ISSUE TITLE
The equalizer does not save the settings after restarting the player

### ISSUE THREAD

**Issue by Oleg-Chashko** [losnoco/Cog#204]
The equalizer does not save the settings after restarting the player. The equalizer stays off, although the checkbox says that it is on. And only calling the equalizer window turns it on. 

**Version information:**
 - macOS version: 12.2 (21D48)
 - Cog version: 1867 (1867-gae10e3e7)

**Comment by kode54** [comment]
This should be fixed by 6011982a639c90e60622489b193f932b2d819f3d

**Comment by Oleg-Chashko** [comment]
Version 1875 (1875-g6b8d3003)
- Fixed: The equalizer does not save the settings after restarting the player. The equalizer stays off, although the checkbox says that it is on.
- Not fixed: And only calling the equalizer window turns it on.
