### ISSUE TITLE
Size at first startup in Mini Player mode

### ISSUE THREAD

**Issue by Oleg-Chashko** [losnoco/Cog#205]
- It is desirable that the horizontal size, at the first start, in the "Mini Player" mode unfolded completely.

At the moment:
<img width="744" alt="Screen Shot 2022-01-22 at 20 09 52" src="https://user-images.githubusercontent.com/62497891/150652221-fb122a58-553f-4d89-8aa9-f3801f78ceba.png">

Desirable:
<img width="875" alt="Screen Shot 2022-01-22 at 19 59 28" src="https://user-images.githubusercontent.com/62497891/150652124-fe0a2749-b2c6-4e9a-ad25-745a02b52144.png">

---

- Unfortunately, this window is not usable.
<img width="710" alt="Screen Shot 2022-01-22 at 20 18 19" src="https://user-images.githubusercontent.com/62497891/150652618-bcdc2ad1-592d-4165-adb9-96f4c199cc1f.png">

**Comment by nevack** [comment]
If Mini Window is too wide, it is unusable on small screens or with high system-wide scale factor.

**Comment by nevack** [comment]
I think it's possible to adjust items' priorities, Volume should be more important than Info/AlbumArt, imho.

**Comment by Oleg-Chashko** [comment]
> If Mini Window is too wide, it is unusable on small screens or with high system-wide scale factor.

The size is fine for me. The first time you turn it on, the full size is desirable. Later the user can reduce it to the size he wants.
Example: MacBook Pro (Retina, 13-inch, Early 2015)

<img width="668" alt="Screen Shot 2022-01-22 at 21 07 22" src="https://user-images.githubusercontent.com/62497891/150653942-c2a2e83e-60cf-49cf-9a31-a6c94f84ab20.png">

<img width="1485" alt="Screen Shot 2022-01-22 at 21 08 25" src="https://user-images.githubusercontent.com/62497891/150653983-d4f0cc8b-89ed-4cfe-8fcd-4dc1a9afc1c5.png">

**Comment by Oleg-Chashko** [comment]
> I think it's possible to adjust items' priorities, Volume should be more important than Info/AlbumArt, imho.

I completely agree with you.

**Comment by nevack** [comment]
You use scale lower than "Default", try "Larger Text" and you will see the issue.

**Comment by Oleg-Chashko** [comment]
"Default"

I'm sorry, but I don't see a issue.

<img width="1279" alt="Screen Shot 2022-01-22 at 21 37 33" src="https://user-images.githubusercontent.com/62497891/150654633-383eb2cb-ca39-4efd-bb38-1733fd30c521.png">

**Comment by nevack** [comment]
Try "Larger Text"

**Comment by Oleg-Chashko** [comment]
> Try "Larger Text"

I'm sorry, but I don't see a issue.

<img width="1023" alt="Screen Shot 2022-01-22 at 21 45 11" src="https://user-images.githubusercontent.com/62497891/150654841-6db383f9-df12-4dd6-be9a-75c4b929c5d8.png">

**Comment by nevack** [comment]
There're still some 11" macs and some low resolution external displays.
I don't think it's right to break things for these cases.
Take a look at https://github.com/losnoco/Cog/issues/125

**Comment by Oleg-Chashko** [comment]
I don't think it's right to break things for these cases.

Nothing breaks, read the title of the issue again.
Size at **FIRST** startup in Mini Player mode

**Comment by Oleg-Chashko** [comment]
If you don't want to change the FIRST launch in mini player mode.
Then change the popup for the moment, so it is usable.

**Comment by Oleg-Chashko** [comment]
> I don't think it's right to break things for these cases.

What is there to break? 
Anything that needs to be done:

![Screen](https://user-images.githubusercontent.com/62497891/150689480-7f7e0af3-6e75-4db6-b627-ab9082b52a06.gif)

**Comment by kode54** [comment]
Priority can be reduced for the HDCD indicator and track info buttons so they disappear first instead of appearing early. I'm not exactly sure how to do that, though.

**Comment by Oleg-Chashko** [comment]
@kode54 

Maybe make a compact version for the first run. And if the user wants to customize it, he can add the missing functions from the "Customize Toolbar"?

<img width="641" alt="Screen Shot 2022-01-24 at 16 33 37" src="https://user-images.githubusercontent.com/62497891/150813586-a446ebeb-2538-449b-9ff8-bbeaf0b138d5.png">

**Comment by Oleg-Chashko** [comment]
Fixed.
