### ISSUE TITLE
Align the double arrow on the axis of symmetry

### ISSUE THREAD

**Issue by Oleg-Chashko** [losnoco/Cog#206]
**Screenshots**

<img width="1144" alt="Screen Shot 2022-01-22 at 20 32 59" src="https://user-images.githubusercontent.com/62497891/150653200-b9824998-b7b6-4fb9-b553-d4300bc53713.png">

**Comment by nevack** [comment]
This sheet is provided by macOS/AppKit for all toolbar customizations.
There's nothing to do about it on Cog's site.

**Comment by Oleg-Chashko** [comment]
> This sheet is provided by macOS/AppKit for all toolbar customizations.
> There's nothing to do about it on Cog's site.

Then this issue will be marked as:
<img width="178" alt="Screen Shot 2022-01-22 at 20 55 51" src="https://user-images.githubusercontent.com/62497891/150653756-c0504e85-da60-426a-914a-88f3ea47e9c9.png">
