### ISSUE TITLE
Not Responding  v.1875 (1875-g6b8d3003)

### ISSUE THREAD

**Issue by Oleg-Chashko** [losnoco/Cog#207]
<img width="999" alt="Screen Shot 2022-01-23 at 10 09 02" src="https://user-images.githubusercontent.com/62497891/150672069-6c6c3b1d-c3a2-4d72-b873-68cdc11512cf.png">

**Comment by kode54** [comment]
This should be fixed by 1883.

**Comment by Oleg-Chashko** [comment]
Fixed. The issue is closed.
