### ISSUE TITLE
Crush: v.1885 (1885-g9e42df41)

### ISSUE THREAD

**Issue by Oleg-Chashko** [losnoco/Cog#208]
When the EQ window is open and there is a switch to a new track. This causes a crash.
[Cog-crush-log.zip](https://github.com/losnoco/Cog/files/7925286/Cog-crush-log.zip)

**Comment by kode54** [comment]
Also I can't reproduce the AU dialog crashing on AU release happening elsewhere. The dialog should be gone before the AU is released by the audio thread, anyway.

**Comment by Oleg-Chashko** [comment]
Can't reproduce this issue. Closed issue.
