### ISSUE TITLE
Problems when rewinding a track: Not Responding v.1885 (1885-g9e42df41)

### ISSUE THREAD

**Issue by Oleg-Chashko** [losnoco/Cog#209]
Turn on the sound during playback.

https://user-images.githubusercontent.com/62497891/150783551-aeb1e8e5-a956-4050-9964-c29cc32815d9.mp4

**Comment by kode54** [comment]
I can't reproduce this issue either. What sample rate is your sound output device set to? Mine usually ends up either 44100Hz or 48000Hz.

**Comment by Oleg-Chashko** [comment]
<img width="889" alt="Screen Shot 2022-01-25 at 05 03 46" src="https://user-images.githubusercontent.com/62497891/150908853-dd38321e-8993-4534-9ea6-0908dff1cf90.png">

**Comment by Oleg-Chashko** [comment]
I only use bluetooth. And I have a choice of 16 or 44.1

<img width="1069" alt="Screen Shot 2022-01-25 at 05 17 08" src="https://user-images.githubusercontent.com/62497891/150910173-995d2ea2-1c7b-44f5-8f52-6adfe29d1cb2.png">

**Comment by Oleg-Chashko** [comment]
In the player there are problems with rewind and for this occurs bugs and crashes.

**Comment by kode54** [comment]
Please post crash logs. I cannot reproduce this. It rewinds perfectly here.

**Comment by Oleg-Chashko** [comment]
This is "No response" no crash, no log file.

This problem will not occur in 99.8% of users. Don't worry about it. I just greatly increased the requirements for your application. That's my fault. I'm not launching it into space.

**Comment by kode54** [comment]
Using Activity Monitor to run a Spin Dump on Cog when it's locked up could help me. You only need to post the log it generates. Preferably from the debug build I linked, as that will have debugging symbols.

**Comment by Oleg-Chashko** [comment]
> Using Activity Monitor to run a Spin Dump on Cog when it's locked up could help me. You only need to post the log it generates. Preferably from the debug build I linked, as that will have debugging symbols.

Got it, thanks, I'll keep it in mind for the future, if I don't forget.
I just greatly increased the requirements for your application.

**Comment by kode54** [comment]
Nah, it's okay, it gives me some inspiration to keep it alive. I try to fulfill issue fixes now. And I caught a lot of attention yesterday due to a Hacker News mention.

**Comment by Oleg-Chashko** [comment]
That's a good player you've got there. I wish it would promote more, and more people knew about it. And I will try to limit myself in the depth of checking your app for quality. I wish further development of your project.
