### ISSUE TITLE
Number sign in folder names?

### ISSUE THREAD

**Issue by Mturner88** [losnoco/Cog#21]
If you have a folder name call cd#01, the files inside said folder won't play. Remove the # from the folder name to read cd01 the files will then play.

**Comment by kode54** [comment]
Again, the path processing is supposed to be interpreting those as %23, because the paths are treated like URLs, and thus # is a special character. This is strange.

**Comment by megadr01d** [comment]
@Mturner88 Please close the issue if fixed.
