### ISSUE TITLE
Stops playing track, rewind bug: v.1885 (1885-g9e42df41)

### ISSUE THREAD

**Issue by Oleg-Chashko** [losnoco/Cog#211]
Turn on the sound during playback.

https://user-images.githubusercontent.com/62497891/150801514-da6dd987-83c9-4047-a21a-aea612d80919.mp4

**Comment by kode54** [comment]
I also can't reproduce this issue.

**Comment by Oleg-Chashko** [comment]
Can't reproduce this issue. Closed issue.

**Comment by kode54** [comment]
Needs @nevack to test the issue too. Clearly something is at play here, even if I can't get this to happen in my system.

**Comment by Oleg-Chashko** [comment]
You will not be able to reproduce this on your system.
Closed the issue.

**Comment by kode54** [comment]
I wish I could reproduce it. I really do. I have attempted everything I can to try to get rid of seeking and track change issues. Can you try again?

**Comment by kode54** [comment]
If anything, please try the debug artifacts, which have a lot more logging information. I'll post one here.

**Comment by kode54** [comment]
https://cogcdn.cog.losno.co/Cog-778ac06-debug-artifact.zip

**Comment by Oleg-Chashko** [comment]
This problem will not occur in 99.8% of users. Don't worry about it. I just greatly increased the requirements for your application. That's my fault. I'm not launching it into space. 😀

**Comment by kode54** [comment]
Well, it was worth a shot anyway. If you ever feel like testing with debugging logs, you can launch Console.app, activate streaming, filter to "Cog", and launch the debug version from somewhere other than the same location as the regular release, so long as you don't run them both at once. It would have been nice to know why this sort of thing is happening. I hate Heisenbugs.

**Comment by Oleg-Chashko** [comment]
Logs:
[Stops playing track, rewind bug.zip](https://github.com/losnoco/Cog/files/7943791/Stops.playing.track.rewind.bug.zip)
[Not Responding.rtf.zip](https://github.com/losnoco/Cog/files/7943792/Not.Responding.rtf.zip)

**Comment by Oleg-Chashko** [comment]
- Try to do so. If you want to:
<img width="756" alt="Screen Shot 2022-01-26 at 18 33 38" src="https://user-images.githubusercontent.com/62497891/151216617-8435b5c3-1a5b-41b5-a687-83c0cbf5d7eb.png">

**Comment by kode54** [comment]
I can try to do that, if I knew how.

Meanwhile, it would help if you went to Activity Monitor.app, selected Cog, and clicked the circled ellipsis button next to the circled i info button, and selected "Spindump", when the errors occur. This will contain stack traces of the threads, and show me where they're stopped. Preferably with a debug version.

Here's a new debug version:

https://cogcdn.cog.losno.co/Cog-600c447-debug-artifact.zip
