### ISSUE TITLE
Mini player, it does not remember its location after restarting

### ISSUE THREAD

**Issue by Oleg-Chashko** [losnoco/Cog#212]
https://user-images.githubusercontent.com/62497891/150831488-1b4a1b3d-b0b4-4182-aa2b-dfe7b8dd80c8.mp4

**Comment by Oleg-Chashko** [comment]
If you have the time and opportunity, please fix it. And it will be possible to close this issue, thank you.

**Comment by kode54** [comment]
The possible issue is that there is code that forcibly sets the window frame size to width of N plus height of 1.

I am on break until the 7th of February. I will look at this then.

**Comment by Oleg-Chashko** [comment]
v.1939 (1939-g476c8897) Not fixed.

**Comment by kode54** [comment]
Works here. Maybe I should just rename the damn frame size option so it deletes the old one and saves to a new one.

**Comment by kode54** [comment]
Note that it only saves the size and position on proper shutdown, not continuously.

**Comment by Oleg-Chashko** [comment]
> Note that it only saves the size and position on proper shutdown, not continuously.

https://user-images.githubusercontent.com/62497891/151691786-87aefd9b-0bd2-4bed-8e63-47191f043a75.mp4

**Comment by kode54** [comment]
You are moving the window off the bottom of the screen. This is not supported. Cocoa automatically moves it back onto the screen on restart. In fact, saved window positions always include the usable region of the screen in the setting field, and clip the window within the latest range for that size on startup.

If you don't like this, take it up with Apple.

**Comment by Oleg-Chashko** [comment]
You are moving the window off the bottom of the screen. Not.

https://user-images.githubusercontent.com/62497891/151692147-42431264-02e6-44cf-b732-c447a4e967e9.mp4

**Comment by kode54** [comment]
Yes, the app lets you move it there. The Cocoa interface for saving window positions won't let you keep it there.
