### ISSUE TITLE
Streaming URL for Path column

### ISSUE THREAD

**Issue by lucianmarin** [losnoco/Cog#214]
It would be nice to have full streaming URL in Path column. Easier to search too.

**Comment by kode54** [comment]
What does it show now? I can add a change to display the full NSURL absoluteString when it's not a filePath.

**Comment by lucianmarin** [comment]
> What does it show now?

URL path without scheme, hostname or port. Scheme isn't useful, but hostname would be nice for filtering and column sorting.

**Comment by kode54** [comment]
I'll make a memo to fix this next time I go at the code.
