### ISSUE TITLE
PSF files cause Cog to hang

### ISSUE THREAD

**Issue by VulpineAmethyst** [losnoco/Cog#217]
**Describe**
Attempting to load a .psf file, e.g. from the Chrono Cross rip, causes Cog to hang.

**To Reproduce** (delete if not applicable)
1. Download and extract https://psf.joshw.info/c/Chrono%20Cross%20(1999-11-18)(Square)%5bPS1%5d.7z
2. Click File.
3. Select 'Add file'.
4. Open e.g. `102 The Brink of Death.psf` from the archive.
5. Observe as Cog freezes

**Expected behavior**
The file should load (relatively) quickly.

**Version information:***
 - macOS version: Monterey 12.1
 - Cog version: Version 1904 (1904-g600c4475)
 - Late 2015 Retina iMac (i.e. x86)

**Additional context**
MiniPSFs, PSF2s, and MiniPSF2s load as expected.

**Comment by kode54** [comment]
Yeah, the goddamned FFmpeg version I updated to, 5.0, takes PSF files from VGMStream for some stupid reason, and then locks up indefinitely. I'll push a fixed build some day.
