### ISSUE TITLE
Method for disabling "Enable Media Key access" -popup dialog?

### ISSUE THREAD

**Issue by esaruoho** [losnoco/Cog#22]
Hi, I use the macOS Function keys for controlling iTunes only.

Every time I boot up Cog, it asks

```
Enable Media Key access?
Media Key support requires the "Accessibility" permission.
You will need to restart the application for the change to take effect.
```

I do not want to ever have this, and I don't want Cog to ask me this every time I boot it up.

What should I do?

**Comment by kode54** [comment]
Even if it does take over the media keys, it relinquishes them if another application binds them. I have never provided an option to disable them.

**Comment by timmb** [comment]
+1 to this. I'd rather not give the app Accessibility permission if it's only to implement a functionality that I'm not using. I suggest a 'Do not show again' option on this dialog.

**Comment by nevack** [comment]
@esaruoho Is the issue still persists?
