### ISSUE TITLE
EQ: Preset Custom does not remember the settings after rebooting

### ISSUE THREAD

**Issue by Oleg-Chashko** [losnoco/Cog#222]
**Describe**
Preset Custom does not remember the settings after rebooting.

**Expected behavior**
Preset Custom does remember the settings after rebooting.

**Comment by kode54** [comment]
It saves when the equalizer is shut down. The fact that it isn't saving constantly must be a problem for people who reboot their computers spontaneously while all their software is still running. I will remember to look at this on the 7th.

**Comment by Oleg-Chashko** [comment]
It doesn't work for me. Thanks for looking later.

**Comment by Oleg-Chashko** [comment]
Issue closed, ok. The problem arises from the crash player.

**Comment by kode54** [comment]
Oh. I'll deal with it then. Please let me reopen. I have a listener already tracking when the user modifies the equalizer preset to set the listbox to "Custom". I'll add an option to save the current preset to the custom preset storage as well. This is a no brainer. But I am on break right now. So just leave this open until I deal with it, thanks.

**Comment by kode54** [comment]
There are several major issues outstanding, and I'm trying to keep myself sane by giving myself a break before addressing them, but if this keeps up, I may give up on taking a break after all.

**Comment by Oleg-Chashko** [comment]
Ok.

**Comment by Oleg-Chashko** [comment]
> There are several major issues outstanding, and I'm trying to keep myself sane by giving myself a break before addressing them, but if this keeps up, I may give up on taking a break after all.

Have a good rest, don't pay attention to what I write. You will deal with the issues later. I wish you a good holiday.
