### ISSUE TITLE
Crush: v.1925 (1925-g7be0ade7)

### ISSUE THREAD

**Issue by Oleg-Chashko** [losnoco/Cog#223]
**Describe**
Crush player. EQ bug.

**Screenshots**

https://user-images.githubusercontent.com/62497891/151658120-c0841aba-f0da-48bf-9bee-3acc3bcf898c.mp4

**Version information:**
 - macOS version: 12.2 (21D49)
 - Cog version: v.1925 (1925-g7be0ade7)

**Additional context**
[Archive Logs.zip](https://github.com/losnoco/Cog/files/7963523/Archive.Logs.zip)

**Comment by kode54** [comment]
Thanks for catching this. I'm adding it to my queue to look at when I return. Damn, that's an annoying issue.
