### ISSUE TITLE
UI improvements: Panel Spotlight

### ISSUE THREAD

**Issue by Oleg-Chashko** [losnoco/Cog#224]
On the Spotlight panel, align on the symmetry axis, move the (Add to Playlist) button up.

**Screenshots**
<img width="480" alt="Screen Shot 2022-01-29 at 13 31 59" src="https://user-images.githubusercontent.com/62497891/151661700-caad995f-e47e-472d-91ca-e02f468a72db.png">

**Comment by kode54** [comment]
Acknowledged. Added to todo list.
