### ISSUE TITLE
Reloading info resets/freezes the playback position slider

### ISSUE THREAD

**Issue by fjolnir** [losnoco/Cog#227]
**Describe**
 Reloading info causes the playback position to reset to 0:00 and become unresponsive until a different track is played

**To Reproduce** (delete if not applicable)
1. Start playing a song
2. Right click on it and reload info

**Version information:***
 - macOS version: 12.3
 - Cog version: Version 1974 (1974-g361f6161)

**Comment by kode54** [comment]
Yes, I know about this one, and I don't know what about the reload causes it.
