### ISSUE TITLE
Crash v.2056 (2056-gf2bebdef)

### ISSUE THREAD

**Issue by Oleg-Chashko** [losnoco/Cog#231]
[Cog-2022-02-13-120427.ips.zip](https://github.com/losnoco/Cog/files/8055403/Cog-2022-02-13-120427.ips.zip)

**Comment by kode54** [comment]
Literally have no idea why the equalizer dialog is crashing for you again.

**Comment by kode54** [comment]
I really need to ditch this stupid system equalizer control and make my own.

**Comment by Oleg-Chashko** [comment]
At the moment of transition from the light theme to the dark one.

**Comment by kode54** [comment]
I just toggled themes several times with no crash. I literally have no idea what's up.

**Comment by kode54** [comment]
Oh, maybe it's the spectrum? That should all be happening in a single thread, though, so nothing with the spectrum should be crashing.

**Comment by Oleg-Chashko** [comment]
https://user-images.githubusercontent.com/62497891/153750739-f62fd38b-41a3-4bc0-8b7a-32e2d702d6a7.mp4

**Comment by Oleg-Chashko** [comment]
> I really need to ditch this stupid system equalizer control and make my own.

I completely agree with you. I believe in your capabilities.

**Comment by Oleg-Chashko** [comment]
> Oh, maybe it's the spectrum? 

The crashing occurs only if the EQ window is open.

**Comment by Oleg-Chashko** [comment]
I found why you failed to trigger the crash. You made a mistake in the algorithm for reproducing this crash.

**Comment by kode54** [comment]
Please elaborate.

**Comment by Oleg-Chashko** [comment]
Necessary:
1. Launching the Cog.
2. Launching the EQ window.
3. Starts track playback.
4. Switching the theme from dark to light.
5. Crash.

Your algorithm:
1. Launching the Cog.
3. Starts track playback.
2. Launching the EQ window.
4. Switching the theme from dark to light.
5. Not Crash.

P.S.: It was noticed by me while watching your video file. And checked by the test.

**Comment by kode54** [comment]
This is fixed now, still using the system equalizer, but with my own custom dialog. Yes, the custom dialog did have some bugs in the recent version I uploaded, but I ran out of time, and needed sleep. Updates are coming.

**Comment by Oleg-Chashko** [comment]
Thank you. Closed the issue.
