### ISSUE TITLE
Improvement of the Volume Control

### ISSUE THREAD

**Issue by Oleg-Chashko** [losnoco/Cog#233]
- Improving the Volume Control:

After installing Cog and starting the player for the first time. The volume control is in the 100% position. And the start of the track is not very pleasant to hear because the volume is too high. Please make the volume control level between 50-70% for starting the player for the first time.

**Currently**
<img width="490" alt="Screen Shot 2022-02-13 at 14 41 10" src="https://user-images.githubusercontent.com/62497891/153756435-9e3c9bfe-02db-4bc5-bf64-b720c8b9098a.png">

**Desirable**
<img width="490" alt="Screen Shot 2022-02-13 at 14 42 22" src="https://user-images.githubusercontent.com/62497891/153756439-0e80d663-ef44-45ed-a133-a77466e496ac.png">

---

- The glow halo is cut off at the sides:

<img width="433" alt="153048001-5bb6df5e-9f16-408c-8519-b26ce073c4db" src="https://user-images.githubusercontent.com/62497891/153756024-7d99a95a-01c2-41cf-a2ee-7225e9c86414.png">

**Comment by kddlb** [comment]
The glow-halo being cut off is because it's drawn within the bounds of the popup.

**Comment by Oleg-Chashko** [comment]
Improving the Volume Control:
After installing Cog and starting the player for the first time. The volume control is in the 100% position. And the start of the track is not very pleasant to hear because the volume is too high. Please make the volume control level between 50-70% for starting the player for the first time.

?
