### ISSUE TITLE
Improvement of the Spectrum Analyzer

### ISSUE THREAD

**Issue by Oleg-Chashko** [losnoco/Cog#234]
- The color of the Background and the frame.

**Currently**

<img width="917" alt="Screen Shot 2022-02-13 at 15 03 22" src="https://user-images.githubusercontent.com/62497891/153759934-089d716e-ddfc-4767-80a3-bd5a71996462.png">

**Desirable**

<img width="1052" alt="Screen Shot 2022-02-13 at 14 33 41 copy" src="https://user-images.githubusercontent.com/62497891/153759952-0e51b3bf-e447-4a00-8ab1-0c2444cb7d6c.png">

---
- Clipping often occurs at lower frequencies.
- It is desirable to display the actual quality of the spectrogram. 
At this point in time, the spectrogram shows the quality, Thomas Edison's phonograph.

**Example**
<img width="666" alt="Screen Shot 2022-02-13 at 15 12 36" src="https://user-images.githubusercontent.com/62497891/153760385-acc1821b-067e-401a-a892-1c499872fa96.png">

**Currently**
![Screen_3](https://user-images.githubusercontent.com/62497891/153760425-3ad6ffd7-0cf6-4a1c-81ab-562e5533920d.gif)

**Desirable**

![Screen_2-20 (dragged)](https://user-images.githubusercontent.com/62497891/153760555-1e3438c8-20d5-4d9e-9f20-7ca13e63b271.jpg)

![Screen_2-304 (dragged)](https://user-images.githubusercontent.com/62497891/153760561-16762b24-05bf-4067-ba59-1ac5ab7f324d.jpg)

**Comment by Oleg-Chashko** [comment]
- The maximum frequency of the Spectrum Analyzer is about 5 kHz.

<img width="475" alt="Sine and square wave spot frequencies _ 5kHz" src="https://user-images.githubusercontent.com/62497891/153768942-393c4e40-1a77-4f1c-bbd3-954114ea3b59.png">

**Comment by Oleg-Chashko** [comment]
Please do not close. The Spectrum Analyzer still needs some work.

---

1. The maximum frequency of the Spectrum Analyzer is about 8-9 kHz.

https://user-images.githubusercontent.com/62497891/153872582-81a5f369-5403-4678-b716-5c0eaef0f20b.mp4

---

2. The spectrum is out of bounds on the right side of the frame.

<img width="196" alt="Screen Shot 2022-02-14 at 05 19 27" src="https://user-images.githubusercontent.com/62497891/153873228-333d0534-7d7d-4565-bfdd-a25e7201e3a3.png">

---

3. The spectrum is out of the frame window at 0 dB.

<img width="273" alt="Screen Shot 2022-02-14 at 14 02 11" src="https://user-images.githubusercontent.com/62497891/153873859-a574b70a-5984-48e3-a436-13c1e854f76e.png">

---

4. At this point, the frame doesn't look pretty. 
Preferably do as in the track duration counter. If this is not possible, remove the frame completely. 

<img width="535" alt="Screen Shot 2022-02-14 at 05 17 03" src="https://user-images.githubusercontent.com/62497891/153875433-2de3cffe-b643-4c03-9bc3-a92a0f87ab5b.png">

**Comment by kddlb** [comment]
It's good enough as it is.
