### ISSUE TITLE
Improvement UI: use a single color and shade

### ISSUE THREAD

**Issue by Oleg-Chashko** [losnoco/Cog#236]
- Use a single color and shade. 
![153773348-b58c5016-6fb0-42b7-a4af-219bf6b1440d](https://user-images.githubusercontent.com/62497891/153773558-cb16871c-8566-4bed-9ec5-9d1893f3a68b.png)

**Comment by kode54** [comment]
Cog uses a single color as a custom accent, with variations of generic, light, and dark. I have no control over what Sparkle's updater uses without rebuilding that.

**Comment by Oleg-Chashko** [comment]
Not possible to fix. Closed.
