### ISSUE TITLE
Bug "Castomize Toolbar..."

### ISSUE THREAD

**Issue by Oleg-Chashko** [losnoco/Cog#237]
https://user-images.githubusercontent.com/62497891/153774234-5eb30b14-a31d-4a74-9bb4-98f75c434b97.mp4

**Comment by Oleg-Chashko** [comment]
> Looks like it's SDK bug

There are no such problems with other icons.

**Comment by kode54** [comment]
This issue occurred because I mistakenly picked the Info Inspector button as the base to copy for these two new buttons, and they were still assigned the position behavior of "Navigational", which is why the Info and Folder buttons stick to the title bar.

**Comment by Oleg-Chashko** [comment]
v.2081 (2081-g570e2840)
Main the player - not fixed
Mini the player - fixed
