### ISSUE TITLE
When using a light desktop wallpaper, it is difficult to see the inscriptions in the equalizer

### ISSUE THREAD

**Issue by Oleg-Chashko** [losnoco/Cog#238]
When using a light desktop wallpaper, it is difficult to see the inscriptions in the equalizer.

1. Flatten EQ, Level Preamp, (Flat, Rock, Pop, ...)
2. Windows -> Equalizer

https://user-images.githubusercontent.com/62497891/153919737-eddd7894-0155-432f-8e8c-22b22efce926.mp4

**Comment by kode54** [comment]
Please check now.

**Comment by Oleg-Chashko** [comment]
It looks great, thank you. Closed issue.
