### ISSUE TITLE
Non-linearity in the spectrum analyzer and no range from 20-45Hz

### ISSUE THREAD

**Issue by Oleg-Chashko** [losnoco/Cog#240]
**1. Describe**
Non-linearity in the spectrum analyzer: Tone 10kHz

**Screenshot: Sine 10kHz, 0dBFS**
<img width="311" alt="Sine_10kHz_0dBFS_10s" src="https://user-images.githubusercontent.com/62497891/154122305-3d4a18a0-580a-4f6a-bced-7a19ff8f5238.png">

**Expected behavior**
It is desirable that the tone 10kHz is in the middle.

---

**2. Describe**
No range from 20-45Hz

**Screenshot: Sine 50Hz, 0dBFS**
<img width="311" alt="Screen Shot 2022-02-15 at 19 15 29" src="https://user-images.githubusercontent.com/62497891/154125171-59b9d7ce-ece9-480c-8986-2ac50e3db6e2.png">

**Expected behavior**
It is desirable that the tone 20Hz is in the beginning.

**Version information:**
 - Cog version: 2081 (2081-g570e2840)

---

**Made files for the test check: Sine 20Hz, 50Hz, 10kHz, 20kHz, Sweep 20Hz-20kHz**

[Test files.zip](https://github.com/losnoco/Cog/files/8073719/Test.files.zip)

**Comment by kode54** [comment]
It's linear by notes/octaves, not by frequency number. I really don't understand the point to it being linear by frequency number, when that's not how we perceive sound.

**Comment by kode54** [comment]
Thanks, those test tones broke my sound output. Guaranteed, reach the end of clip, sound output breaks.

**Comment by Oleg-Chashko** [comment]
> Thanks, those test tones broke my sound output. Guaranteed, reach the end of clip, sound output breaks.

The test tones could not have broken your sound. It could have happened through excessive amplification (Sound Control from 100-800%). Also, if the output power of the amplifier equals or exceeds the power of the speaker system. I thought you knew that. Good thing the building didn't go into resonance and collapse.

**Comment by kode54** [comment]
My player volume is set to 25%. I'm piping it through the HRIR filter. The sound device volume is configured to about 45%. It still output a NaN or INF somewhere. I have to figure out where.

**Comment by Oleg-Chashko** [comment]
> It's linear by notes/octaves, not by frequency number. I really don't understand the point to it being linear by frequency number, when that's not how we perceive sound.

I agree with you there. 
I often have to guess. Since I have no information, what you wanted to do and what you ended up with. 
Spectrum analyzer measurements can be made in both linear and logarithmic.

Example:

![2](https://user-images.githubusercontent.com/62497891/154187201-bf937eb6-fdfc-43a6-a165-b3dfcb91649b.png)
![1](https://user-images.githubusercontent.com/62497891/154187206-cf7c1218-dceb-4fc8-ba73-a4452140ac0e.gif)

**Comment by Oleg-Chashko** [comment]
> No range from 20-45Hz

Will you try to fix it?

**Comment by Oleg-Chashko** [comment]
> Thanks, those test tones broke my sound output. Guaranteed, reach the end of clip, sound output breaks.

Improvement of the Volume Control #233

- Improving the Volume Control:
After installing Cog and starting the player for the first time. The volume control is in the 100% position. And the start of the track is not very pleasant to hear because the volume is too high. Please make the volume control level between 50-70% for starting the player for the first time.

Somebody's ears could have been hurt here.
The topic was closed because no one cares about the ears of users.

**Comment by Oleg-Chashko** [comment]
I see that you are closing issues without solving the problem. I won't bother you anymore. :)
