### ISSUE TITLE
[Cog 2047-gc39b7ee9] First play is not random on open

### ISSUE THREAD

**Issue by fulldecent** [losnoco/Cog#241]
**Describe**

First play is not random on open

**To Reproduce** (delete if not applicable)

1. Add songs to playlist
2. Turn on random
3. Close Cog
4. Open Cog
5. Press play

**Expected behavior**

A random song is played

**Actual outcome**

The first song is played

**Version information:***
 - macOS version: 12
 - Cog version: Cog 2047-gc39b7ee9

**Comment by kode54** [comment]
I'm not sure what you expect, but the playback focus on first start, or when hitting the play button, focuses either the last track selected, or the first track in the playlist. Shuffle only controls which track is next after the current track.

Shuffle also doesn't remember its playback order after quitting and restarting the player.

**Comment by fulldecent** [comment]
Here is my experience: https://youtu.be/wQSkaf_nQDs

---

Every time I open the app and press play it is playing the first song.

It DOES remember that I am on shuffle, which is good.

So I am expecting that if I open it and press play then it will either continue with the previously select song....

or if it for some reason it forgot what my previously selected song was, then if the mode the shuffle then the default should be to pick a random song rather than the first song.

**Comment by kode54** [comment]
It does remember that you're on shuffle. It does not, however, remember what the play order was since the last session. It will reshuffle the playlist on startup.
