### ISSUE TITLE
[Cog 2110-g90ed0230] Current Time digits enlarge

### ISSUE THREAD

**Issue by ThomRoss** [losnoco/Cog#243]
**Describe**
Current Time digits enlarge in size when a track starts playing. The digits remain enlarged until the next restart of Cog (or, more precisely, until the first Play action, when they enlarge again).

**Expected behavior**
I would appreciate some workaround for the Current Time digits not to enlarge and get cut off.

**Screenshots**
<img width="169" alt="cog-time" src="https://user-images.githubusercontent.com/100146600/154984497-d7e9dad2-ce80-4e1e-8e46-4af61fc449f2.png">

**Version information:***
 - macOS version: 10.13.6
 - Cog version: 2110 (2110-g90ed0230)

**Additional context**
—

**Comment by kode54** [comment]
I don't know which macOS releases have such a tiny toolbar, but here:
<img width="75" alt="Screen Shot 2022-02-21 at 4 51 28 PM" src="https://user-images.githubusercontent.com/796316/155043834-52361250-ffef-44c0-b9b5-762646ddba20.png">

I guess I'll make it 11 points on 10.13 and 10.12.

**Comment by ThomRoss** [comment]
It was just a little cosmetic issue, but thank you for fixing it, Christopher. My OCD can rest happy now.

**Comment by kode54** [comment]
Glad it fixed it for you. I wasn't aware there were major font size differences across OS releases. It's been a hot minute since I last used 10.13, heh.
