### ISSUE TITLE
Tracks Shorter Than 2 Seconds Don't Play

### ISSUE THREAD

**Issue by itl20xx** [losnoco/Cog#246]
In the last few versions of Cog, there has been a bug where short tracks refuse to play. It doesn't matter which file format they are; they all experience this. I've attached a screen recording of what it looks like when this occurs.

https://user-images.githubusercontent.com/101009337/156889713-46dccbf7-9404-4609-a1f0-ba629f49e220.mov

**Comment by kode54** [comment]
It was a combination of two issues:

1) Input starting output thread on end of file, before queueing another track.
2) Output not starting itself if it finished so quickly that it hit the "stop" function before playback was actually started.

Build incoming.

**Comment by kode54** [comment]
New build is up.
