### ISSUE TITLE
txtps that specify certain channels play them all 

### ISSUE THREAD

**Issue by LukeWarnut** [losnoco/Cog#247]
**Describe**
Vgmstream txtps that specify the playback of certain channels erroneously play every channel in the file.
This can be seen in when playing back this txtp for Mario Kart 8 Deluxe:
`pBGM_WU_WOOD_F.bfstm#C1,2`

**To Reproduce**
1. Download [MK8D.zip](https://github.com/losnoco/Cog/files/8316012/MK8D.zip)
2. Play `pBGM_WU_WOOD_N_MAIN.txtp` in Cog
3. Compare playback with another way of using vgmstream.

**Expected behavior**

[Comparison.zip](https://github.com/losnoco/Cog/files/8316113/Comparison.zip)

**Version information:***
 - macOS version: 11.4 (Big Sur)
 - Cog version: 2154-g38969cd3

**Comment by kode54** [comment]
Should be fixed by 69ebce32c014b998a84cbe3c2b1b65e4360016ca
