### ISSUE TITLE
Cog not remembering playing

### ISSUE THREAD

**Issue by reagle** [losnoco/Cog#248]
When I quit cog and open it later, the play list is blank. Should it not remember what the last play list was if there was a proper quit?

Cog 2154 on macOS 12.3 21E230 arm64

**Comment by kode54** [comment]
Sounds like it's corrupting the database? It did that to me too, but only because it crashed on shutdown. I'm not sure why it would do that, though.

**Comment by reagle** [comment]
These are command-Q quits, not crashes. If there's some config or database to delete to start fresh, let me know and I will try.

**Comment by kode54** [comment]
Back up and wipe the contents of `~/Library/Application Support/Cog`. Default.m3u would be a playlist from over 7 years ago, Default.xml would be a playlist from many months ago, Default.sqlite would be the current format. The latter may be present, but corrupt.

**Comment by reagle** [comment]
I quit cog, removed that folder, opened cog, created a play list, and quit cog. The `~/Library/Application Support/Cog` has returned, but there's nothing in it.

**Comment by kode54** [comment]
Try this debug artifact, and log with Console.app filtered to "Cog" and see what turns up:

https://cogcdn.cog.losno.co/Cog-69ebce3-debug-artifact.zip

**Comment by kode54** [comment]
I guess I'll have to make the player impossible to quit while it's busy scanning added files.

**Comment by kode54** [comment]
Retry again. Closing until further feedback arrives.
