### ISSUE TITLE
Cog slows down significantly with even moderately long playlists/folders

### ISSUE THREAD

**Issue by althonich** [losnoco/Cog#249]
**Describe:**
When playing a playlist that I have that has 360 songs (which is 1 day, 4 hours, 30 minutes and 3 seconds long exactly), it takes around 30 seconds to open the folder the songs are located in.

There is a noticeable delay between songs as well, when skipping a few songs or just adding a new song in the playlist.

Ruling out hardware power as this is running on an M1 Max MacBook Pro, though this may be a problem with the M1 machines, I'm not skilled enough to know.

**To Reproduce:**
1. Get a moderately large playlist/folder.
2. Try to play it, try skip a few songs and notice the delay before the song start playing.

**Expected behavior:**
No lag when opening playlist/folder.
No lag between songs in a long playlist/folder.

**Version information:***
 - macOS version: MacOS Monterey 12.3.1
 - Cog version: Version 2156 (2156-g2ed46303)

**Extra notes:**
I love this app as it allows me to use my folders of existing songs as 'playlists' and such. Keep up the great work! I hope to contribute more bug reports and perhaps donate in the future.

**Comment by kode54** [comment]
I do notice that a folder and M3U8 playlist of over 4000 MP3 files takes about 5 seconds to populate the playlist entries, then a progress meter appears on the icon indicating it takes about 3-4 minutes to populate the track information for all those files. Track changes are near instantaneous after that.

**Comment by althonich** [comment]
After getting a new update today, I've noticed the issue is almost gone.

I opened that huge folder again and it only took around 1-2 seconds and played pretty well after that.
