### ISSUE TITLE
Catalina: High CPU usage of WindowServer process after latest security update 2022-004

### ISSUE THREAD

**Issue by mag01** [losnoco/Cog#255]
**Describe**
I'm running the macOS Catalina and after installing the latest security update (2022-004 https://support.apple.com/en-us/HT213255 - 10.15.7 19H1922) I noticed a high CPU usage of the WindowServer process when running Cog.
It doesn't seem to occur when other apps are in use or at least I haven't found any other one that would cause this.

I tried to update the Cog to the latest build (2169-gbf54c452 from https://cog.losno.co/download) to see if that makes any difference, but unfortunately it doesn't.

Removing the Spectrum item from the toolbar partially helps, however it doesn't fully remedy the issue (and still the issue didn't previously occur even with Spectrum active).
Minimizing the Cog window helps even more (and maybe brings things back to normal, though I can't compare it directly).

I'm fully aware it could be likely an OS rather than Cog related issue, however it doesn't really appear to affect other apps so there could be something to do about it in the Cog.

The machine is an old 2012 MacBook Air 11", 2 CPU cores, 4 threads, so such things are pretty visible there with fan kicking in shortly after the issue start to occur.

Typical CPU usage examples:
- roughly idle: user 4%, system 3%, idle 93%
- Cog running and stopped: same as idle
- Cog playing with Spectrum on (MP3, FLAC, doesn't matter much): user 20%, system 5%, idle 75% (approx. 55% is WindowServer process)
- Cog playing with Spectrum off: user 13%, system 6%, idle 81%
- Cog playing minimized with Spectrum on: user 10%, system 6%, idle 84%
- Cog playing minimized with Spectrum off: user 6%, system 5%, idle 89%

If there's anything I can help with in order to diagnose this please let me know.

**Version information:***
 - macOS version: 10.15.7 (19H1922)
 - Cog version: Version 2169 (2169-gbf54c452)

**Additional context**
Started to occur after installing the macOS Catalina Security Update 2022-004 https://support.apple.com/en-us/HT213255

**Comment by kode54** [comment]
It's doing that even on an M1 running Monterey. I think the only choice is to either reimplement the entire visualizer using Metal, or turn it off entirely.

**Comment by kode54** [comment]
This has been fixed by dc103ac546bf3e3b19559e708c52dcc15284c429 which also disables visualizations when they're not visible. Prior releases, the visualization would still process audio, even if it's not drawing. In your case, it's also the visualizer drawing. Remove the visualizer from the toolbar to disable it. I'll have to consider disabling it by default.
