### ISSUE TITLE
Crash (SIGFPE) in SpectrumView at start after update to gfce0e129

### ISSUE THREAD

**Issue by kolen** [losnoco/Cog#257]
**Describe**
Cog always crashes when starting it. It started to occur after updating to gfce0e129. Latest version, gc59d4d02, also crashes. This commit (gfce0e129) introduced changes to spectrum visualizer.

**To Reproduce** (delete if not applicable)
1. Start the program
2. It crashes with floating point exception in thread related to spectrum visualization

**Expected behavior**
Program starts

**Version information:**
 - macOS version: 10.13.6
 - Cog version: 2170-gfce0e129, 2181-gc59d4d02

**Additional context**
[Crash report](https://gist.github.com/kolen/644b9dd8a4cb37d4e0a1523660865063)

**Comment by kode54** [comment]
Ah, I see the issue. Your GPU doesn't support Metal, so I shouldn't be forcing the Metal renderer in the SceneKit options.

**Comment by ThomRoss** [comment]
For me, 2181 is the last crash-free version of Cog. :( Every update since 2181 causes Cog to crash on start, and reverting to 2181 seems to be the only fix. 
I'm on macOS 10.13.6 as well.

[Crash Report](https://github.com/losnoco/Cog/files/8791469/crash_report.txt)

**Comment by kode54** [comment]
Apparently SceneKit doesn't support the 10.8 minimum it claims in the documentation? Guess I better bump the minimum to 10.14.

**Comment by kode54** [comment]
Technically the minimum I test on is the latest 12.4. And I use OpenCore Legacy Patcher to run that on my no longer supported machines. Good thing I never had nvidia gpus.

**Comment by kode54** [comment]
Looks like I fixed this with 2193.

**Comment by ThomRoss** [comment]
Just tried 2194 – no crashes at start anymore! 
Many thanks, Christopher! I love Cog. ⚙️💛🤓

**Comment by kode54** [comment]
Yeah, that version forces Metal only render. I have similarly updated it again, this time disabling visualization entirely if Metal doesn't have any devices to render with. Apparently, the OpenGL renderers are totally bonkers.

GL 4.1 is broken on M1 on Monterey 12.4. GL 3.2 works, but looks awful.

Apparently both of those GL renderers are broken on High Sierra and cause floating point division by zero exceptions. So now the visualizer view will return nil on init and dispose of itself, so the resulting toolbar control should take up no space in the toolbar, and the visualization window will just be empty.
