### ISSUE TITLE
Double speed bug when pressing multiple media keys

### ISSUE THREAD

**Issue by uyjulian** [losnoco/Cog#26]
There is a bug that causes the audio to play twice as fast when multiple playback keys are pressed at the same time.
How to reproduce:
1. Press ⏪ and ⏩ on the keyboard at the same time

**Comment by megadr01d** [comment]
I was able to replicate this by alternating the previous/next track shortcuts, one at a time, in a rapid and random fashion.  I was able to discern 2 different playback velocities, on 2 different occasions.
It sounded cool, tho, on a couple of slow, mellow tracks.

**Comment by kode54** [comment]
This should not be happening any more.
