### ISSUE TITLE
Cog is crashing on set as playlist

### ISSUE THREAD

**Issue by reagle** [losnoco/Cog#261]
Like issue #245 , cog crashed on a "set as playlist" with two sibling folders. Reopening causes it to immediately crash.

cog: 2194,539a8c79
OS: macOS 12.4 21F79 arm64

**Comment by kode54** [comment]
What is in these two folders? I tried setting two sibling folders as playlist, and it worked. Except one of the folders was empty.

**Comment by kode54** [comment]
Please email me your Default.sqlite, compressed in a zip (right click, compress, will be sufficient), at cogplaylist@kode54.net

**Comment by reagle** [comment]
Okay, email sent.

**Comment by kode54** [comment]
Try `2221`.

**Comment by kode54** [comment]
On second thought, try `2223`.

**Comment by reagle** [comment]
Okay, 2223 is behaving better and I've emailed a corrupted file that causes it to crash.
