### ISSUE TITLE
Regression: Crashing on Version 2217-g91898e9e

### ISSUE THREAD

**Issue by tungol** [losnoco/Cog#262]
**Describe**
I'm getting a crash on Version 2217-g91898e9e that isn't there on Version 2212-gf2b015c1. It occurs whenever I try to play a song. 

**To Reproduce** (delete if not applicable)
1. Launch Cog
2. Select song on playlist
3. Hit enter to begin playback
4. Cog crashes.

**Expected behavior**
I expect the song to play

**Screenshots**

**Version information:***
 - macOS version: macOS 12.3
 - Cog version: Version 2217-g91898e9e

**Additional context**
My music files are stored on an NFS volume mounted in finder, if that might be a complicating factor.

Here's the crash report:

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Cog [18653]
Path:                  /Applications/Cog.app/Contents/MacOS/Cog
Identifier:            org.cogx.cog
Version:               2217 (2217-g91898e9e)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-06-09 15:32:31.9071 -0700
OS Version:            macOS 12.3 (21E230)
Report Version:        12
Anonymous UUID:        1957DD90-0247-E660-DACC-8558592BD035

Sleep/Wake UUID:       9A896018-9511-4FAD-B2A6-5E6F8D7EB3CD

Time Awake Since Boot: 57000 seconds
Time Since Wake:       14723 seconds

System Integrity Protection: enabled

Crashed Thread:        10

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x00000001a20adf4c
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [18653]

Application Specific Information:
Thread is not a member of the workgroup

Thread 0::  Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib               	       0x1a20c29c8 objc_release + 88
1   libobjc.A.dylib               	       0x1a20c72c4 AutoreleasePoolPage::releaseUntil(objc_object**) + 196
2   libobjc.A.dylib               	       0x1a20c3b04 objc_autoreleasePoolPop + 212
3   CoreFoundation                	       0x1a22c3b78 _CFAutoreleasePoolPop + 32
4   Foundation                    	       0x1a31b24fc -[NSAutoreleasePool drain] + 140
5   AppKit                        	       0x1a4e546c4 -[NSApplication run] + 648
6   AppKit                        	       0x1a4e25da8 NSApplicationMain + 1132
7   dyld                          	       0x101211088 start + 516

Thread 1:
0   libsystem_pthread.dylib       	       0x1a2235078 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x1a2235078 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x1a2235078 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	       0x1a2235078 start_wqthread + 0

Thread 5:
0   libsystem_kernel.dylib        	       0x1a21fc924 semaphore_timedwait_trap + 8
1   Cog                           	       0x100f3d05c 0x100f28000 + 86108
2   Foundation                    	       0x1a31d971c __NSThread__start__ + 808
3   libsystem_pthread.dylib       	       0x1a223a26c _pthread_start + 148
4   libsystem_pthread.dylib       	       0x1a223508c thread_start + 8

Thread 6:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x1a21fc8d0 mach_msg_trap + 8
1   libsystem_kernel.dylib        	       0x1a21fcd40 mach_msg + 76
2   CoreFoundation                	       0x1a2306c1c __CFRunLoopServiceMachPort + 372
3   CoreFoundation                	       0x1a23050cc __CFRunLoopRun + 1180
4   CoreFoundation                	       0x1a2304490 CFRunLoopRunSpecific + 600
5   AppKit                        	       0x1a4fd0794 _NSEventThread + 196
6   libsystem_pthread.dylib       	       0x1a223a26c _pthread_start + 148
7   libsystem_pthread.dylib       	       0x1a223508c thread_start + 8

Thread 7:: AMCP Logging Spool
0   libsystem_kernel.dylib        	       0x1a21fc90c semaphore_wait_trap + 8
1   caulk                         	       0x1aac8ea2c caulk::mach::semaphore::wait_or_error() + 28
2   caulk                         	       0x1aac7277c caulk::concurrent::details::worker_thread::run() + 56
3   caulk                         	       0x1aac7239c void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 96
4   libsystem_pthread.dylib       	       0x1a223a26c _pthread_start + 148
5   libsystem_pthread.dylib       	       0x1a223508c thread_start + 8

Thread 8:: com.apple.audio.toolbox.AUScheduledParameterRefresher
0   libsystem_kernel.dylib        	       0x1a21fc90c semaphore_wait_trap + 8
1   caulk                         	       0x1aac8ea2c caulk::mach::semaphore::wait_or_error() + 28
2   caulk                         	       0x1aac7277c caulk::concurrent::details::worker_thread::run() + 56
3   caulk                         	       0x1aac7239c void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 96
4   libsystem_pthread.dylib       	       0x1a223a26c _pthread_start + 148
5   libsystem_pthread.dylib       	       0x1a223508c thread_start + 8

Thread 9:
0   libdispatch.dylib             	       0x1a20adf4c os_workgroup_interval_start.cold.1 + 24
1   libdispatch.dylib             	       0x1a208f4cc os_workgroup_interval_start + 304
2   CogAudio                      	       0x1013d253c -[Node startWorkslice] + 76
3   CogAudio                      	       0x1013d1998 -[InputNode process] + 460
4   CogAudio                      	       0x1013d2414 -[Node threadEntry:] + 56
5   Foundation                    	       0x1a31d971c __NSThread__start__ + 808
6   libsystem_pthread.dylib       	       0x1a223a26c _pthread_start + 148
7   libsystem_pthread.dylib       	       0x1a223508c thread_start + 8

Thread 10 Crashed:
0   libdispatch.dylib             	       0x1a20adf4c os_workgroup_interval_start.cold.1 + 24
1   libdispatch.dylib             	       0x1a208f4cc os_workgroup_interval_start + 304
2   CogAudio                      	       0x1013d253c -[Node startWorkslice] + 76
3   CogAudio                      	       0x1013e39d0 -[ConverterNode process] + 132
4   CogAudio                      	       0x1013d2414 -[Node threadEntry:] + 56
5   Foundation                    	       0x1a31d971c __NSThread__start__ + 808
6   libsystem_pthread.dylib       	       0x1a223a26c _pthread_start + 148
7   libsystem_pthread.dylib       	       0x1a223508c thread_start + 8

Thread 10 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000000000000   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x50b47382f772001d   x9: 0x50b47382f772001d  x10: 0xfffffffe5dfb748b  x11: 0x0000000000000001
   x12: 0x00000000c0dffffc  x13: 0x0000000040dff800  x14: 0x0000000040c00000  x15: 0xffffffffffffffff
   x16: 0xfffffffffffffff4  x17: 0x00000001fc0a7ed0  x18: 0x0000000000000000  x19: 0x000000013ee12780
   x20: 0x0000000000000000  x21: 0x000000012f036038  x22: 0x0000000101404000  x23: 0x000000016f4d70e0
   x24: 0x0000000101404000  x25: 0x0000000101404000  x26: 0x0000000101404000  x27: 0x0000000101404000
   x28: 0x0000000101404000   fp: 0x000000016f4d2bf0   lr: 0x4d240001a20adf4c
    sp: 0x000000016f4d2bf0   pc: 0x00000001a20adf4c cpsr: 0x60001000
   far: 0x00000001058f4000  esr: 0xf2000001 (Breakpoint) brk 1

Binary Images:
       0x1a20b9000 -        0x1a20f6fff libobjc.A.dylib (*) <4b5ab8fb-60e0-3992-ba0e-a073a3fa86a7> /usr/lib/libobjc.A.dylib
       0x1a2282000 -        0x1a27c7fff com.apple.CoreFoundation (6.9) <8e1809ff-f5b1-3d9e-be15-f2e7b1d8ce51> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
       0x1a317d000 -        0x1a356dfff com.apple.Foundation (6.9) <589677dd-19b7-3f93-b2b6-eed7117729ca> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
       0x1a4e22000 -        0x1a5cd9fff com.apple.AppKit (6.9) <465b9570-6646-31ea-a082-ab0dfa538966> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x10120c000 -        0x10126bfff dyld (*) <fbb89662-e6f2-3434-b542-f75185ac5e74> /usr/lib/dyld
       0x1a2233000 -        0x1a223ffff libsystem_pthread.dylib (*) <cee8bc77-6923-34d9-89a3-6f8f7279605e> /usr/lib/system/libsystem_pthread.dylib
       0x1a21fb000 -        0x1a2232fff libsystem_kernel.dylib (*) <1d7b3b8e-75a1-34ea-aa52-9f7c23155c55> /usr/lib/system/libsystem_kernel.dylib
       0x100f28000 -        0x1010b7fff org.cogx.cog (2217) <fcdc0cf6-cfc2-31ac-8ca7-3823cbe81a24> /Applications/Cog.app/Contents/MacOS/Cog
       0x1aac70000 -        0x1aac96fff com.apple.audio.caulk (1.0) <23d0d7ce-cb87-35f3-9c15-943bd8f6645a> /System/Library/PrivateFrameworks/caulk.framework/Versions/A/caulk
       0x1a2072000 -        0x1a20b8fff libdispatch.dylib (*) <dc048e3b-e023-3d17-afe5-4ff3dc625608> /usr/lib/system/libdispatch.dylib
       0x1013c0000 -        0x1013fbfff org.cogx.cogaudio (*) <7d4f05cb-e6a0-3ac2-afc5-e495c5f2cb67> /Applications/Cog.app/Contents/Frameworks/CogAudio.framework/Versions/A/CogAudio

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)
Writable regions: Total=1.3G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.3G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               384K        3 
Activity Tracing                   256K        1 
CG backing stores                 3520K        4 
CG image                          32.3M       10 
CG raster data                     384K        2 
ColorSync                          592K       26 
CoreAnimation                     13.0M      142 
CoreGraphics                        16K        1 
CoreServices                      7424K        6 
CoreUI image data                 2208K       18 
Foundation                        1008K        3 
Image IO                          4352K        2 
Kernel Alloc Once                   32K        1 
MALLOC                           270.6M       61 
MALLOC guard page                  192K       11 
MALLOC_MEDIUM (reserved)         600.0M        5         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
SQLite page cache                 1088K       17 
STACK GUARD                       56.2M       11 
Stack                             13.3M       12 
VM_ALLOCATE                        544K       15 
VM_ALLOCATE (reserved)              64K        1         reserved VM address space (unallocated)
__AUTH                            2397K      263 
__AUTH_CONST                      19.1M      451 
__DATA                            39.9M      535 
__DATA_CONST                      18.0M      534 
__DATA_DIRTY                      1550K      180 
__FONT_DATA                          4K        1 
__LINKEDIT                       589.8M       82 
__OBJC_CONST                      2997K      231 
__OBJC_RO                         82.9M        1 
__OBJC_RW                         3152K        1 
__TEXT                           479.1M      551 
__UNICODE                          592K        1 
dyld private memory               1024K        1 
mapped file                      164.2M       39 
shared memory                      880K       15 
===========                     =======  ======= 
TOTAL                              2.7G     3239 
TOTAL, minus reserved VM space     1.8G     3239 

-----------
Full Report
-----------

{"app_name":"Cog","timestamp":"2022-06-09 15:32:32.00 -0700","app_version":"2217","slice_uuid":"fcdc0cf6-cfc2-31ac-8ca7-3823cbe81a24","build_version":"2217-g91898e9e","platform":1,"bundleID":"org.cogx.cog","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.3 (21E230)","incident_id":"DACB1143-2182-4509-9A12-E6C21DE6FDD2","name":"Cog"}
{
  "uptime" : 57000,
  "procLaunch" : "2022-06-09 15:32:27.2086 -0700",
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,3",
  "procStartAbsTime" : 1372726904740,
  "coalitionID" : 16708,
  "osVersion" : {
    "train" : "macOS 12.3",
    "build" : "21E230",
    "releaseType" : "User"
  },
  "captureTime" : "2022-06-09 15:32:31.9071 -0700",
  "incident" : "DACB1143-2182-4509-9A12-E6C21DE6FDD2",
  "bug_type" : "309",
  "pid" : 18653,
  "procExitAbsTime" : 1372839198490,
  "translated" : false,
  "cpuType" : "ARM-64",
  "procName" : "Cog",
  "procPath" : "\/Applications\/Cog.app\/Contents\/MacOS\/Cog",
  "bundleInfo" : {"CFBundleShortVersionString":"2217","CFBundleVersion":"2217-g91898e9e","CFBundleIdentifier":"org.cogx.cog"},
  "storeInfo" : {"deviceIdentifierForVendor":"D0C5470F-B3B4-5AA0-BB4E-6689A589A649","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "org.cogx.cog",
  "crashReporterKey" : "1957DD90-0247-E660-DACC-8558592BD035",
  "wakeTime" : 14723,
  "sleepWakeUUID" : "9A896018-9511-4FAD-B2A6-5E6F8D7EB3CD",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x00000001a20adf4c","rawCodes":[1,7013588812],"type":"EXC_BREAKPOINT","signal":"SIGTRAP"},
  "termination" : {"flags":0,"code":5,"namespace":"SIGNAL","indicator":"Trace\/BPT trap: 5","byProc":"exc handler","byPid":18653},
  "asi" : {"libsystem_c.dylib":["Thread is not a member of the workgroup"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 10,
  "threads" : [{"id":597317,"queue":"com.apple.main-thread","frames":[{"imageOffset":39368,"symbol":"objc_release","symbolLocation":88,"imageIndex":0},{"imageOffset":58052,"symbol":"AutoreleasePoolPage::releaseUntil(objc_object**)","symbolLocation":196,"imageIndex":0},{"imageOffset":43780,"symbol":"objc_autoreleasePoolPop","symbolLocation":212,"imageIndex":0},{"imageOffset":269176,"symbol":"_CFAutoreleasePoolPop","symbolLocation":32,"imageIndex":1},{"imageOffset":218364,"symbol":"-[NSAutoreleasePool drain]","symbolLocation":140,"imageIndex":2},{"imageOffset":206532,"symbol":"-[NSApplication run]","symbolLocation":648,"imageIndex":3},{"imageOffset":15784,"symbol":"NSApplicationMain","symbolLocation":1132,"imageIndex":3},{"imageOffset":20616,"symbol":"start","symbolLocation":516,"imageIndex":4}]},{"id":597339,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":5}]},{"id":597340,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":5}]},{"id":597341,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":5}]},{"id":597342,"frames":[{"imageOffset":8312,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":5}]},{"id":597344,"frames":[{"imageOffset":6436,"symbol":"semaphore_timedwait_trap","symbolLocation":8,"imageIndex":6},{"imageOffset":86108,"imageIndex":7},{"imageOffset":378652,"symbol":"__NSThread__start__","symbolLocation":808,"imageIndex":2},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":5},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":5}]},{"id":597367,"name":"com.apple.NSEventThread","frames":[{"imageOffset":6352,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":6},{"imageOffset":7488,"symbol":"mach_msg","symbolLocation":76,"imageIndex":6},{"imageOffset":543772,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":372,"imageIndex":1},{"imageOffset":536780,"symbol":"__CFRunLoopRun","symbolLocation":1180,"imageIndex":1},{"imageOffset":533648,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":1},{"imageOffset":1763220,"symbol":"_NSEventThread","symbolLocation":196,"imageIndex":3},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":5},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":5}]},{"id":597371,"name":"AMCP Logging Spool","frames":[{"imageOffset":6412,"symbol":"semaphore_wait_trap","symbolLocation":8,"imageIndex":6},{"imageOffset":125484,"symbol":"caulk::mach::semaphore::wait_or_error()","symbolLocation":28,"imageIndex":8},{"imageOffset":10108,"symbol":"caulk::concurrent::details::worker_thread::run()","symbolLocation":56,"imageIndex":8},{"imageOffset":9116,"symbol":"void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*)","symbolLocation":96,"imageIndex":8},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":5},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":5}]},{"id":597376,"name":"com.apple.audio.toolbox.AUScheduledParameterRefresher","frames":[{"imageOffset":6412,"symbol":"semaphore_wait_trap","symbolLocation":8,"imageIndex":6},{"imageOffset":125484,"symbol":"caulk::mach::semaphore::wait_or_error()","symbolLocation":28,"imageIndex":8},{"imageOffset":10108,"symbol":"caulk::concurrent::details::worker_thread::run()","symbolLocation":56,"imageIndex":8},{"imageOffset":9116,"symbol":"void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*)","symbolLocation":96,"imageIndex":8},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":5},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":5}]},{"id":597388,"frames":[{"imageOffset":245580,"symbol":"os_workgroup_interval_start.cold.1","symbolLocation":24,"imageIndex":9},{"imageOffset":120012,"symbol":"os_workgroup_interval_start","symbolLocation":304,"imageIndex":9},{"imageOffset":75068,"symbol":"-[Node startWorkslice]","symbolLocation":76,"imageIndex":10},{"imageOffset":72088,"symbol":"-[InputNode process]","symbolLocation":460,"imageIndex":10},{"imageOffset":74772,"symbol":"-[Node threadEntry:]","symbolLocation":56,"imageIndex":10},{"imageOffset":378652,"symbol":"__NSThread__start__","symbolLocation":808,"imageIndex":2},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":5},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":5}]},{"triggered":true,"id":597389,"threadState":{"x":[{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":5815400025176539165},{"value":5815400025176539165},{"value":18446744066696377483},{"value":1},{"value":3235905532},{"value":1088419840},{"value":1086324736},{"value":18446744073709551615},{"value":18446744073709551604},{"value":8523513552},{"value":0},{"value":5349910400},{"value":0},{"value":5083717688},{"value":4315955200},{"value":6162313440},{"value":4315955200},{"value":4315955200},{"value":4315955200},{"value":4315955200},{"value":4315955200}],"flavor":"ARM_THREAD_STATE64","lr":{"value":5558567847095623500},"cpsr":{"value":1610616832},"fp":{"value":6162295792},"sp":{"value":6162295792},"esr":{"value":4060086273,"description":"(Breakpoint) brk 1"},"pc":{"value":7013588812,"matchesCrashFrame":1},"far":{"value":4388241408}},"frames":[{"imageOffset":245580,"symbol":"os_workgroup_interval_start.cold.1","symbolLocation":24,"imageIndex":9},{"imageOffset":120012,"symbol":"os_workgroup_interval_start","symbolLocation":304,"imageIndex":9},{"imageOffset":75068,"symbol":"-[Node startWorkslice]","symbolLocation":76,"imageIndex":10},{"imageOffset":145872,"symbol":"-[ConverterNode process]","symbolLocation":132,"imageIndex":10},{"imageOffset":74772,"symbol":"-[Node threadEntry:]","symbolLocation":56,"imageIndex":10},{"imageOffset":378652,"symbol":"__NSThread__start__","symbolLocation":808,"imageIndex":2},{"imageOffset":29292,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":5},{"imageOffset":8332,"symbol":"thread_start","symbolLocation":8,"imageIndex":5}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7013634048,
    "size" : 253952,
    "uuid" : "4b5ab8fb-60e0-3992-ba0e-a073a3fa86a7",
    "path" : "\/usr\/lib\/libobjc.A.dylib",
    "name" : "libobjc.A.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7015505920,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5529600,
    "uuid" : "8e1809ff-f5b1-3d9e-be15-f2e7b1d8ce51",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "1858.112"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7031214080,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.Foundation",
    "size" : 4132864,
    "uuid" : "589677dd-19b7-3f93-b2b6-eed7117729ca",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Versions\/C\/Foundation",
    "name" : "Foundation",
    "CFBundleVersion" : "1858.112"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7061250048,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 15433728,
    "uuid" : "465b9570-6646-31ea-a082-ab0dfa538966",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2113.40.126"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4313890816,
    "size" : 393216,
    "uuid" : "fbb89662-e6f2-3434-b542-f75185ac5e74",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7015182336,
    "size" : 53248,
    "uuid" : "cee8bc77-6923-34d9-89a3-6f8f7279605e",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7014952960,
    "size" : 229376,
    "uuid" : "1d7b3b8e-75a1-34ea-aa52-9f7c23155c55",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4310859776,
    "CFBundleShortVersionString" : "2217",
    "CFBundleIdentifier" : "org.cogx.cog",
    "size" : 1638400,
    "uuid" : "fcdc0cf6-cfc2-31ac-8ca7-3823cbe81a24",
    "path" : "\/Applications\/Cog.app\/Contents\/MacOS\/Cog",
    "name" : "Cog",
    "CFBundleVersion" : "2217-g91898e9e"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7160135680,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.audio.caulk",
    "size" : 159744,
    "uuid" : "23d0d7ce-cb87-35f3-9c15-943bd8f6645a",
    "path" : "\/System\/Library\/PrivateFrameworks\/caulk.framework\/Versions\/A\/caulk",
    "name" : "caulk"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7013343232,
    "size" : 290816,
    "uuid" : "dc048e3b-e023-3d17-afe5-4ff3dc625608",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4315676672,
    "CFBundleIdentifier" : "org.cogx.cogaudio",
    "size" : 245760,
    "uuid" : "7d4f05cb-e6a0-3ac2-afc5-e495c5f2cb67",
    "path" : "\/Applications\/Cog.app\/Contents\/Frameworks\/CogAudio.framework\/Versions\/A\/CogAudio",
    "name" : "CogAudio",
    "CFBundleVersion" : "1.0"
  }
],
  "sharedCache" : {
  "base" : 7011893248,
  "size" : 3136438272,
  "uuid" : "00edbaf8-9281-3f26-b94f-e6a315e3a659"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)\nWritable regions: Total=1.3G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.3G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               384K        3 \nActivity Tracing                   256K        1 \nCG backing stores                 3520K        4 \nCG image                          32.3M       10 \nCG raster data                     384K        2 \nColorSync                          592K       26 \nCoreAnimation                     13.0M      142 \nCoreGraphics                        16K        1 \nCoreServices                      7424K        6 \nCoreUI image data                 2208K       18 \nFoundation                        1008K        3 \nImage IO                          4352K        2 \nKernel Alloc Once                   32K        1 \nMALLOC                           270.6M       61 \nMALLOC guard page                  192K       11 \nMALLOC_MEDIUM (reserved)         600.0M        5         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nSQLite page cache                 1088K       17 \nSTACK GUARD                       56.2M       11 \nStack                             13.3M       12 \nVM_ALLOCATE                        544K       15 \nVM_ALLOCATE (reserved)              64K        1         reserved VM address space (unallocated)\n__AUTH                            2397K      263 \n__AUTH_CONST                      19.1M      451 \n__DATA                            39.9M      535 \n__DATA_CONST                      18.0M      534 \n__DATA_DIRTY                      1550K      180 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       589.8M       82 \n__OBJC_CONST                      2997K      231 \n__OBJC_RO                         82.9M        1 \n__OBJC_RW                         3152K        1 \n__TEXT                           479.1M      551 \n__UNICODE                          592K        1 \ndyld private memory               1024K        1 \nmapped file                      164.2M       39 \nshared memory                      880K       15 \n===========                     =======  ======= \nTOTAL                              2.7G     3239 \nTOTAL, minus reserved VM space     1.8G     3239 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6112dda2fc54bc3389840642",
      "factorPackIds" : {
        "SIRI_DICTATION_ASSETS" : "628bd2fda5168570b594bb52"
      },
      "deploymentId" : 240000137
    },
    {
      "rolloutId" : "60356660bbe37970735c5624",
      "factorPackIds" : {

      },
      "deploymentId" : 240000027
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro18,3, BootROM 7459.101.2, proc 8:6:2 processors, 32 GB, SMC 
Graphics: Apple M1 Pro, Apple M1 Pro, Built-In
Display: Color LCD, 3024 x 1964 Retina, Main, MirrorOff, Online
Memory Module: LPDDR5
AirPort: Wi-Fi, wl0: Feb  8 2022 01:51:44 version 20.90.39.0.8.7.114 FWID 01-510a2aee
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

**Comment by kode54** [comment]
Yeah, this is because apparently, the beta of Ventura doesn't require something that Apple Support actually told another developer was required for this to work: The threads must already be set to real-time constraints before they may join an audio interval workgroup. I've fixed this with 7813712df3d0782b7bc38e71d2701961eccf9337 which I'll shortly push to a release.

**Comment by kode54** [comment]
This should be fixed now, closing unless you find it still crashes.

**Comment by tungol** [comment]
Looks good now. Thanks so much for all your work!
