### ISSUE TITLE
App Hang in BufferChain.m:175

### ISSUE THREAD

**Issue by kddlb** [losnoco/Cog#267]
## Error in Cog

**App Hang** in **BufferChain.m:175**
The app was terminated while unresponsive

[View on Bugsnag](https://app.bugsnag.com/losnoco/cog/errors/62a480f357649100097f4017?event_id=62a480f3009509d32d3c0000&i=gh&m=ci)

## Stacktrace

    Chain/BufferChain.m:175 - -[BufferChain dealloc]
    AudioPlayer.m:87 - -[AudioPlayer play:withUserInfo:withRGInfo:startPaused:andSeekTo:]
    Application/PlaybackController.m:225 - -[PlaybackController playEntry:startPaused:andSeekTo:]
    Application/PlaybackController.m:175 - -[PlaybackController playEntry:]
    Playlist/PlaylistController.m:1546 - -[PlaylistController didInsertURLs:origin:]
    Application/AppController.m:400 - -[AppController application:openFiles:]

[View full stacktrace](https://app.bugsnag.com/losnoco/cog/errors/62a480f357649100097f4017?event_id=62a480f3009509d32d3c0000&i=gh&m=ci)

*Created by Kevin López via Bugsnag*

**Comment by kode54** [comment]
Please feel free to describe here what was happening when this issue occurred to cause the output cleanup to hang while trying to start output again. The input handler appears to have hung up.

**Comment by kddlb** [comment]
[Please stop terminating the player randomly.](https://github.com/losnoco/Cog/issues/270)

Comment added in Bugsnag by Kevin López
[**App Hang** in **BufferChain.m:175**](https://app.bugsnag.com/losnoco/cog/errors/62a480f357649100097f4017?event_id=62a5c0b80094ffc889220000&i=gh&m=cm)

**Comment by kode54** [comment]
No idea what all these hangs were about. I've overhauled the relevant code significantly since then anyway, and Bugsnag is no longer employed by the project.

**Comment by kddlb** [comment]
An error linked to this issue has been reopened in Bugsnag
[**App Hang** in **BufferChain.m:175**](https://app.bugsnag.com/losnoco/cog/errors/62a480f357649100097f4017?event_id=62b3cb8e00950cb31ffb0000&i=gh&m=ra)

**Comment by kddlb** [comment]
Bugsnag is no longer tracking our project.

Comment added in Bugsnag by Kevin López
[**App Hang** in **BufferChain.m:175**](https://app.bugsnag.com/losnoco/cog/errors/62a480f357649100097f4017?event_id=62b3cb8e00950cb31ffb0000&i=gh&m=cm)
