### ISSUE TITLE
CUE sheets for M4A files don't read track titles / artists

### ISSUE THREAD

**Issue by JayB1988** [losnoco/Cog#268]
Opening a CUE sheet pointing to an M4A file no longer reads track titles and artists. This used to work before (I can't remember which version, must be 1 or 2 years ago). It still works for MP3 files.
![Bildschirmfoto 2022-06-11 um 22 31 23](https://user-images.githubusercontent.com/57588676/173203993-ea208b07-966c-4045-9090-ab98d81d6ddc.png)

Cog version is 2243, OS is Monterey 12.4. As you can see on the screenshot, the CUE sheets are pretty much identical except for the file they're pointing at. Changing "WAVE" to "MP3" or "M4A" doesn't change a thing. 
VLC opens the same CUE sheets flawlessly so it's not a file issue. And Cog used to do it too earlier. 

For comparison, here's the same CUE sheet opened in version 1148:
![Bildschirmfoto 2022-06-11 um 22 39 47](https://user-images.githubusercontent.com/57588676/173204183-64d95831-5f3d-49ce-b71e-b8f5697c0841.png)

It doesn't make a difference if I open the file via double-click or drag'n'drop.

**Comment by kode54** [comment]
The FILE declarations should have the type of "WAVE" not "M4A". I'm surprised the cue sheet parser I'm using even allows arbitrary values there.

**Comment by JayB1988** [comment]
I just tried changing that to see if it makes a difference. Originally it was "WAVE" but it didn't work with that either. Sorry for the confusion. My files are all marked as "WAVE".

**Comment by kode54** [comment]
Hmm, must be merging the file and cuesheet tags backwards, if the file's source tags are overriding the cuesheet's tags. I'll fix this tonight.

**Comment by kode54** [comment]
This should be fixed now.

**Comment by JayB1988** [comment]
Yes, it works now perfectly! Thank you very much!

And ironically it's much faster than opening the CUE sheets of MP3 files. These take a few seconds with the CPU at 100%. And also skipping tracks takes some time. But that's no priority for me personally as most of my CUE sheets are with M4A files.

**Comment by kode54** [comment]
MP3 files should be handled much better now. Full file scanning is no longer employed for files without Xing/LAME or iTunes ID3v2 headers, so length will now be estimated as if the files are CBR.
