### ISSUE TITLE
EXC_BAD_ACCESS in MADDecoder.m:640

### ISSUE THREAD

**Issue by kddlb** [losnoco/Cog#269]
## Error in Cog

**EXC_BAD_ACCESS** in **MADDecoder.m:640**
Attempted to dereference garbage pointer 0x7fa504efb000.

[View on Bugsnag](https://app.bugsnag.com/losnoco/cog/errors/62a4fccc1b78d900080d11ad?event_id=62a4fccc00951401af590000&i=gh&m=ci)

## Stacktrace

    Plugins/MAD/MADDecoder.m:640 - -[MADDecoder readAudio:frames:]
    CueSheetDecoder.m:321 - -[CueSheetDecoder readAudio:frames:]
    Chain/InputNode.m:183 - -[InputNode process]
    Chain/Node.m:209 - -[Node threadEntry:]

[View full stacktrace](https://app.bugsnag.com/losnoco/cog/errors/62a4fccc1b78d900080d11ad?event_id=62a4fccc00951401af590000&i=gh&m=ci)

*Created by Kevin López via Bugsnag*

**Comment by kode54** [comment]
This appears to be caused by not zeroing _outputFrames when opening a file, and the object gets reused to open another file.
