### ISSUE TITLE
Add able to copy track Title/Artist/etc

### ISSUE THREAD

**Issue by LennyLip** [losnoco/Cog#273]
First, thank you for the best audio player for MacOS!

**Describe**
I want to copy the track Title to search it on Google and can't find the way to do it. Also, the Info inspector does not show long length title fully. 

**Screenshots**
<img width="395" alt="Screenshot 2022-06-16 at 16 49 40" src="https://user-images.githubusercontent.com/955994/174086741-485baa5a-4223-4bf0-8375-495eef1fb370.png">

**Version information:***
 - macOS version: 12.4 (21F79)
 - Cog version: 2275 (2275-g0997ca2c)

**Comment by LennyLip** [comment]
> which formats all available fields of the playing track into a single copied string. The default hotkey is Cmd+Ctrl+C.

Thanks! It's working, but not so simple for users, I think. As far as the second issue: width of the inspector is maximized on the screenshot above.

**Comment by kode54** [comment]
I've added the ability to copy "spam" formatted text of all selected playlist entries when using the standard copy operation on the playlist. The formatted entries from the playlist will have their index numbers prepended to them, like a list. This release is coming soon.

**Comment by LennyLip** [comment]
Is it hard task to make text in Info Inspector selectable/copyable?

**Comment by kode54** [comment]
We're working on it.
