### ISSUE TITLE
[Cog 2298-g5a6295be] Streams do not update metadata

### ISSUE THREAD

**Issue by bmosley** [losnoco/Cog#275]
**Describe**
When listening to a stream playlist (ogg in my case) VLC is able to update the stream title/metadata when the track changes. In Cog it seems to use the same general URL title.

**To Reproduce** (delete if not applicable)
1. Unfortunately the stream was temporary but using an Icecast2 server, connect using Cog "Add URL..." menu
2. add the url and stream.ogg mount point
3. let several tracks play and view the title in cog

**Expected behavior**
I would expect the title to update with the actual metadata from the stream

**Screenshots**
VLC vs Cog
![Screen Shot 2022-06-17 at 09 14 54](https://user-images.githubusercontent.com/705077/174337919-d0a541f6-200b-4415-bbd8-786752301f36.jpg)

**Version information:***
 - Cog version: Cog 2298-g5a6295be

**Comment by kode54** [comment]
I need a stream to test. You may mail me at cogstream@kode54.net if you have privacy concerns.
