### ISSUE TITLE
Add support for .wav inside .cue

### ISSUE THREAD

**Issue by LennyLip** [losnoco/Cog#277]
As I remember, foobar20000 can open .cue with wrong described extension. With Cog is working opening flac file (it's find .cue and loads split tracks). It will be nice if we can open tracks with a wrong cue file too.

**Comment by LennyLip** [comment]
<img width="114" alt="Screenshot 2022-06-19 at 09 15 25" src="https://user-images.githubusercontent.com/955994/174468642-fe1f42ec-5f3c-4c1d-a1bd-3a5eb71c911c.png">
<img width="213" alt="Screenshot 2022-06-19 at 09 15 13" src="https://user-images.githubusercontent.com/955994/174468643-5d446756-345f-41c9-9dca-7a4680749868.png">

**Comment by kode54** [comment]
No, foobar2000 cannot open CUE with the wrong filename in the CUE sheet. You must edit the CUE sheet to point to the FLAC. I could add this, but then it would be a matter of doing a raw file search, every single time you reference a track from the CUE.

**Comment by LennyLip** [comment]
Ok, thank you.

**Comment by kode54** [comment]
Incidentally, foobar2000 does open the file with the correct name, regardless of whether the CUE says it is "WAVE" or "MP3", but really only supports "WAVE" in that field. But it does require a correct filename.

**Comment by LennyLip** [comment]
Yes, I've meant correct filename and wrong extension inside .cue in the same directory (as on screenshots). There is a lot of software that leave .wav in cue (instead of .flac) during cd grabbing.
