### ISSUE TITLE
Updates within App Sandbox should work as of 2395-g271b9b34

### ISSUE THREAD

**Issue by kode54** [losnoco/Cog#279]
I forgot to enable some entitlements when switching Sparkle versions, to enable the sandbox. Version 2355-g6fb991f9 should allow it to work, so subsequent updates should work from that version.

**Comment by LennyLip** [comment]
<img width="611" alt="Screenshot 2022-06-22 at 13 53 00" src="https://user-images.githubusercontent.com/955994/175012138-b8ad9bcf-5b09-43a3-a179-31bcbf0b6aa8.png">
<img width="257" alt="Screenshot 2022-06-22 at 13 53 07" src="https://user-images.githubusercontent.com/955994/175012129-1ce63b4e-6d0c-4baf-8773-19e9453256d6.png">

**Comment by kode54** [comment]
Sandboxed versions can't be updated using Sparkle until you get to the current version as of this post, 2395-g271b9b34.

**Comment by reagle** [comment]
I got the latest and was prompted about a sandbox and don't know what it is. Perhaps provide an explanation.

**Comment by kode54** [comment]
Fine. I'll add an explanation.

**Comment by kode54** [comment]
I've changed the descriptions on the dialogs, to better reflect what they are for. The dialogs still function the same. Update will come when I have it built.

**Comment by kode54** [comment]
This has long since passed out of relevance, especially with years of updates.
