### ISSUE TITLE
Xcode 14 will no longer support building for targets older than 10.13

### ISSUE THREAD

**Issue by nevack** [losnoco/Cog#282]
Topic.
https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes

> **Known Issues:**
> * Xcode 14 supports building applications that target macOS 10.13, iOS 11, tvOS 11, watchOS 4, and later. Xcode incorrectly shows some unsupported deployment targets in the project editor. (93995391)
> ** Deprecations:**
> * Building for deployment to OS releases older than macOS 10.13, iOS 11, tvOS 11, and watchOS 4 is no longer supported. (92834476)

As of Xcode 14 Beta 2 this versions are not shown and Cog's project target is shown as `Default`, probably because main Project has target 10.12.
Also warnings are emitted on build, as subprojects have their target in range from 10.8 to 10.12.

@kode54 Christopher, what do you think about it? Do you plan to raise minimum target to 10.13 any time soon?
At least 10.13 is supported on 12-year old Macs.

**Comment by kode54** [comment]
I will drop 10.12. But the projects can't be raised if I don't control them. The Ogg and Vorbis and Opus projects are all pretty much verbatim from upstream, but I guess I can increment the copies I have locally.

**Comment by kode54** [comment]
Let's not forget that 13.4 and newer have that toolbar bug. Has it been confirmed fixed by 14 beta 2?

**Comment by kode54** [comment]
It happens on 10.13 - 10.15, at least. Maybe even 12.4. The issue was that the toolbar did not allow customization after the default options had been dragged into it.

**Comment by kode54** [comment]
Then we can go forward with bumping the requirements to macOS 10.13 or newer. Also, there are several places in the app that check for `@available(macOS 10.13, *)`, one of which is a minimum point release of 10.13, but the rest are KeyedArchiver replacements that require 10.13.0, and can safely eliminate that conditional fallback.

**Comment by kddlb** [comment]
Closed as per 2c2a0581266c7fdca9358fcc3659209ebc7a9abc.
