### ISSUE TITLE
Empty play list positions after Cog restart

### ISSUE THREAD

**Issue by LennyLip** [losnoco/Cog#283]
After cue has been added - it works ok, but after restart the app it add the empty positions:

**Screenshots**
<img width="1038" alt="Screenshot 2022-06-23 at 10 49 28" src="https://user-images.githubusercontent.com/955994/175245851-b31164dc-ca86-4508-868a-e9dcbc2ca24f.png">

**Version information:***
 - Cog version: Version 2395 (2395-g271b9b34)

**Comment by reagle** [comment]
Confirm. I received 2405 this morning via homebrew (I wish there was a cog-stable) and my window looked like this.

<img width="932" alt="Screen Shot 2022-06-23 at 08 48 03" src="https://user-images.githubusercontent.com/596814/175303560-985a72c6-769c-4171-a7d2-da9ad07caece.png">

I deleted all configuration and restarted, and the file finder on the left is empty. I can reselect a folder and it will populate, but not upon a new launch.

<img width="926" alt="Screen Shot 2022-06-23 at 08 49 23" src="https://user-images.githubusercontent.com/596814/175303721-665f2b0e-8e58-4923-8af8-bb0ab6f5ae89.png">

Also, I don't recall configuring any fonts, but I notice that they are smaller in 2405.

**Comment by LennyLip** [comment]
1) Hangup up when open folder with name like "FolderName.ape". Cog trying to add the whole folder instead of opening it.
2) !!! **Hangup up when trying to open ANY .cue file after the last update.** There are empty list in play list after a force restart.
<img width="744" alt="Screenshot 2022-06-25 at 08 32 38" src="https://user-images.githubusercontent.com/955994/175759804-e7c20ed8-0ca1-4244-aeff-2740317dabed.png">

**Comment by kode54** [comment]
Adding CUE sheets takes a while. Sorry if there is not more progress display.

**Comment by kode54** [comment]
Also, adding FLAC files with embedded CUE sheets takes a while, too.

**Comment by LennyLip** [comment]
> Adding CUE sheets takes a while. Sorry if there is not more progress display.

Ok, thanks. Looks like it working now. Steps:

Open **folder** with .cue extension (hangup) -> Open **file** with .cue extension (hangup) -> Open .flac (Open ok, w\o splitting) -> Add path to sandbox Pop-up (add music folder) -> Wait a while -> cue works.

**Comment by kode54** [comment]
Dammit, I knew I forgot something.

**Comment by LennyLip** [comment]
>!!! Hangup up when trying to open ANY .cue file

**Comment by kode54** [comment]
It does not. If you add your library folders to the preferences.

**Comment by LennyLip** [comment]
>!!! Hangup up when trying to open ANY .cue file

Sorry, sent the message too early. 
Same issue with recently copied files. I copy a new cue files in Sandbox and can't open it. It seems I need to run command to re-scan sandbox folder?

**Comment by LennyLip** [comment]
Ok, it's after around 10 minutes.

**Comment by kode54** [comment]
How many CUE sheets are you adding?

**Comment by LennyLip** [comment]
> How many CUE sheets are you adding?

**Losslees folder:** (134,7 GB on disk) for 6 285 items
Recently, copied single folder (1 cue + 1 ape).

**Comment by kode54** [comment]
You're in luck: I just uploaded a fix for much of CUE's info loading problems. Although there are still some minor problems with FLAC files, due to how libFLAC works, and due to nested info loading from the same track.

**Comment by LennyLip** [comment]
I've got the addition issue when I open cue file. I have flac files with é symbol. When I try to opan cue file, this files looks like:
<img width="1022" alt="Screenshot 2022-06-26 at 11 49 39" src="https://user-images.githubusercontent.com/955994/175807074-3482f336-1f13-4855-b4b1-2fea28f1f93e.png">

**Comment by kode54** [comment]
Re-run the path suggester, then re-add your files you the playlist.

**Comment by kode54** [comment]
I really need to do a first launch wizard to suggest the user add all their common Music directories to the settings.

**Comment by LennyLip** [comment]
> Re-run the path suggester, then re-add your files you the playlist.

Ops, thanks, sorry, my bad, it was just incorrect CUE file. (uppercase é)
<img width="236" alt="Screenshot 2022-06-26 at 12 23 57" src="https://user-images.githubusercontent.com/955994/175807836-dba71e80-0b2c-430c-91cb-35e5d5b961ea.png">
