### ISSUE TITLE
Playlist kills Cog

### ISSUE THREAD

**Issue by ThomRoss** [losnoco/Cog#286]
I have this weird issue on two of my iMacs running macOS High Sierra 10.13.6. 
Opening any .m3u/.m3u8 playlist freezes Cog, so I have to force quit the application and run it again.
I tried deleting the app with AppCleaner and downloading it again but to no avail.
Please find a playlist attached. Cheers! ⚙️
[playlist.m3u.zip](https://github.com/losnoco/Cog/files/8984959/playlist.m3u.zip)

**Comment by LennyLip** [comment]
read this thread https://github.com/losnoco/Cog/issues/283#issuecomment-1166198766

**Comment by ThomRoss** [comment]
Thanks, @LennyLip!
I added my music folder path to sandbox (I had to wait a while, as you pointed out), and my .m3u playlists indeed do work again.
