### ISSUE TITLE
Bug: Empty file drawer despite right permissions

### ISSUE THREAD

**Issue by minthemiddle** [losnoco/Cog#287]
**Describe**
After an update to Version 2443 (2443-g5f2335b7) and giving permission to the music library path, the file drawer is completely empty.

**Expected behavior**
All folders, subfolders and files within the path with permission show up in file drawer

**Screenshots**

![Preferences_und_Cog_und_Issues_·_losnoco_Cog](https://user-images.githubusercontent.com/1950766/175804801-45e69625-493a-4854-8eb0-9c904eb4bb0f.jpg)

**Version information:***
 - macOS version: 12.4
 - Cog version: Version 2443 (2443-g5f2335b7)

**Additional context**
- Opening files directly from the path in Cog plays those without showing anything in the file drawer, I tried it with individual songs and playlist files.
- Of course, there are music files in the path, with prior Cog versions the file drawer showed files

**Comment by kode54** [comment]
You have to restart the player or reselect the path in the File Tree for it to reload the file listing.

**Comment by minthemiddle** [comment]
I did restart and reselect the path multiple times, after the 3x time, it worked again.

**Comment by kode54** [comment]
There's a bug with the sandbox code, and only Apple can tell me how to fix it. You must manually select your music folder as the path for that tree list. The default path is in the sandbox container, for some stupid ass reason that only makes sense to Apple.
