### ISSUE TITLE
Empty folder view on restart

### ISSUE THREAD

**Issue by reagle** [losnoco/Cog#289]
When closed and restarted, the view to the folders (from which to add or set playlist) is empty. cog: 2455,03a2c0c1

<img width="520" alt="Screen Shot 2022-06-27 at 07 06 46" src="https://user-images.githubusercontent.com/596814/175927989-f22f42f8-46d8-4008-9417-d74363508ddf.png">

**Comment by reagle** [comment]
Perhaps this is #288, but it is closed so I did not see it on default github view of issues; will try those instructions now.

**Comment by kode54** [comment]
Open `Preferences`, navigate to `General`, right or ctrl click the list, select the bottom option, then restart the player.

**Comment by kode54** [comment]
The update should be live now.

**Comment by reagle** [comment]
I meant how do I truly remove any trace of Cog. I don't understand what is going on with the empty folder pane, and want to do a fresh install. When I uninstall via brew, there's still files such as:

    $HOME/Library/Application Scripts/org.cogx.cog
    $HOME/Library/Containers/org.cogx.cog/Data/Library/Application Support/Cog
    $HOME/Library/Containers/org.cogx.cog/Data/Library/Application Support/org.cogx.co
    $HOME/Library/Containers/org.cogx.cog/Data/Library/Application Support/org.cogx.cog
    $HOME/Library/Containers/org.cogx.cog/Data/Library/HTTPStorages/org.cogx.co
    $HOME/Library/Containers/org.cogx.cog/Data/Library/HTTPStorages/org.cogx.cog
    $HOME/Library/HTTPStorages/org.cogx.cog

and even when I delete all of those and go into preferences, I still see my global hotkeys are configured, so I'm wondering if things are sticking around.

**Comment by reagle** [comment]
Do you mean the player file tree? (Versus something about the sandbox.) I find it handy to have my genre folders there for easy access. I just don't know why it's unpopulated when I restart cog.

<img width="337" alt="Screen Shot 2022-06-29 at 14 15 28" src="https://user-images.githubusercontent.com/596814/176507448-4a970187-664a-459f-913c-da441f717b7d.png">

**Comment by nevack** [comment]
> Do you mean the player file tree? (Versus something about the sandbox.) I find it handy to have my genre folders there for easy access. I just don't know why it's unpopulated when I restart cog. I then have to click on the folder and re-select my music folder to get it back.
> 
> <img alt="Screen Shot 2022-06-29 at 14 18 33" width="314" src="https://user-images.githubusercontent.com/596814/176507959-f8210bf9-e234-4890-9b19-dcf2d4c95f1f.png">

Same issue I have. If I reselect folder filetree shows OK.

**Comment by kode54** [comment]
Select your folder again manually with the provided button.
