### ISSUE TITLE
Please bring back the File Tree!

### ISSUE THREAD

**Issue by JuanDouek** [losnoco/Cog#291]
The File Tree is the main reason I'm using Cog.
Since Version 2487 the File Tree was removed, the changelog says:
"Remove the file tree, as Sandbox does not permit"

Is this temporary?
There must be a way to implement it.

**Comment by kode54** [comment]
I brought it back, but it will require using the Choose button to pick a base path. Choosing a path with the drop list is not guaranteed to work properly.

**Comment by zearp** [comment]
Same here, file tree is the main reason. Can the choose button be hidden? It really stands out. 

As an aside it would be awesome if we can go back to the default colours where it follows the systems theme. The orange really does not match the rest of the desktop.

I also noticed that double clicking on a file no longer starts to play it, no matter what I set in the settings it just clears the queue and does not start playing the song I double clicked. I come from an older version and got very used to this behaviour.

**Comment by kode54** [comment]
Please don't post issues and then delete them.

If you don't like the accent color, go to System Preferences, General, Accent Color, and disable the "Multicolor" setting. This setting was added at some point in the macOS development life cycle, and allows app developers to provide their own accent colors. If you don't want this, disable it.
