### ISSUE TITLE
Need source of earlier releases

### ISSUE THREAD

**Issue by mattneub** [losnoco/Cog#294]
I made a big mistake and allowed Cog to update itself and now it doesn't work. I need to get back to release 2203, but it isn't listed on the Downloads page, and I have no backup. Is there a place where all previously released builds are available? Thanks. (Ideally what I'd like to do is try every subsequent release until I come to the first one that doesn't work, and then just go back one.)

**Comment by kode54** [comment]
It doesn't work? Describe the issue. I can supply a link to 2203, but I'd like to get the latest version working for you as well.

**Comment by kode54** [comment]
Here's 2203, for what it's worth. I'd be interested in any crashes you observed, though. Fixing bugs is what I'm about.

https://cogcdn.cog.losno.co/Cog-eaa73bc5.zip

**Comment by mattneub** [comment]
The latest version is 2514. When I drop a .cue file on it, it can't seem to find / resolve the accompanying .flac file. 2203 was working fine.

**Comment by kode54** [comment]
The current version is in the App Sandbox. You'll have to add your root music directories to the file permission grant dialog for things like CUE and M3U and PLS to resolve their contents. I'm still not sure how to make it automatically ask for permission for dependent tracks like that.

You can also import your old main playlist by migrating the contents of `~/Library/Application Support/Cog` to `~/Library/Containers/org.cogx.cog/Data/Application Support/Cog`, trashing the existing contents of the target folder first. But you'll need to set up permissions once you do that:

1) Open Preferences.
2) Select the General pane.
3) Right/Ctrl click on the list box there.
4) Select "Suggest Paths" or the equivalent there, it's the bottom option.
5) Select some root folders in the list that pops open by checking them in the list. You need not check the same root folder twice, the list is provided to allow as coarse or fine grained permission as possible.
6) Click the Apply button to launch Folder Open dialog prompts which will add permissions for the checked folders.

I really need to make it possible to automatically grant permission for playlists and CUE sheets, but unfortunately, that requires processing them twice: Once to determine their contents, then ask permission to actually access their contents, then process their contents.

**Comment by mattneub** [comment]
Thanks but I'm sticking with 2203 and many thanks for providing it! I still think it would be a kindness to have a page that allows one to obtain earlier releases.

**Comment by kode54** [comment]
I only provide earlier releases as needed for OS compatibility. It is preferred if users would not run older versions at all. Just don't report any issues you have with running that version. And I won't respond to any crash reports from anything that old, either.

**Comment by kode54** [comment]
Sorry about that, I was just a bit annoyed that you were writing off all future releases. I have made changes with 2518, when uploaded, which will make adding arbitrary .CUE/.M3U/.PLS files much more convenient. Well, at least, a lot more convenient than it is now with a fresh install.

**Comment by mattneub** [comment]
👍 I see how this works now, thanks (and I'll describe it, for future readers):

* In the short run, if a drag-and-drop comes in from a cue sheet in a location that doesn't already have permission, we're now opening a Choose Folder dialog that offers to let me grant permission to the containing folder (though it is not entirely obvious that that is what it's doing).
* In the long run, as you say, I can just manually grant permission to the whole disk in the Folder Access Paths and presto, we're back to normal.

Here's an idea. To ease this transition for existing users, one possibility might be to detect, on opening a cue or similar, that there are no existing Folder Access Paths, and put up a dialog explaining the change and suggesting that the user set the whole disk as a folder access path. Otherwise it does feel like mysterious arbitrary breakage (which is how I experienced it); my thought is that the dialog would take away the mystery.

**Comment by kode54** [comment]
It's automatically adding grants for individual files and for folders added. Adding CUE or M3U or PLS tries to add the folder that contains that file. For some reason, macOS isn't showing the titles on the file open dialogs.
