### ISSUE TITLE
Double clicking a file or folder in the file tree no longer starts playback

### ISSUE THREAD

**Issue by zearp** [losnoco/Cog#296]
**Describe**
Double clicking on a file or folder does not start playback anymore. When double clicking on a folder with many files I can see the bottom of the windows display this:
```
loading metadata for tracks - processing files...
```
The queue is made but playback does not start. Double clicking a file in the queue does start playback.
**To Reproduce** (delete if not applicable)
1. Install latest version (2514-g7f1c337e)
2. Add music base folder
3. Double click file or folder in file tree
4. Playback does not start

**Expected behavior**
Playback starting

**Screenshots**

![Screenshot 2022-07-04 at 12 44 26](https://user-images.githubusercontent.com/63272687/177139604-8c7a8693-f920-47d1-bdf8-d8427b85ce34.png)

***Version information:***
 - macOS version: 12.4
 - Cog version: 2514-g7f1c337e

**Comment by zearp** [comment]
Same behaviour with 2518. I can see it loading metadata 9never seen that before) but it doesn't start playback.

**Comment by kode54** [comment]
Did you change the Playlist settings tab? There are two items there controlling what to do when adding files.

**Comment by kode54** [comment]
What format files are you adding? How are you adding them?

**Comment by kode54** [comment]
Oh, I see what you mean. I'll see if I can fix that.

**Comment by kode54** [comment]
This should be fixed by 2520.

**Comment by zearp** [comment]
Can confirm it works again, radially the files load almost as fast as before the sandboxing! Very nice, thanks!

**Comment by zearp** [comment]
Can confirm it works again, additionally adding a lot of files goes almost as fast as before the sandboxing! Very nice given sandbox limitations, thanks!

**Comment by kode54** [comment]
The `Suggest Paths` option is about to get a lot faster, too. At least, if you're using network shares. Local storage wasn't noticeably slower with the previous setup.
