### ISSUE TITLE
Crash on Cog 2545-g0732b176

### ISSUE THREAD

**Issue by nevack** [losnoco/Cog#299]
**Describe**
Crash on double clicking folder in File Outline.

**To Reproduce**
1. Open Cog.app
2. Double Click on folder in File Outline

**Expected behavior**
Playlist is created from this folder contents.

**Screenshots**

**Version information:***
 - macOS version: 12.4
 - Cog version: 2545-g0732b176

**Additional context**
File Outline root is set to folder inside SMB Share.

**Comment by nevack** [comment]
https://pastebin.com/sTshbEXF

**Comment by kode54** [comment]
Fixed, uploading a new build shortly.

**Comment by kode54** [comment]
The issue was with adding URLs to the playlist when the open action was set to clear the playlist first.
