### ISSUE TITLE
Will cog support adplug?

### ISSUE THREAD

**Issue by palxex** [losnoco/Cog#3]
One of my favorite vgm format, RIX, seems only supported in adplug.

**Comment by kode54** [comment]
Done. Enjoy.

**Comment by palxex** [comment]
Thanks very much! So fast!
In future version wishes more tweakable option be added to prefereces, if the original panel in fb2k adplug plugin could be available in Cog too, that will be best:)
If surrounding will be added later, I've a little more suggestion: make the FREQ_OFFSET customizable. The original value, 128.0 seems still too small for some music, that makes (sometime) sound strange. Considers more situation, customizable should be better. 
Below is a example file( with original CSurroundopl it will sound strange at about the third second, 384.0 eliminated it ), if that could helps.

[MUS70.rix.zip](https://github.com/kode54/Cog/files/1670896/MUS70.rix.zip)
