### ISSUE TITLE
Add "Playlist Font Size" as an appearance option

### ISSUE THREAD

**Issue by eduardodesigner** [losnoco/Cog#300]
The playlist area in Cog has very small fonts when compared to certain default macOS app's list views, such as the list view in Finder, for example. It would be a nice new feature to be able to customize the font size.

**Comment by eduardodesigner** [comment]
Oh wow, I never realized that. It even shows that option in the menubar.
Thanks for the quick response. For me, that solves the issue.

Making the default font size slightly larger, as you suggested, will definitely make it look more comfortable for first time users.

**Comment by kode54** [comment]
I'm changing the default to the Regular control size, which ends up being 13. I don't hard code the unit size, just reading the control size for Regular, instead of Small.

**Comment by eduardodesigner** [comment]
Thank you very much!

**Comment by kode54** [comment]
It's in build right now, and will appear in updates when complete in about 15-30 minutes. About a day if you're using the App Store version.
