### ISSUE TITLE
FreeSurround branch could use some extra attention

### ISSUE THREAD

**Issue by kode54** [losnoco/Cog#308]
**Describe**
The code within that branch is experimental, and strangely causes app instability, compared to the incredible mess of changes I attempted to make that had no effect on the crashes. I leave it up to someone else to help figure out if these are worth fixing.

**To Reproduce** (delete if not applicable)
1. Check out the fsurroundExperiments branch.
2. Build it.
3. Attempt to play stereo audio in the debugger.
4. Crash spectacularly in inconsistent ways.

**Expected behavior**
Audio should just work, and it should have no effect if the signal is not stereo, or if the FSurround is disabled.

**Version information:***
 - macOS version: 12.4
 - Cog version: The HEAD of the fsurroundExperiments branch

**Additional context**
This code took hours of messing around to adapt. Meh.

**Comment by kode54** [comment]
Okay, it's ready for translation.

Guess what? The ceiling we hit? It's the 512KiB per-thread stack size limit! We were probably already pushing it kind of close with random things. Now I've bumped the stack size limit to 1MiB.

**Comment by kode54** [comment]
Calling: @LennyLip @paxcoder

**Comment by paxcoder** [comment]
I will translate it, no worries.
@kode54 
I probably translated some strings from it.
thanks for mentioning.

**Comment by LennyLip** [comment]
I am on it, what we need t do? I don't see fsurroundExperiments branch.

**Comment by LennyLip** [comment]
<img width="579" alt="Screenshot 2022-07-14 at 17 30 41" src="https://user-images.githubusercontent.com/955994/179007146-f0963568-067f-4015-bf9c-e0f460cf2166.png">
<img width="361" alt="Screenshot 2022-07-14 at 17 29 08" src="https://user-images.githubusercontent.com/955994/179007155-2655b815-1a33-465f-ac76-c48f81974a66.png">

The lost word in the end of string
