### ISSUE TITLE
I can't switch languages, and my app doesn't switch when I clear all files.

### ISSUE THREAD

**Issue by paxcoder** [losnoco/Cog#309]
Hi.
I tried to make it work, but just nope, it fails, it launches still in English.

**Comment by kode54** [comment]
Sorry about that. I've activated the translations, but they're missing some strings, especially a lot of the MainMenu.strings entries are still in English. I had trouble even finding anything that was actually translated.

**Comment by LennyLip** [comment]
Ru works fine, thanks! But fixed width in settings Window looks not so good:
<img width="732" alt="Screenshot 2022-07-13 at 06 59 44" src="https://user-images.githubusercontent.com/955994/178647789-28273d8b-3a0e-426d-97ce-5095674c56ed.png">

**Comment by paxcoder** [comment]
But how I switch to it?

**Comment by kode54** [comment]
I should have proofread the strings files you sent me. There were several misplaced quotation marks in a few places, and a string of text outside of the quotation marks in one place. Another string, the quotation marks were both at the end of the string, leaving the string unquoted.

I also noticed that you translated the string token names in the localizable dictionary file used for the total duration. That's an understandable error.

I really wish I had proofread that before attempting to build with it. Sorry about that, you probably have a hard time. I see you mentioned screen readers, I suppose you're also vision impaired? It can be hard to process source code without the ability to see it, even with the aid of a perfect screen reader.

I've forwarded your email address to my co-developer for invitation to the translation service, you should be able to make future changes to the translation there in a much easier way than fiddling with source code. I hope. And I hope this hasn't soured our relationship as volunteer translator and app developer.

A new build will be submitted to the App Store and uploaded to the web site shortly.

**Comment by kode54** [comment]
Incidentally, I was only able to even notice it with the aid of syntax highlighting. Otherwise, I would have had a hard time spotting the errors.
