### ISSUE TITLE
Outdated links

### ISSUE THREAD

**Issue by formaj** [losnoco/Cog#311]
The links in the help section are outdated:

[Cog homepage](http://cogx.org/)
[Cog forums](http://cogx.org/forums/)
[Developer email](mailto:vspader@users.sourceforge.net)

**Comment by kode54** [comment]
I don't even maintain the help document, so I should just remove it.

**Comment by kode54** [comment]
I could update it, but maybe someone else would like to sync it with the web site contents?

**Comment by kode54** [comment]
This should be fixed now.

**Comment by kode54** [comment]
Help book has been removed.
