### ISSUE TITLE
code signature issue in build 2592

### ISSUE THREAD

**Issue by core-code** [losnoco/Cog#312]
all previous builds were properly signed with a "Developer ID" signature:

Developer ID: Christopher Snowhill (N6E749HJ2X)

the newest build does a broken signature - "Apple Development" signatures are not meant for distributing software and cannot usually be launched by users:

```
codesign -dvv 'Cog.app'
Executable=Cog.app/Contents/MacOS/Cog
Identifier=org.cogx.cog
Format=app bundle with Mach-O universal (x86_64 arm64)
CodeDirectory v=20500 size=39544 flags=0x10000(runtime) hashes=1225+7 location=embedded
Signature size=4767
Authority=Apple Development: Created via API (6U9DBS23H9)
Authority=Apple Worldwide Developer Relations Certification Authority
Authority=Apple Root CA
Signed Time=12 Jul 2022 at 06:15:39
Info.plist entries=45
TeamIdentifier=N6E749HJ2X
Runtime Version=12.3.0
Sealed Resources version=2 rules=13 files=231
Internal requirements count=1 size=176
```

**Comment by kode54** [comment]
Oops. I guess I didn't export the notarized build before uploading. That's what I get for updating from my tablet.

I've reuploaded the correct build.

**Comment by core-code** [comment]
thanks!

**Comment by core-code** [comment]
thanks love to hear it!
