### ISSUE TITLE
[Cog 2643] Double-clicking audio file opens a file selector dialog box instead of immediately playing the audio file

### ISSUE THREAD

**Issue by classicjazz** [losnoco/Cog#316]
**Describe**
After double-clicking an audio file, Cog displays a file selector dialog box. Cog does not immediately list the file or start playback. At the bottom of Cog, it says "playlist loader inserting files - collecting files - 20.0% complete". After the user closes the dialog box using the cancel button, the file then appears in Cog and audio playback commences.

**To Reproduce** (delete if not applicable)
1. Double-click on an audio file. It doesn't matter whether this is local file system or hosted on an SMB server

**Expected behavior**
Double-clicking the file should display the file in Cog and immediately start playback, without displaying the file selector dialog box

**Version information:***
 - macOS version: 12.5
 - Cog version: 2643

**Additional context**
Add any other context about the issue here.

**Comment by kode54** [comment]
This is intentional, and required to allow indexing of playlists and CUE sheets. You are supposed to click OK to the dialog box.

**Comment by kode54** [comment]
I cannot make this clearer without adding even further dialog boxes.

**Comment by classicjazz** [comment]
I don't fully understand the playlist indexing use case. 

Here, I am streamripping live radio shows... I listen to the program, then delete the file (similar to DVR'ing TV shows). Cog enables me to play audio without adding audio files to my Apple Music library, needing to manage a playlist, etc. A simple double-click on the audio file without dialog boxes would be the path with the least number of steps.

I would suggest that if the only file(s) that are passed to Cog have a known extension such as M4A, MP3, etc., then play them in the sequence passed without dialog boxes/additional user intervention.

**Comment by kode54** [comment]
If you want to change it, you're welcome to make your own fork.

**Comment by classicjazz** [comment]
Testing this some more, I believe the issue is associated with the new sandboxing code. If you click cancel (because you double-clicked the file initially that you want to play and don't want to select a different file), it adds only that file path to the folder access path. So every subsequent time you double-click a file, the same issue presents itself including the file selector dialog box every time.

However, if you click OK, then it adds the parent folder (not just the current file) to the folder access path. After that,  there are no modal file selector dialog boxes and you can double-click any other audio file in that folder without seeing the file selector dialog box.

**Comment by kode54** [comment]
What can I say, App Sandbox is purely designed to inconvenience both users and developers.

**Comment by kode54** [comment]
Tell you what, I can sort of fix this. I can parse the output of what a container (PLS/CUE/M3U) returns and decide whether to add it to the exceptions list first. PLS and M3U can be scanned for only remote URLs, which don't need exemptions.

**Comment by kode54** [comment]
I have reduced the dialog to only appear if a container has local files referenced, and added a warning dialog that can be dismissed either once or for the rest of the session.

**Comment by classicjazz** [comment]
Thank you for looking into this further.

The dialog box is informative. However, you should update the new text to say "Open" rather than "OK" on the following folder open dialog box.

Two idiosyncrasies that I notice:

If the user selects Open, both the file itself and its parent folder are added to the Folder Access Paths. I recommend only adding the parent folder.

If the user deletes both of those (the file and folder access paths) during the same session and then clicks on another audio file, instead of displaying the file picker, there is a Grant Access to Select Folders including parent folder and parent of the parent folder. (e.g. /Volumes/radio and /Volumes). Selecting Enabled, then Apply, then displays the File Selector (defaulting to /Volumes) then a second time (defaulting to /Volumes/radio). Somehow, I then ended up with /Volumes/radio displayed twice in Folder Access Paths but no ability to delete either/both instances until I quit Cog and restart the app.

Also, Cog crashed on me while testing these steps. See the crash report with 

Crashed Thread:        0  Dispatch queue: com.apple.main-thread
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000000000000001c
Exception Codes:       0x0000000000000001, 0x000000000000001c
Exception Note:        EXC_CORPSE_NOTIFY
Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [24923]

**Comment by kode54** [comment]
The crash and removing should be fixed in an upcoming version. Eliminating redundant paths is planned, maybe, but will probably be more work than it's worth.
