### ISSUE TITLE
[Feature Request] Automatically add an entire folder when adding single files

### ISSUE THREAD

**Issue by floralskirts** [losnoco/Cog#317]
**Describe**
Would love the option to automatically add all tracks from a folder to the playlist similar to IINA. Thanks!

**To Reproduce**
1. Open track
2. Only that track plays in Cog and that's it

**Expected behavior**
1. Open track
2. That track plays, and the rest of the tracks in the folder are queued for playing next

**Version information:***
 - macOS version: Monterey 12.4 (21F79)
 - Cog version: Version 2649 (2649-ge796e23a)

**Comment by kode54** [comment]
No, this will just confuse people. What if people really do want to just add individual files and not an entire folder? Just add the entire folder directly.

**Comment by floralskirts** [comment]
IINA does this by having a "Add files in the same folder automatically" option under their Playlist settings. I don't understand how it could have much potential to confuse as an option and why the same can't be implemented for Cog. It's a feature I miss from using IINA, as I often catch myself clicking one file expecting the rest to be added. Not a dealbreaker, of course. Thanks anyway.

**Comment by floralskirts** [comment]
Noticed you implemented this—thanks! The only problem I noticed is that if there's a .cue file in the folder, it will add everything twice + the .cue file, but I imagine that's an easy fix. Thanks again.

**Comment by kode54** [comment]
Not as easy as you think: Every CUE returns thecuename.cue#tracknumber as an URL instead of the referenced file. I'd have to add a service to resolve every CUE sheet path to its referenced paths on every sweep of the directory.

**Comment by floralskirts** [comment]
Sorry, my comment was made out of ignorance. I know next to nothing about programming. I hope it can be fixed and again, I appreciate you adding the feature. I donated $5 in support of the program.

**Comment by kode54** [comment]
I'll try to fix it somehow.

**Comment by kode54** [comment]
It was easier than I thought to fix. A fix is incoming.

**Comment by floralskirts** [comment]
Perfect, thanks again!

**Comment by kode54** [comment]
Sorry for a bit of yelling or whatever when I first saw this, I always get a bit anxious when people ask me to implement new features when I don't already know how I'm going to do it. I do eventually come around and get into the thick of it, and implement the features.

**Comment by slitrov** [comment]
I understand and it's all good!
