### ISSUE TITLE
[Feature Request] Add Sample Rate and Bits Per Sample columns to the playlist view

### ISSUE THREAD

**Issue by floralskirts** [losnoco/Cog#318]
**Describe**
Have playlist column options to show Sample Rate and Bits Per Sample. Helpful in a time where 24-bit and varying sample rates are more common.

**To Reproduce** (delete if not applicable)
1. Right-click on playlist column options and neither of these are options.

**Expected behavior**
1. Right-click on playlist column options and both of these are (separate) options.

**Version information:***
 - macOS version: Monterey 12.4 (21F79)
 - Cog version: Version 2649 (2649-ge796e23a)

**Additional context**
Thanks for considering!

**Comment by kode54** [comment]
Implemented by 5f87475f2d448c03ec064340d2557816e8184583 and 360464ceec108c089954c7ab0a58b859d5010c73 in their respective branches.
