### ISSUE TITLE
SPC not playing properly

### ISSUE THREAD

**Issue by efdevelopers** [losnoco/Cog#320]
SPC plays very slowly and stuttering.

- macOS version: 10.15.7
- Cog version: 2677 (2677-g93e3dd7a)

[102 Chrono Trigger.spc.zip](https://github.com/losnoco/Cog/files/9262262/102.Chrono.Trigger.spc.zip)

**Comment by kode54** [comment]
Oops, I broke the GME input with my changes almost a month ago and never noticed. Thanks for bringing this to my attention. I'll fix this shortly.

**Comment by efdevelopers** [comment]
Many thanks for fixing it.
