### ISSUE TITLE
The program crashes when trying to open the OGG file 

### ISSUE THREAD

**Issue by SokoloffA** [losnoco/Cog#330]
**Describe**
I noticed that the program crashes when trying to open [my test OGG file](https://github.com/flacon/flacon/files/9795469/01-track.ogg.zip).  Other players play it successfully.

**To Reproduce** (delete if not applicable)
1. Download file https://github.com/flacon/flacon/files/9795469/01-track.ogg.zip
2. Unzip file
3. Open in the player
4. The program crashes

**Version information:**
 - macOS version: 10.15.7 intel
 - Cog version: Version 2688 (2688-g37065adf)

**Comment by kode54** [comment]
This has been fixed by e4bc5853add9ece195faaf9b217ebf565df27670 / e25cfbf22c8d8c53ab5dfdfd602779c642da6a38, which will be released shortly.
