### ISSUE TITLE
Delay when clicking play, previous or next

### ISSUE THREAD

**Issue by jnak** [losnoco/Cog#337]
**Describe**
There is almost 3 secs delay when starting the playback of a track

**To Reproduce** (delete if not applicable)
A1. Click play
B1. Or, While a track is playing, click next or previous
C1. Or double-click a track in the playlist

**Expected behavior**
It should start playback immediately

**Version information:***
 - macOS version: Ventura 13.0
 - Cog version: Version 2722 (2722-g5e0a3308)

**Additional context**
This happens with any track, including when the playlist is almost empty (ie contains only one track)

**Comment by jnak** [comment]
The bug started happening with version Version 2721. I confirmed Version 2719 does not have the issue

**Comment by kode54** [comment]
The bug has been around for far longer, but has become exacerbated by more recent changes. It should be fixed now by 2727.

**Comment by jnak** [comment]
This seems to be fixed! I could not find the most recent version on the website but found it on the Mac App store - I didn't know it was released there as well. Sweet!

Thanks!

**Comment by kode54** [comment]
Sorry about the website trouble, it should be working now. It was fetching a manifest file from the wrong place. It has also been redesigned a bit.

I do try to update both distributions at the same time, though. The App Store version has about a 4-12 hour turnaround on upload to availability.
