### ISSUE TITLE
App crashes on startup (macOS Mojave 10.14.6, 2013 Mac Pro)

### ISSUE THREAD

**Issue by RiotNrrrd** [losnoco/Cog#338]
This has been happening for the last few releases (including the current one).

If I run _/Applications/Cog.app/Contents/MacOS/Cog_ directly, it comes up.

I get a few messages but it runs fine.

`objc[47597]: Class RedundantPlaylistDataStore is implemented in both /Applications/Cog.app/Contents/Frameworks/CogAudio.framework/Versions/A/CogAudio (0x10cb30438) and /Applications/Cog.app/Contents/MacOS/Cog (0x10ca39688). One of the two will be used. Which one is undefined.
objc[47597]: Class SHA256Digest is implemented in both /Applications/Cog.app/Contents/Frameworks/CogAudio.framework/Versions/A/CogAudio (0x10cb306b8) and /Applications/Cog.app/Contents/MacOS/Cog (0x10ca398b8). One of the two will be used. Which one is undefined.
2022-12-10 14:36:54.492 Cog[47597:24244437] Unknown class NSSearchToolbarItem in Interface Builder file at path /Applications/Cog.app/Contents/Resources/Base.lproj/MainMenu.nib.
2022-12-10 14:36:54.968 Cog[47597:24244437] +[NSSegmentedCell(StaticMethods) _image_state_for_visual_state:style:trackingMode:]: Unknown NSSegmentVisualState 0
2022-12-10 14:36:54.968 Cog[47597:24244437] +[NSSegmentedCell(StaticMethods) _image_state_for_visual_state:style:trackingMode:]: Unknown NSSegmentVisualState 0
2022-12-10 14:36:55.054 Cog[47597:24244437] +[NSSegmentedCell(StaticMethods) _image_state_for_visual_state:style:trackingMode:]: Unknown NSSegmentVisualState 0
2022-12-10 14:36:55.054 Cog[47597:24244437] +[NSSegmentedCell(StaticMethods) _image_state_for_visual_state:style:trackingMode:]: Unknown NSSegmentVisualState 0
2022-12-10 14:36:55.071 Cog[47597:24244437] [Firebase/Crashlytics] Version 9.1.0`

But if I double-click the app icon or do an _open /Applications/Cog.app_, it crashes.

I tried removing the saved state files in _~/Library/Containers/org.cogx.cog/Data/Library/Saved Application State/org.cogx.cog.savedState_ but it didn't change anything.

Here's the crash log if it helps.

`Process:               Cog [48080]`
`Path:                  /private/var/folders/*/Cog.app/Contents/MacOS/Cog`
`Identifier:            org.cogx.cog`
`Version:               2728 (2728)`
`Code Type:             X86-64 (Native)`
`Parent Process:        ??? [1]`
`Responsible:           Cog [48080]`
`User ID:               501`

`Date/Time:             2022-12-10 14:41:54.339 -0800`
`OS Version:            Mac OS X 10.14.6 (18G9323)`
`Report Version:        12`
`Anonymous UUID:        657F697B-2B3D-EE6E-64A1-0D1F96040DAD`

`Time Awake Since Boot: 2000000 seconds`
`System Integrity Protection: disabled`

`Notes:                 Translocated Process`

`Crashed Thread:        0  Dispatch queue: com.apple.main-thread`

`Exception Type:        EXC_CRASH (SIGABRT)`
`Exception Codes:       0x0000000000000000, 0x0000000000000000`
`Exception Note:        EXC_CORPSE_NOTIFY`

`Application Specific Information:`
`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: bundleProxy != nil'`
`terminating with uncaught exception of type NSException`
`abort() called`

`Application Specific Backtrace 1:`
`0   CoreFoundation                      0x00007fff347a4191 __exceptionPreprocess + 256`
`1   libobjc.A.dylib                     0x00007fff5f0b53c6 objc_exception_throw + 48`
`2   CoreFoundation                      0x00007fff347bf196 +[NSException raise:format:arguments:] + 98`
`3   Foundation                          0x00007fff36a82171 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194`
`4   UserNotifications                   0x00007fff405c9328 -[UNUserNotificationCenter initWithBundleProxy:] + 292`
`5   UserNotifications                   0x00007fff405c9103 __53+[UNUserNotificationCenter currentNotificationCenter]_block_invoke + 81`
`6   libdispatch.dylib                   0x00007fff6082f63d _dispatch_client_callout + 8`
`7   libdispatch.dylib                   0x00007fff60830d4b _dispatch_once_callout + 20`
`8   UserNotifications                   0x00007fff405c90af +[UNUserNotificationCenter currentNotificationCenter] + 45`
`9   Cog                                 0x00000001028174af Cog + 275631`
`10  AppKit                              0x00007fff31ccdd49 -[NSCustomObject nibInstantiate] + 364`
`11  AppKit                              0x00007fff31ccdb7c -[NSIBObjectData instantiateObject:] + 267`
`12  AppKit                              0x00007fff31cccf11 -[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:] + 578`
`13  AppKit                              0x00007fff31ccb16c loadNib + 401`
`14  AppKit                              0x00007fff31cca8a2 +[NSBundle(NSNibLoading) _loadNibFile:nameTable:options:withZone:ownerBundle:] + 1294`
`15  AppKit                              0x00007fff31cca291 -[NSBundle(NSNibLoading) loadNibNamed:owner:topLevelObjects:] + 204`
`16  AppKit                              0x00007fff31cca053 +[NSBundle(NSNibLoading) loadNibNamed:owner:] + 446`
`17  AppKit                              0x00007fff31cbe0ad NSApplicationMain + 502`
`18  libdyld.dylib                       0x00007fff6087c3d5 start + 1`
`19  ???                                 0x0000000000000001 0x0 + 1`

`Thread 0 Crashed:: Dispatch queue: com.apple.main-thread`
`0   libsystem_kernel.dylib        	0x00007fff609b72c2 __pthread_kill + 10`
`1   libsystem_pthread.dylib       	0x00007fff60a72bf1 pthread_kill + 284`
`2   libsystem_c.dylib             	0x00007fff609216a6 abort + 127`
`3   libc++abi.dylib               	0x00007fff5db03641 abort_message + 231`
`4   libc++abi.dylib               	0x00007fff5db037df default_terminate_handler() + 267`
`5   libobjc.A.dylib               	0x00007fff5f0b777b _objc_terminate() + 97`
`6   libc++abi.dylib               	0x00007fff5db0f19e std::__terminate(void (*)()) + 8`
`7   libc++abi.dylib               	0x00007fff5db0f213 std::terminate() + 51`
`8   libdispatch.dylib             	0x00007fff6082f651 _dispatch_client_callout + 28`
`9   libdispatch.dylib             	0x00007fff60830d4b _dispatch_once_callout + 20`
`10  com.apple.UserNotifications   	0x00007fff405c90af +[UNUserNotificationCenter currentNotificationCenter] + 45`
`11  org.cogx.cog                  	0x00000001028174af 0x1027d4000 + 275631`
`12  com.apple.AppKit              	0x00007fff31ccdd49 -[NSCustomObject nibInstantiate] + 364`
`13  com.apple.AppKit              	0x00007fff31ccdb7c -[NSIBObjectData instantiateObject:] + 267`
`14  com.apple.AppKit              	0x00007fff31cccf11 -[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:] + 578`
`15  com.apple.AppKit              	0x00007fff31ccb16c loadNib + 401`
`16  com.apple.AppKit              	0x00007fff31cca8a2 +[NSBundle(NSNibLoading) _loadNibFile:nameTable:options:withZone:ownerBundle:] + 1294`
`17  com.apple.AppKit              	0x00007fff31cca291 -[NSBundle(NSNibLoading) loadNibNamed:owner:topLevelObjects:] + 204`
`18  com.apple.AppKit              	0x00007fff31cca053 +[NSBundle(NSNibLoading) loadNibNamed:owner:] + 446`
`19  com.apple.AppKit              	0x00007fff31cbe0ad NSApplicationMain + 502`
`20  libdyld.dylib                 	0x00007fff6087c3d5 start + 1`

**Comment by kode54** [comment]
Please move the app to your Applications folder, or somewhere outside of Downloads.

**Comment by RiotNrrrd** [comment]
> Please move the app to your Applications folder, or somewhere outside of Downloads.

I don't know what makes you think it's in _Downloads_ (it's not), given that I said

>> But if I [...] do an _open /Applications/Cog.app_, it crashes.

**Comment by kode54** [comment]
The crash log says it's translocated. That means it's not installed properly.

**Comment by RiotNrrrd** [comment]
> The crash log says it's translocated. That means it's not installed properly.

I downloaded the ZIP file and did a

`( cd /Applications ; unzip -q /path/to/ZIP/file ; sync ; sync )`

When it runs, it seems like it's getting translocated into _/private/var/folders/<folder>/Cog.app_ somehow.

**Comment by kode54** [comment]
`unzip` does not extract .app bundles correctly. You need to extract it either with the `ditto` command, or Finder.

**Comment by RiotNrrrd** [comment]
Extracting the ZIP file via Finder and moving the app into /Applications fixed it.  Thanks @kode54 !
