### ISSUE TITLE
[Feature request] Embedded lyrics support

### ISSUE THREAD

**Issue by vulpes-vulpeos** [losnoco/Cog#343]
**Describe**
Hello. Can you add a window/panel or something else which will show lyrics embedded into file? For example, USLT tag in .mp3 files.
I really want to replace iTunes with folder based music player but none of the players I tried has option to view embedded lyrics :(

**Comment by kode54** [comment]
I'm working on an unsynced lyrics display control. Once I have that working, I may look into implementing synchronized lyrics. May. Not sure how feasible that will be, considering I'm already having a hard time getting started on unsynced lyrics display. I'm trying, though.

**Comment by vulpes-vulpeos** [comment]
Thank you for adding lyrics window. Now Cog is main music player on my macbook :)
