### ISSUE TITLE
Crash when changing file associations

### ISSUE THREAD

**Issue by grishka** [losnoco/Cog#361]
**Describe**
Cog crashes when files are associated with it while it's running. Sometimes it also crashes just on its own with the same stack trace.

**To Reproduce** (delete if not applicable)
There are probably other ways to reproduce this but here's what does it reliably for me:
1. Make a folder with two audio files of different types (I did it with tracker modules, but it'd probably work with anything else too)
2. Make sure Cog is closed
3. Associate one file type with Cog through the Finder properties window as shown in the video below
4. Open this file, Cog launches
5. Associate the second file type with Cog
6. Watch it crash

**Expected behavior**
It shouldn't crash, obviously :)

**Screenshots**
Screencast of me reproducing the crash: https://disk.yandex.ru/i/deg8m5nvb-Iczw

**Version information:***
 - macOS version: 13.4
 - Cog version: Version 2762 (2762-g6c0db041e)

**Additional context**
Complete crash log: [Cog-2023-06-03-190102.txt](https://github.com/losnoco/Cog/files/11643143/Cog-2023-06-03-190102.txt)

**Comment by kode54** [comment]
Wow, I had no idea that file type association changing started notifying the app of anything. I'll have to debug this.

**Comment by kode54** [comment]
Would you mind consenting to the Firebase Crashlytics submission in Preferences, then trying to reproduce the crash? I can't make Xcode symbolicate the crash log you posted, and I can't reproduce the issue locally, either.
