### ISSUE TITLE
Stop stream links instead of pause

### ISSUE THREAD

**Issue by thenktor** [losnoco/Cog#363]
**Describe**
When playing internet streams (URLs) the music should be stopped instead of paused. If the music is paused for more then a few seconds apparantly the connection to the stream gets lost and when continuing playback only the remaining local buffer is played. After that playback stops.

**To Reproduce** (delete if not applicable)
1. Add a stream URL, e.g. http://mp3channels.webradio.rockantenne.de/classic-perlen
2. Play the stream for 30 seconds
3. Pause
4. Wait 15 seconds
5. Hit Play

**Expected behavior**
Start playback and continue playing. Instead it plays a few seconds and then stops.

**Version information:***
 - macOS version: 13.4
 - Cog version: Version 2771 (2771-gad9af1640)

**Comment by kode54** [comment]
I'll consider that the next time I'm capable of working on the player.

**Comment by kode54** [comment]
This has been implemented for a few versions now. Hope you find it behaves.
