### ISSUE TITLE
Add multiple stream URLs to playlist

### ISSUE THREAD

**Issue by thenktor** [losnoco/Cog#364]
**Describe**
Please make it possible to add multiple stream URLs to the playlist. At the moment the `File->Add URL...`dialogue clears the playlist and adds the new one, but it is actually perfectly possible to have multiple stream URLs in a playlist.

**Version information:***
 - macOS version: 13.4
 - Cog version: Version 2771 (2771-gad9af1640)

**Comment by kode54** [comment]
Change configuration option from "Open" or "Open and Play" to "Enqueue" or "Enqueue and Play". I really don't know why I left that as the default.

**Comment by thenktor** [comment]
Sorry, I've missed that option.
