### ISSUE TITLE
DSD playback is staticky unless DSD_DECIMATE is disabled

### ISSUE THREAD

**Issue by bmastenbrook** [losnoco/Cog#367]
**Describe**
DSD playback is staticky unless `DSD_DECIMATE` is redefined to `0` in `ChunkList.h`. If `DSD_DECIMATE` is defined to `0`, output level drops to "SACD 0dB" (aka -6dB) as expected, but output quality is good. 

**To Reproduce** (delete if not applicable)

1. Obtain a DSD file. The files I'm using are DSD64. You can obtain a [DSD64 sample from NativeDSD](https://www.nativedsd.com/product/ndsd017-nativedsd-music-free-starter-pack/) at no cost.
2. Play the file.

**Expected behavior**

Playback should be free of static or other artifacts.

**Version information:***
 - macOS version: 13.4
 - Cog version: Version 2777 (2777-g728ae813c)

**Comment by bmastenbrook** [comment]
Confirmed, this is fixed now. I suppose audio is still at -6dB compared to PCM; I've opened #368 as a feature request related to this.

**Comment by kode54** [comment]
It's really not -6 dB compared to PCM. The filter the decimator uses has a +6 dB gain anyway, which is why I correct it on output.
