### ISSUE TITLE
Hangs on loading stream

### ISSUE THREAD

**Issue by Volodymyr-13** [losnoco/Cog#370]
**Describe**
Double click on any next radio in playlist causes hang of the UI. 

1. Have a playlist with radio streams
2. Double click any
3. Try to access UI right after that
4. Notice UI is not responding, lags. 

**Expected behavior**
Load streams in the background. 

**Screenshots**

On this video I'm trying to play and then move window a bit, by lick and drag. As you can see it lags. 

https://www.youtube.com/watch?v=ad_njIhpSQM

**Version information:***
 - macOS version: 13.5
 - Cog version: 2794 (2794-gf642a066f)

**Comment by kode54** [comment]
Playback is now started asynchronously, or at least, the player core is invoked in the background. Seeking is also performed in the background. All other playback actions remain synchronous.

**Comment by Volodymyr-13** [comment]
Thanks, fixed.
