### ISSUE TITLE
Feature Request: Sort by rating

### ISSUE THREAD

**Issue by ademaro** [losnoco/Cog#375]
I'd like to sort the song list by rating. I know there is a more general (and extensive) issue #355, but maybe it would be faster to make a more localized one.

If you can tell me where to look and what approximately to fix, I'll try to do a PullRequest, but it's not for sure...

<img width="185" alt="Screenshot 2023-08-18 at 23 47 33" src="https://github.com/losnoco/Cog/assets/416356/0c2b6943-bd94-474d-b520-8f891d14175d">

Thanks in advance for any responses.

**Comment by kode54** [comment]
Wish I knew this one. I don't even know how to program the list control to use a different value for sorting the fields than what is displayed. Note that the list isn't fully populated with the data, a callback feeds out cell data on request, and the UI only requests cell data for what's visible, or when sorting the entries, I presume.

**Comment by kode54** [comment]
This is fixed by 0f6b403b4350bf762f6f30d8d67c5c0ee1d89471 / 16c1cf4b65bc65d66afb9836947c4804326345c8 which I will be pushing shortly.

**Comment by ademaro** [comment]
Thank you so much! This was really missed!
