### ISSUE TITLE
Runaway memory usage since Sonoma and/or latest Cog update

### ISSUE THREAD

**Issue by bhilimon** [losnoco/Cog#379]
I've been running Sonoma for about 1.5 weeks now and also upgraded to the latest Cog from the app store at that time (2846). Since then, Cog just endlessly uses more and more memory until my system completely crashes (Mac Mini M2). It was at 48g of memory/swap this morning and already back to 3+ gig in about 2 hours this morning. I play .mp3 files exclusively over a network share. Let me know if there is anything I can do help figure this out.

**Comment by bhilimon** [comment]
Actually, I see the Cog upgrade is newer than the Sonoma install. It's possible it started with the latest Cog and not Sonoma.

**Comment by bhilimon** [comment]
Little more messing around, it looks like just pausing a song for a second releases all of the memory, back down to a couple hundred meg. It does start climbing again though.

**Comment by ElbowBaggins** [comment]
I see this exact behaviour on the current latest stable Cog from the website, on Sonoma. Mac Studio M1 Max.

Pausing or changing tracks immediately frees the memory but usage climbs fairly linearly and constantly during playback. This doesn't _always_ happen, sometimes memory usage stays nominal during playback. However, when it _doesn't_, the describe effect occurs. I am not sure what causes it, I have observed this behaviour in multiple formats. NSF was the worst offender in my examination, but this correlation may be spurious.

**Comment by kode54** [comment]
I'll be looking at this and the SID crashing issue tonight and possibly also tomorrow if it takes me too long to fix them.

This one looks like it might be because I'm not using adequate `@autoreleasepool` blocks in the Converter thread, which I moved more work back to again. I forget if I had enough autoreleasepools there at all, or if I removed them after I simplified the converter.
