### ISSUE TITLE
Playback Control Toolbar Item Size

### ISSUE THREAD

**Issue by lucianmarin** [losnoco/Cog#4]
The Playback Control in the toolbar has 10 pt extra spacing on the right side. To fix it, you need to set maximum width to the same value as minimum width.

Minimum/maxium values: 121 width, 24 height

I wanted to create a pull request, but I get an error building it: `libbinio/src/binfile.cpp` is missing.

**Comment by kode54** [comment]
Did you remember to:

```
git submodule update --init --recursive
```

or simply check out the repository at the start with the `--recursive` switch?

**Comment by kode54** [comment]
This should be fixed. Closing.
