### ISSUE TITLE
Choppy audio playback

### ISSUE THREAD

**Issue by frothedoatmilk** [losnoco/Cog#407]
**Describe**
I just updated Cog from pre-speed control and now all audio playback sounds like it's being played through a taser. It sounds like the audio is cutting in and out at a pretty fast rate.

The speed of this varies in line with how fast the audio speed slider is set. You can't really tell what it sounds like until you slow your audio down to the slowest allowed (which for me was x0.2 speed).

I was only able to test using flac and mp3 files, but the issue was identical for both.

**To Reproduce**
1. Open Cog
2. Load a flac/mp3 file
3. Hit play
4. (optional, the issue occurred immediately for me) change playback speed.

**Expected behavior**
Audio playback smooth under 1.0x speed, and any other speed.

**Screenshots**
I don't really have any screenshots, but you can observe this happening by watching the visualizer while doing audio playback.

**Version information:***
 - macOS version: 14.7 (This is an M1 MacBook Pro)
 - Cog version: Version 2869 (2869-g58cbda594)

**Comment by kode54** [comment]
What sample rate is your sound output device set to? I can't reproduce this issue, either on an M1 Mac mini, or an M4 Pro Mac mini.

**Comment by frothedoatmilk** [comment]
48 kHz on a 32-bit float. I just tested again with both my headphones plugged into the 3.5mm jack on the laptop body, headphones plugged into a dock connected via USB-C, and the MacBook's main speakers, all with the same results. Is there some kind of logs I can send you?

**Comment by kode54** [comment]
Try wiping the configuration and see if it still does it? You can wipe just the Preferences file from the container, the Playlists/Media database should be fine to keep.

Also, try setting the sound output to 96kHz, since Cog internally outputs a mix to that. Strangely, I cannot reproduce any crackling audio on my dad's M1 Mac mini. Do you have any system software installed that hooks into sound output?

**Comment by frothedoatmilk** [comment]
Sorry, I'm not super familiar with MacOS file structures, where is the preferences file?
Tried swapping to all of the sample rates available (including 96 kHz) and there was no change in the sound.
The only thing I can think of is Zoom, because it creates a weird audio device, but it doesn't look like the audio is running through that? I'll try to remove Zoom and see what happens.

**Comment by kode54** [comment]
Quit Cog, then run from a terminal:

```
defaults delete org.cogx.cog
```

**Comment by frothedoatmilk** [comment]
The terminal command fixed it! Thank you.
