### ISSUE TITLE
FR: search

### ISSUE THREAD

**Issue by piaci** [losnoco/Cog#46]
is it possilbe make search work in path not only the current playlist?

**Comment by kode54** [comment]
Then I would need to figure out how to interface with Spotlight. Because I'm sure as hell not writing a directory crawler just to do my own file searching algorithm.

**Comment by piacimosca** [comment]
well, I mean in the file tree next to the playlist. then (I suppose) you already have the collection in hand.

**Comment by kode54** [comment]
This will require making it possible to apply the search filter to the folder view, which may be doable, but it will need drilling down every path tree to decide whether to hide it or not, based on whether any of their children match the filter. Hmm...

**Comment by kode54** [comment]
There already is a Spotlight dialog. But it won't automatically add files to the playlist. And it doesn't support arbitrary formats not supported by Spotlight, even if they're natively supported by the player.
