### ISSUE TITLE
Cog using default 1-2 outputs instead of system output

### ISSUE THREAD

**Issue by h-v-b** [losnoco/Cog#5]
I LOVE Cog and can't thank you enough for maintaining it.
I have one gripe, with it. Somewhere along the line, it seems that the audio routing got broken.
When using an external soundcard with multiple outputs, Cog is using the 1-2 outs by default, and there's no way to have it follow the System Output like it used to. 
In my case, it's 7-8. All other apps are outputting sound output defined in the Audio Midi setup app, except Cog.
Is there any chance to fix this?

**Comment by kode54** [comment]
https://github.com/kode54/Cog/blob/master/Audio/Output/OutputCoreAudio.m#L194-L223

Here it is, asking the device for its preferred stereo output channels. I don't know any other way, other than not supporting channel mapping at all.

**Comment by kode54** [comment]
@h-v-b Try again? It's supposed to be asking for whatever mapping your device supports that matches 1-8 MPEG channel layouts, whatever that may be configured as in Audio MIDI Settings.

**Comment by kode54** [comment]
Closing until further feedback is supplied.
