### ISSUE TITLE
Mini player bounces back when I tried to drag it down

### ISSUE THREAD

**Issue by htruong** [losnoco/Cog#6]
I often maintain a terminal or a remote desktop that I maximize and run Cog in the background. I want Cog to show the current song and some minimal control when I work. So I make the Mac OS dock about as big as the Cog mini-player window and drag it down to the very bottom of the screen, and at the area where the dock doesn't cover. The only problem is that the Cog window bounces back when I tried to drag it down, so it wouldn't go any lower than the screenshot. So my terminal covers the Cog song title when it loses focus :(

![screen shot 2018-03-21 at 12 36 16 pm](https://user-images.githubusercontent.com/146489/37723518-eade8a54-2d04-11e8-8811-7d669ca96f4b.png)

**Comment by htruong** [comment]
This is what happens when the Cog window loses focus...

![screen shot 2018-03-21 at 12 42 04 pm](https://user-images.githubusercontent.com/146489/37723665-4bd34f34-2d05-11e8-9c83-6de7c64bc27d.png)

**Comment by kode54** [comment]
Yes, macOS won't let you maintain windows below the top of the Dock. This is by design. Even if your Dock is somehow not filling the entire width of the screen.
