### ISSUE TITLE
Add screenshots to README.md

### ISSUE THREAD

**Issue by lambdaupb** [losnoco/Cog#7]
![mainwindow](https://user-images.githubusercontent.com/1890613/39100121-198c27d2-4685-11e8-9e25-ae5cdefb4461.png)
![main_with_inspector](https://user-images.githubusercontent.com/1890613/39100123-1c974560-4685-11e8-8b0f-d81ce5c7aa77.png)
![main_small](https://user-images.githubusercontent.com/1890613/39100148-aabb7eec-4685-11e8-8686-2330d2091b22.png)

Some screenshots would help a lot for newcomers to get a glance on what Cog is.
Feel free to just include the embedded ones I created for this purpose, consider them public domain without any attribution.

**Comment by megadr01d** [comment]
@esaruoho Yep.

https://github.com/iina/iina
https://github.com/iina/iina/blob/master/iina/Assets.xcassets/AppIcon.appiconset/256-1.png
https://raw.githubusercontent.com/iina/iina/master/iina/Assets.xcassets/AppIcon.appiconset/256-1.png

**Comment by nevack** [comment]
Fixed.
