### ISSUE TITLE
Title of the current track causes the contents of the window to shift downwards

### ISSUE THREAD

**Issue by sirburpalot** [losnoco/Cog#79]
To prevent this, the space under the toolbar where the title is displayed should always be present even when no track is currently playing; or else the title should not be displayed at all. There should probably be a toggle for this.

**Comment by kode54** [comment]
Some minor effort actually went into making this whole popover appear, but maybe some way could be added to make its animation also offset the scroll position of the playlist, so it doesn't shift everything downward. Of course, I will at least add an option to keep this, or hide it permanently, or show it permanently. Unfortunately, it will need a transformer for the text content if I do that, as with the current setup, even if it isn't hidden, when the PlayingEntry is unset, it becomes an empty string and shrinks to near zero height anyway.

**Comment by kode54** [comment]
This should only affect anything older than Big Sur / 11.0, where a window subtitle is not available.
