### ISSUE TITLE
Bad vertical alignment in the status bar

### ISSUE THREAD

**Issue by sirburpalot** [losnoco/Cog#80]
See the screenshot:
<img width="408" alt="Screenshot 2021-01-24 at 07 48 57" src="https://user-images.githubusercontent.com/1429516/105621465-abd4ad00-5e18-11eb-9e6b-5ba6afca16d5.png">

**Comment by kode54** [comment]
The current status bar is the footer bar of a control which offers top, middle/body, and bottom aligned features. The footer needs padding of its content cell to prevent this.

**Comment by nevack** [comment]
@kode54 I'll fix it while converting Main Window to use AutoLayout

**Comment by nevack** [comment]
I'll resolve it for now as this was merged.
