### ISSUE TITLE
Time remaining display shows strange results when no track is playing

### ISSUE THREAD

**Issue by kode54** [losnoco/Cog#85]
@nevack this one seems to be caused by your latest change to the time display? I'm not sure if it worked correctly before, or what it was or is doing. It doesn't *seem* to be displaying the time remaining for the entire playlist, at least.

**Comment by nevack** [comment]
I reverted locally and experience the same issue.

What's the intended behavior for this?

**Comment by kode54** [comment]
I'm not entirely sure what it's supposed to be doing here, and I don't think it's displaying the remaining time for the entire playlist. Perhaps reading int max or some other undefined behavior?

I don't know whether it would be better to show remaining time for the entire list, or just 0 when no track is playing.
