### ISSUE TITLE
Option for classic style dual row window title bar layout

### ISSUE THREAD

**Issue by radioproektor** [losnoco/Cog#86]
Hello. I noticed that after Cog-3b628c398 version you start to use single row (slim) window title bar. This may look modern and cool, but in reality this introduce some problems with usability:
1. Too small free space from top makes very hard to grab with mouse and move window.
2. Too small free space from sides don't allow to fit many buttons and same time wide enough seek slider.

Is it possible add option in preferences or in "View" menu to switch between modern and "classic" window title bar layout?

![Screen Shot 2021-01-26 at 10 19 42 AM](https://user-images.githubusercontent.com/35053925/105819889-79b27f00-5fc1-11eb-8913-97ecb998b371.jpg)

**Comment by nevack** [comment]
Hi, do you ask for option to enable pre-BigSur layout on BigSur?
I think on Catalina nothing has been changed changed.

**Comment by radioproektor** [comment]
I ask to enable pre-BigSur layout on pre-BigSur OS. I am on on Mojave 10.14.6 and layout in all versions released after Cog-3b628c398 look like this:
![Screen Shot 2021-01-27 at 1 31 57 AM](https://user-images.githubusercontent.com/35053925/105920205-a016ff80-603f-11eb-874b-ed44102a643c.jpg)

 Too small free space from top makes very hard to grab with mouse and move window. (probably not a problem on BigSur because it have larger default toolbar height)
 Too small free space from sides don't allow to fit many buttons and same time wide enough seek slider.

**Comment by nevack** [comment]
Ah, ok, I think it's possible

**Comment by nevack** [comment]
GitHub closed this automatically based on commit message, please check if this works in new version released.

Use `Toggle Toolbar Style` in `View` menubar submenu.
