### ISSUE TITLE
Option for Disc Number columns in Spotlight and Playlist?

### ISSUE THREAD

**Issue by radiosilence** [losnoco/Cog#87]
If you try to search for multi-disc albums the tracks currently come up collated, it would be good if we could either sort by filename or be able to orded by discnumber/tracknumber.

I can see from poking around in the xib that the columns are hardcoded, but I am not really experienced enough in native macOS development to know how to PR this myself :(

**Comment by nevack** [comment]
Nice addition, I think it's doable.

P.S.

> I am not really experienced enough in native macOS development to know how to PR this myself

To be honest, Cog is the first macOS project I contributed to. I had no previous Cocoa/ObjC experience.
So everything is possible 😄

**Comment by kode54** [comment]
Would a combined column be acceptable as an idea for implementation? It would also make it easier to sort, unless we also make it possible to sort by a separate value using padded numbers.

"discnumber.tracknumber"

1.01, 1.02, etc.

**Comment by radiosilence** [comment]
That would be absolutely great!

**Comment by kode54** [comment]
I have implemented this. Please reload your track information to see the new fields populated.
