### ISSUE TITLE
Main and mini window are not consistently the same color

### ISSUE THREAD

**Issue by kode54** [losnoco/Cog#95]
**Describe the bug**
Main window and mini window are not consistently the same color

**To Reproduce**
1. Go to main window
2. Go to mini window

**Expected behavior**
Windows should appear consistently similar to each other.

**Screenshots**
![Screen Shot 2021-02-07 at 21 42 47](https://user-images.githubusercontent.com/796316/107161923-bcc30980-6954-11eb-869d-87bbd238e2c3.png)
![Screen Shot 2021-02-07 at 21 43 00](https://user-images.githubusercontent.com/796316/107161924-bfbdfa00-6954-11eb-9138-2205e754e32b.png)

**Desktop (please complete the following information):**
 - macOS version: 10.13.6
 - Cog version: Presumably latest

**Additional context**
User emailed me these.

**Comment by nevack** [comment]
I think this is because of transparent Titlebar/Toolbar. Is this really a bug to consider?

**Comment by kode54** [comment]
For future consideration, maybe I should make the feedback button in the app open the GitHub issues page instead of sending me direct email.

**Comment by kddlb** [comment]
> For future consideration, maybe I should make the feedback button in the app open the GitHub issues page instead of sending me direct email.

I made it so that the contact page on the website links to the GitHub repository.

![image](https://user-images.githubusercontent.com/115702/107293297-2244f200-6a4a-11eb-9d84-faec62a96a6d.png)

**Comment by kode54** [comment]
So I may have less incidents of cases like this:

"Cog does not remember its position on screen after I quit it and relaunch it.
	Please fix this in the next version."

**Comment by nevack** [comment]
Changed feedback button url, now it points to GitHub Issue creation.
